examples/Resources/Private/Singles/Structures.html, src/Core/ViewHelper/AbstractViewHelper.php, src/Core/ViewHelper/ViewHelperInterface.php, src/Core/ViewHelper/ViewHelperInvoker.php, tests/Unit/Core/ViewHelper/AbstractViewHelperTest.php, tests/Unit/Core/ViewHelper/ViewHelperInvokerTest.php
=> [FEATURE] Allow any ViewHelper to accept undeclared arguments

src/Core/Parser/TemplateParser.php, src/View/AbstractTemplateView.php
Like the subject says, Fluid parser errors now echo the template identifier (unfortunately not the filename since there is no file name in the parser), the line number and the character number when parsing the template source. The pointers can then be included in a re-thrown error message.
Example error:
```
TYPO3Fluid\Fluid\Core\Parser\Exception: Fluid parse error in template Default_action_Default_1cb8dc11e29962882f629f79c0b9113ff33d6219, line 11 at character 3. Error: The ViewHelper "<f:serender>" could not be resolved.
Based on your spelling, the system would load the class "TYPO3Fluid\Fluid\ViewHelpers\SerenderViewHelper", however this class does not exist. (1407060572). Template code: <f:serender section="Foo" optional="1">
```
=> [FEATURE] Include line, character no. and Fluid code in parse errors

.travis.yml
=> [TASK] Do not allow any PHP flavor to error in tests

src/ViewHelpers/SpacelessViewHelper.php, tests/Unit/ViewHelpers/SpacelessViewHelperTest.php
```xml
<f:spaceless>
<div>
<div>
<div>text
text</div>
</div>
</div>
</f:spaceless>
```
Outputs:
```html
<div><div><div>text
text</div></div></div>
```
=> [FEATURE] SpacelessViewHelper to trim whitespace outside tags

src/Core/Parser/SyntaxTree/ViewHelperNode.php
* Avoids setting the rendering context (this gets done by the Invoker already; as is proper)
* Do not clone the "uninitialized" ViewHelper instance upon evaluating the rendering context (can *still* be done by Invoker if required/desired but is no longer default. Fixes: #5)
* Use `get_class` to read the obvious class name of already resolved ViewHelper, bypassing an already performed lookup in Resolver
* Change `getArgumentDefinitions` to read already retrieved argument definitions instead of consulting the Resolver (which would cache them, but still...)
* Changed order of logic in constructor to put simple assignments on top and rewriting logic on bottom
=> [TASK] Cleanup in ViewHelperNode

src/ViewHelpers/Format/CdataViewHelper.php, tests/Unit/ViewHelpers/Format/CdataViewHelperTest.php
Outputs tag content or "value" attribute wrapped in CDATA node.
=> [FEATURE] Cdata formatting ViewHelper

src/Core/Parser/TemplateParser.php
It is necessary for ExpressionNodes to be able to manipulate the RenderingContext (adding namespaces, ignoring namespaces, etc.) and the only way to allow this is to trigger evaluation during parse time.
=> [TASK] Evaluate ExpressionNodes during parse time

src/Core/Compiler/NodeConverter.php, src/Core/Parser/BooleanParser.php, src/Core/Parser/SyntaxTree/BooleanNode.php, src/Core/Parser/SyntaxTree/Expression/TernaryExpressionNode.php, tests/Functional/BaseConditionalFunctionalTestCase.php, tests/Functional/Cases/Conditions/BasicConditionsTest.php, tests/Functional/Cases/Conditions/TernaryConditionsTest.php, tests/Functional/Cases/Conditions/VariableConditionsTest.php, tests/Unit/Core/Compiler/NodeConverterTest.php, tests/Unit/Core/Parser/BooleanParserTest.php, tests/Unit/Core/Parser/SyntaxTree/BooleanNodeTest.php, tests/Unit/Core/Parser/SyntaxTree/Expression/TernaryExpressionNodeTest.php
Turning the BooleanNode into a seriously stable recursive boolean descent parser to allow all kinds of boolean combinations.
=> [FEATURE] Recursive descent boolean parser

src/Core/Parser/TemplateParser.php, tests/Unit/Core/Fixtures/TestViewHelper.php, tests/Unit/Core/Parser/TemplateParserTest.php, tests/Unit/Core/ViewHelper/ViewHelperInvokerTest.php
This change increases the percentage of covered code by adding additional test cases and refactoring the recursive array handling method in TemplateParser. No behaviors changed.
=> [TASK] Increase code coverage percentage

src/View/TemplatePaths.php
During the decoupling a decision was made to not use
array keys for the priority of template paths - instead,
the order of the array should determine the lookup order.
However, the TemplatePaths class of TYPO3Fluid had
received a sorting behavior that was intended for the
TemplatePaths class of TYPO3 CMS. This patch removes
that sorting behavior.
This fix must be followed up by a patch for TYPO3 CMS.
suggested strategy there is to override the setter methods
for paths and enforce the sorting there.
References: #104
References: https://forge.typo3.org/issues/75862
References: https://review.typo3.org/#/c/48279/
=> [BUGFIX] Do not sort by key when receiving paths arrays

composer.json
Fix version constraints to have reliable testing
Fix licence
Add atoloading for test fixtures
Remove unnecessary minimum stability setting
=> [TASK] Fix composer.json

src/View/TemplatePaths.php
Also catch exception that might occur second try, resolving paths
=> [TASK] Cleanup path resolving

src/Core/ViewHelper/AbstractViewHelper.php, tests/Unit/Core/ViewHelper/AbstractViewHelperTest.php
Typed arrays are missing. Don't know if that would not be to expensive.
=> [FEATURE] Support and validate array notation in argument types

src/ViewHelpers/Format/HtmlspecialcharsViewHelper.php
=> [BUGFIX] Use same encoding in static and non static call

src/Core/Parser/SyntaxTree/ObjectAccessorNode.php, tests/Unit/Core/Parser/SyntaxTree/BooleanNodeTest.php, tests/Unit/Core/Parser/SyntaxTree/ObjectAccessorNodeTest.php
=> [FEATURE] Remove all reserved variables except _all

src/Core/Parser/BooleanParser.php
- protect internal methods
- output a better „end of line“ exception
=> [TASK] Cleanup BooleanParser

tests/Unit/Core/ViewHelper/AbstractViewHelperTest.php
Adds a test to confirm operability of unit.
=> [TASK] Add unit tests for getFirstElementOfNonEmpty on VH

src/View/TemplatePaths.php
Binary is not a format for Fluid regardless.
=> [TASK] Force file_get_contents to read text files only

doc/FLUID_VIEWHELPERS.md
=> [TASK] Update outdated documentation

bin/fluid
Set new namespace from TYPO3Fluid in php comments
Resolves: #182
=> [TASK] Correct namespaces in comments

src/Core/Cache/FluidCacheWarmupResult.php, src/Core/Parser/SyntaxTree/ObjectAccessorNode.php, src/Core/Variables/JSONVariableProvider.php, src/Core/Variables/VariableProviderInterface.php, src/View/TemplatePaths.php, src/View/ViewInterface.php, src/ViewHelpers/SwitchViewHelper.php
* Removes some unused variables
* Corrects some method annotations
=> [TASK] Address issues reported as "major" by Scrutinizer

src/Core/Cache/FluidCacheWarmupResult.php, src/Core/Compiler/ViewHelperCompiler.php, src/Core/Parser/TemplateParser.php, src/Core/Variables/JSONVariableProvider.php, src/Core/Variables/StandardVariableProvider.php, src/Core/ViewHelper/AbstractViewHelper.php, src/View/TemplatePaths.php, src/ViewHelpers/SwitchViewHelper.php
Annotations of variable types and casts to explicit
required type.
=> [TASK] Address issues reported as "minor" by Scrutinizer

src/Core/Cache/SimpleFileCache.php
=> [BUGFIX] Use glob() to find cache files in SimpleFileCache

src/ViewHelpers/SpacelessViewHelper.php
=> [BUGFIX] Set escapeOutput to false

src/ViewHelpers/DebugViewHelper.php
This just changes the @retrurn annotation to @return in the DebugViewHelper.php.
=> fix typo in annotation

src/Core/Variables/VariableExtractor.php, tests/Unit/Core/Variables/VariableExtractorTest.php, tests/Unit/ViewHelpers/Fixtures/UserWithoutToString.php
=> [FEATURE] Add ability to extract has* accessors

.travis.yml
=> [TASK] Remove test coverage of HHVM from travis.yml

src/Core/Cache/FluidCacheWarmupResult.php, src/Core/Cache/StandardCacheWarmer.php, src/Core/Compiler/AbstractCompiledTemplate.php, src/Core/Compiler/NodeConverter.php, src/Core/Parser/BooleanParser.php, src/Core/Parser/Interceptor/Escape.php, src/Core/Parser/SyntaxTree/BooleanNode.php, src/Core/Parser/SyntaxTree/Expression/CastingExpressionNode.php, src/Core/Parser/SyntaxTree/Expression/MathExpressionNode.php, src/Core/Parser/SyntaxTree/Expression/TernaryExpressionNode.php, src/Core/Parser/TemplateParser.php, src/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php, src/Core/Parser/TemplateProcessorInterface.php, src/Core/Rendering/RenderingContext.php, src/Core/ViewHelper/AbstractViewHelper.php, src/Core/ViewHelper/Traits/CompileWithContentArgumentAndRenderStatic.php, src/View/AbstractTemplateView.php, src/ViewHelpers/Cache/DisableViewHelper.php, src/ViewHelpers/Cache/StaticViewHelper.php, src/ViewHelpers/CommentViewHelper.php, src/ViewHelpers/CountViewHelper.php, src/ViewHelpers/ForViewHelper.php, src/ViewHelpers/SectionViewHelper.php, src/ViewHelpers/VariableViewHelper.php, tests/Unit/Core/Cache/StandardCacheWarmerTest.php, tests/Unit/Core/ViewHelper/ViewHelperInvokerTest.php, tests/Unit/ViewHelpers/Cache/WarmupViewHelperTest.php, tests/Unit/ViewHelpers/DebugViewHelperTest.php
Also fixes a single missing doc-comment. Zero active code touched.
=> [TASK] Clean up class imports

src/View/TemplatePaths.php, tests/Unit/View/TemplatePathsTest.php
Support also sources from http://, ssh2://, file:// and custom stream wrapppers.
Fixes #361
=> [BUGFIX] Support any protocol and wrapper as template source

src/ViewHelpers/ForViewHelper.php, tests/Unit/ViewHelpers/ForViewHelperTest.php
=> [BUGFIX] Fix numeric key array reversing in f:for

src/View/TemplatePaths.php
Allowing multiple TemplatePaths objects (and thus TemplateViews)
to be used in parallel.
TODO: Add tests?
See also: https://review.typo3.org/#/c/54416/
=> [BUGFIX] TemplatePaths: Use a non-static cache

tests/Functional/Cases/Rendering/NestedFluidTemplatesWithLayoutTest.php, tests/Functional/Fixtures/Layouts/Layout.html, tests/Functional/Fixtures/LayoutsOverride/Layouts/Layout.html
This is a follupup for https://github.com/TYPO3/Fluid/pull/342
=> [TASK] Add a test to test nested templates layout cache problems

src/Core/Rendering/AbstractRenderable.php, src/Core/Rendering/RenderableClosure.php, src/Core/Rendering/RenderableInterface.php, src/Core/Rendering/StandardRenderable.php, src/Core/ViewHelper/ViewHelperVariableContainer.php, tests/Unit/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessorTest.php, tests/Unit/Core/Rendering/RenderingContextFixture.php, tests/Unit/Core/ViewHelper/Fixtures/RenderMethodFreeDefaultRenderStaticViewHelper.php, tests/Unit/Core/ViewHelper/Traits/CompileWithContentArgumentAndRenderStaticTest.php, tests/Unit/View/LegacyTemplatePathsTest.php, tests/Unit/ViewHelpers/CountViewHelperTest.php, tests/Unit/ViewHelpers/Fixtures/ParsedTemplateImplementationFixture.php, tests/Unit/ViewHelpers/SectionViewHelperTest.php
* Removes some unused imports
* Adds a few missing annotations
* Sorts imports
=> [TASK] Random code cleanups

examples/Resources/Private/Templates/Default/Nested/Default.html, src/View/TemplatePaths.php, tests/Unit/View/TemplatePathsTest.php
Fixes resolving of files in subfolders, among other
things making all resolveAvailableXyz methods
return all files in subfolders.
=> [BUGFIX] Make template file resolving recursive

src/Core/Parser/SyntaxTree/AbstractNode.php
This patch slightly refactors the way evaluateChildNodes
behaves, allowing the return value from getChildNodes
to be any type of iterable type/object.
There are currently no use cases in existence that would
change a node to return non-arrays from getChildNodes
but in order to support this in the future we can refactor
now without ill effects.
(I am in fact working on something that would require it)
=> [TASK] Refactor child node evaluation to iterable

.travis.yml, composer.json
* composer remove satooshi/php-coveralls
* composer require --dev php-coveralls/php-coveralls
* adapt .travis.yml
=> [TASK] Use current php-coverall version

composer.json
=> [TASK] Use lowercase mikey179/vfsStream in composer.json

composer.json
Raises the required PHP version to 7.2 or above.
=> [FEATURE] Demand PHP 7.2 minimum

tests/Unit/Core/Parser/TemplateParserTest.php
… method as preparation for further changes
=> [TASK] Add testcases to ensure functionality of TemplateParsers recursiveArrayHandler

src/Core/Parser/TemplateParser.php
To solve #449, we can change the order of result handling. Tests were added, which test for the existing behavior.
=> [BUGFIX] Build subarray if found in regex, regardless of other matches

.travis.yml, bin/fluid, src/Core/Variables/JSONVariableProvider.php, src/View/TemplatePaths.php, tests/Unit/Core/Parser/SyntaxTree/AtomNodeTest.php, tests/Unit/Core/Parser/SyntaxTree/EntryNodeTest.php, tests/Unit/Core/Parser/SyntaxTree/ReferenceNodeTest.php, tests/Unit/ViewHelpers/VariableViewHelperTest.php
Enable 7.4 in matrix and convert incompatible syntax occurrences.
=> [TASK] Enable testing on PHP 7.4

.gitattributes
Do not export files/directories which are not necessary for production usage.
Fixes #402
=> [TASK] Clean up dist archive

.github/workflows/build.yml
Use coveralls parallel to generate coverage per PHP version.
=> [TASK] Coveralls per tested PHP version

.github/workflows/build.yml, .gitignore, phpunit.xml.dist
* colors by default (why not?)
* no useless cache file
* convert warnings and notices to exceptions
=> [TASK] More strict phpunit settings

MAINTAINERS
MAINTAINERS is not maintained. Let's remove that
file, active maintainer roles are reflected by
github.
=> [TASK] Remove outdated MAINTAINERS file

.github/workflows/build.yml, .gitignore
A test coverage and a numerolog related left over.
=> [TASK] Remove some test related artifacts

composer.json
We don't need this anymore.
composer rem --dev mikey179/vfsstream
=> [TASK] Remove mikey179/vfsstream dev dependency

phpunit.xml.dist
Fail more often, report more errors and
reference phpunit 9.5 xsi.
=> [TASK] More strict phpunit.xml.dist

.editorconfig, .gitattributes, .github/workflows/build.yml, composer.json, phpstan-baseline.neon, phpstan.neon.dist
Have a default phpstan config with PHP 7.2.
Level 4 seems to be suitable for now. Add a
baseline file and enable phpstan in CI.
With PHP 7.2:
composer req --dev phpstan/phpstan
vendor/bin/phpstan --generate-baseline
=> [TASK] Add phpstan level 4, add baseline, add CI

composer.json, phpstan-baseline.neon, phpstan.neon.dist
Using PHP 7.2:
composer req --dev phpstan/phpstan-phpunit
./vendor/bin/phpstan --generate-baseline
=> [TASK] Add phpstan/phpstan-phpunit and regenerate baseline

composer.json
> composer req --dev phpunit/phpunit:"^8.5.33 || ^9.5.28 || ^10.0.16"
=> [TASK] Raise --dev phpunit 10 and allow bugfix releases

src/Core/Parser/ParsingState.php, src/View/AbstractTemplateView.php
=> [TASK] Avoid array_push on array writing

src/Core/Parser/BooleanParser.php, src/Core/Parser/SyntaxTree/BooleanNode.php, src/Core/Parser/SyntaxTree/Expression/CastingExpressionNode.php, src/ViewHelpers/CycleViewHelper.php
=> [TASK] Simplify some instanceof checks

phpstan-baseline.neon, src/Core/Parser/SyntaxTree/Expression/TernaryExpressionNode.php, src/Core/Rendering/RenderingContext.php, src/View/TemplatePaths.php
=> [TASK] Fix some wrong return type annotations

src/Core/Parser/BooleanParser.php, src/Core/Parser/SyntaxTree/Expression/TernaryExpressionNode.php
=> [TASK] Strict comparison on string compares

src/Core/Variables/StandardVariableProvider.php
=> [TASK] Minor StandardVariableProvider improvement

src/Core/Compiler/NodeConverter.php
This makes the code a bit better readable.
=> [TASK] Inline a static string in NodeConverter

src/Core/Variables/StandardVariableProvider.php
Merge detectAccessor() and extractWithAccessor()
into one method.
=> [TASK] Simplify StandardVariableProvider->getByPath()

src/Core/Variables/StandardVariableProvider.php
Inlining excract() into getByPath() and optimizing a bit further improves performance of this heavy
used method. Avoiding call_user_func_array() and
using dynamic method calls directly also improves
it a bit.
=> [TASK] Inline StandardVariableProvider->extract()

tests/Unit/Core/Variables/StandardVariableProviderTest.php
=> [TASK] Verify reference to int key works

tests/Unit/Core/ViewHelper/ViewHelperResolverTest.php
ViewHelperResolver is the test subject.
=> [TASK] Get naming right in ViewHelperResolverTest

src/Core/Compiler/NodeConverter.php
NodeConverter->convertViewHelperNode() is
optimized to render more dense array definitions
of the argument array.
=> [TASK] Simplify arguments in compiled templates

tests/Functional/ViewHelpers/IfThenElseViewHelperTest.php
More if-then-elseif-else cases.
=> [TASK] Add more if VH test cases

src/ViewHelpers/ForViewHelper.php
* Mention 'total' as key of iteration information
=> [DOCS] Sharpen docs of f:for viewhelper

src/Core/Variables/StandardVariableProvider.php
See https://github.com/TYPO3/Fluid/pull/730
=> Drop documentation of removed variable provider parameter

composer.json, examples/src/CustomVariableProvider.php, src/Core/Cache/StandardCacheWarmer.php, src/Core/Parser/TemplateParser.php
> composer req --dev friendsofphp/php-cs-fixer:^3.37.1
> vendor/bin/php-cs-fixer fix -v
=> [TASK] Bump friendsofphp/php-cs-fixer:^3.37.1

src/ViewHelpers/Format/TrimViewHelper.php, tests/Functional/ViewHelpers/Format/TrimViewHelperTest.php
TrimViewHelper doesn't have any dependencies to TYPO3, so it can be moved to Fluid Standalone.
=> [FEATURE] TrimViewHelper for StandaloneFluid

tests/Functional/ViewHelpers/VariableViewHelperTest.php
=> [TASK] Add test case for f:variable

src/ViewHelpers/Format/CaseViewHelper.php, tests/Functional/ViewHelpers/Format/CaseViewHelperTest.php
CaseViewHelper doesn't have any dependencies to TYPO3, so it can be moved to Fluid Standalone.
=> [FEATURE] CaseViewHelper for StandaloneFluid

.github/workflows/build.yml, .php-cs-fixer.dist.php
Update ruleset, show no progress on CI,
activate parallel runners.
=> [TASK] Avoid deprecated php-cs-fixer rules

Documentation/Changelog/2.x.rst, Documentation/Changelog/Index.rst, Documentation/Index.rst, src/Core/Compiler/StopCompilingChildrenException.php, src/Core/Compiler/TemplateCompiler.php, src/Core/Compiler/ViewHelperCompiler.php, src/Core/Parser/Patterns.php, src/Core/Parser/SyntaxTree/Expression/ParseTimeEvaluatedExpressionNodeInterface.php, src/Core/Parser/SyntaxTree/ObjectAccessorNode.php, src/Core/Variables/StandardVariableProvider.php, src/Core/Variables/VariableExtractor.php, src/Core/ViewHelper/AbstractConditionViewHelper.php, src/Core/ViewHelper/AbstractTagBasedViewHelper.php, src/Core/ViewHelper/AbstractViewHelper.php, src/Core/ViewHelper/Traits/ParserRuntimeOnly.php
List deprecations and code removal targets.
=> [TASK] Add v2 Changelog

Documentation/Changelog/2.x.rst, Documentation/Changelog/Index.rst, Documentation/Index.rst, src/Core/Compiler/StopCompilingChildrenException.php, src/Core/Compiler/TemplateCompiler.php, src/Core/Compiler/ViewHelperCompiler.php, src/Core/Parser/Patterns.php, src/Core/Parser/SyntaxTree/Expression/ParseTimeEvaluatedExpressionNodeInterface.php, src/Core/Parser/SyntaxTree/ObjectAccessorNode.php, src/Core/Variables/StandardVariableProvider.php, src/Core/Variables/VariableExtractor.php, src/Core/ViewHelper/AbstractConditionViewHelper.php, src/Core/ViewHelper/AbstractTagBasedViewHelper.php, src/Core/ViewHelper/AbstractViewHelper.php, src/Core/ViewHelper/Traits/ParserRuntimeOnly.php
List deprecations and code removal targets.
=> [TASK] Add v2 Changelog (#912)

src/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php, src/Core/ViewHelper/Traits/CompileWithContentArgumentAndRenderStatic.php, tests/Functional/ViewHelpers/IfThenElseViewHelperTest.php, tests/Unit/Core/Parser/BooleanParserTest.php
This helps some IDEs with parsing phpdocs correctly.
=> [TASK] Improve phpdoc formatting

src/Core/ViewHelper/AbstractConditionViewHelper.php
Since `renderStatic()` is now deprecated, `AbstractConditionViewHelper` is
adjusted accordingly. Template compilation steps are left as-is except for the
ViewHelper call itself, which now also uses `ViewHelperInvoker`. The
functionality of `renderStatic()` is now integrated into the separate render
methods. Also, special handling for the internal closure arguments is added
to the class.
=> [TASK] Remove renderStatic() from condition ViewHelpers

Documentation/Changelog/2.x.rst, src/View/TemplatePaths.php
=> [TASK] Add deprecation hints to TemplatePaths

composer.json
> composer req --dev phpunit/phpunit:^11.4.3
=> [TASK] Raise phpunit/phpunit:^11.4.3

Documentation/Syntax/Variables.rst
=> [DOCS] Improve object property access documentation

Documentation/Syntax/Comments.rst, Documentation/Syntax/ConditionsBooleans.rst, Documentation/Syntax/Escaping.rst, Documentation/Syntax/Expressions.rst, Documentation/Syntax/Variables.rst, Documentation/Syntax/ViewHelpers.rst, Documentation/Usage/Structure.rst, Documentation/ViewHelpers/SchemaFiles.rst
I hope its fine to make this kind of pull requests :)  
Just small things I noticed while reading the docs.
=> [DOCS] Fix typos, grammar and improve wording

composer.json
Used command(s):
```shell
composer config \
extra."branch-alias"."dev-main" "4.x-dev"
```
=> [TASK] Add composer branch alias for `dev-main`

src/Core/ViewHelper/AbstractViewHelper.php, src/Core/ViewHelper/ViewHelperInvoker.php
This could be slightly breaking, so we better wait for next major.
=> [TASK] Add todo to move validation code

tests/Functional/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessorTest.php
Example taken from TYPO3 Core test suite
=> [TASK] Add test case for diverging namespace usage

src/Core/Parser/TemplateParser.php
Currently, the `ParsingState` only gets its (optional) identifier after
the whole parsing process, even though it's already available at
the beginning. With this change, the identifier is set early (and
to an empty string as fallback).
This allows us to provide more context in deprecation messages
which will be added in follow-up patches.
=> [TASK] Provide identifier early to ParsingState

tests/Functional/Core/Rendering/RecursiveRenderingTest.php, tests/Functional/Fixtures/ViewHelpers/TagBasedTestViewHelper.php
=> [TASK] Add test case for tag-based VH in recursive section

Documentation/ViewHelpers/Fluid/Argument.rst
=> [DOCS] Re-enable reference to TYPO3 for f:argument

src/ViewHelpers/ArgumentViewHelper.php, tests/Functional/Fixtures/Layouts/LayoutWithArgumentDefinitions.html, tests/Functional/Fixtures/Partials/PartialWithArgumentDefinitions.html, tests/Functional/Fixtures/Templates/TemplateWithArgumentDefinitions.html, tests/Functional/ViewHelpers/ArgumentViewHelperTest.php
=> [TASK] Treat f:argument with default value as optional

composer.json, patches/patches.json, patches/react-promise-switch-case-semicolon-syntax.diff
Dev dependency.
This has been fixed upstream but not released, yet.
PHP:
https://github.com/php/php-src/commit/5f8d648af6ef4e29a3c7f2b2029d08466c12bc6f
React/promise:
https://github.com/reactphp/promise/commit/d3998c8a5d3cff0b39b2f332da550e996f35b947
=> [TASK] Apply react/promise patch to fix PHP 8.5 deprecation

src/Core/ViewHelper/AbstractTagBasedViewHelper.php
This is a clean-up after #1173.
=> [TASK] Remove obsolete $tagAttributes property
