TYPO3/Fluid

src/Core/Parser/SyntaxTree/BooleanNode.php
tests/Unit/Core/Parser/SyntaxTree/BooleanNodeTest.php

Relaxing the required input type for the constructor of
BooleanNode allows simple values to be passed, avoiding
the need for additional wrapping of plain types in Nodes
before being able to evaluate them as booleans.

[FEATURE] BooleanNode accepts non-Nodes in constructor

---

src/Core/ViewHelper/AbstractConditionViewHelper.php
tests/Unit/Core/ViewHelper/AbstractViewHelperTest.php

This removes the render() method from the AbstractViewHelper
class in order to prevent PHP errors when a subclass overrides the
method with a different signature (i.e. including parameters).
Note:
This was lost when re-applying https://github.com/NamelessCoder/TYPO3.Fluid/pull/18
to this repository.
This change also adds the ``AbstractViewHelperTest`` changes that got
lost.

[BUGFIX] Remove ``render()`` method from ``AbstractConditionViewHelper``

---

src/View/TemplatePaths.php

Example error message after change:
"Tried resolving a template file for controller action "MyController->myAction" in format ".html", but none of the paths contained the expected template file (Mycontroller/MyAction.html). The following paths were checked: /foo, /bar"

[TASK] Improve error message when unable to resolve template

---

src/Core/ViewHelper/AbstractConditionViewHelper.php

Removing the type hint keeps this base class compatible with current condition ViewHelpers in CMS which is a pre-requisite before releasing Fluid in version 1.0.0.

[TASK] Remove type hint for evaluateCondition method

---

src/View/AbstractTemplateView.php

Exceptions converted by the Parser into pretty errors with template line, char and snippet are now thrown as the same type of Exception that was originally caught. This allows external users to check by class which type of Exception was thrown without having to read/parse the error message.

[TASK] Throw same Exception type as caught in Parser

---

src/Core/Parser/Patterns.php
src/Core/Parser/TemplateParser.php
src/Core/Parser/UnknownNamespaceException.php
src/Core/ViewHelper/ViewHelperResolver.php
tests/Functional/ExamplesTest.php
tests/Unit/Core/Parser/TemplateParserTest.php

This commit adds back the "old" namespace syntax:
{namespace foo=Foo\Bar\ViewHelpers}
and it checks if you're using any viewHelpers in namespaces you didn't
register to reduce common problems where you move stuff in templates,
spelling errors and similar which result in not-rendered viewHelpers
or even exceptions because as a side effect arguments are cast to
string, but fail.
fixes  #8

[FEATURE] Support Legacy Namespaces and throw Exception on unknown namespace use

---

src/ViewHelpers/RenderViewHelper.php
tests/Unit/ViewHelpers/RenderViewHelperTest.php

Allows a completely new approach to structuring Fluid template rendering, allowing partials and sections to be used as "wrappers" for an arbitrary piece of template code. Consider the following example:
```xml
<f:section name="MyWrap">
<div>
{contentVariable -> f:format.raw()}
</div>
</f:section>
<f:render section="MyWrap" contentAs="contentVariable">
This content will be wrapped. Any Fluid code can go here.
</f:render>
```
The result is that the tag content of `f:render` is assigned as the template variable `{contentVariable}` which can then be used in the template code that is in the section/partial. It's the same as passing a big chunk of Fluid to the `arguments` array as a variable there, and using it the same way - but it is a lot easier on the syntax.
The new structure approach is …

[FEATURE] Passing of tag content from f:render to partial/section

---

src/Core/Parser/SyntaxTree/BooleanNode.php
src/Core/Parser/TemplateParser.php
tests/Functional/Cases/Conditions/BasicConditionsTest.php
tests/Functional/Cases/Conditions/VariableConditionsTest.php
tests/Unit/Core/Parser/SyntaxTree/BooleanNodeTest.php

This change:
* Uses PHP math workaround ($value + 0) to ensure numeric-ness of unqouted values.
* Changes the analysis of left/right sides to use is_scalar as basic decision; allowing scalar values to be compared readily with null and resource pointers.
* Changes test expectations that were previously off PHP standard.
* Adds new test cases for the PHP standard comparison expectations.
Close: #7

[BUGFIX] Match PHP behavior in deciding comparability of variables

---

src/Core/ViewHelper/ViewHelperResolver.php
tests/Unit/Core/ViewHelper/ViewHelperResolverTest.php

Deviation: unresolvable ViewHelpers had been changed to throw ViewHelper Exception, not Parser Exception. Changed this and unit test expectations.
Close: #11

[TASK] All parse-time errors are reported as ParserException

---

src/Core/Parser/SyntaxTree/BooleanNode.php
tests/Functional/Cases/Conditions/BasicConditionsTest.php
tests/Functional/Cases/Conditions/VariableConditionsTest.php

Correctly preserves whitespace in quoted strings.
Close: #6

[BUGFIX] Correct expected string unquoting behavior

---

src/Core/Parser/TemplateParser.php

Prevents an issue where internal namespace extraction now fails when a namespace is not registered or would be registered only by a template pre-processor. Because template pre-processors were asked *after* the internal method, their registered namespaces were never recognised. TemplateParser would instead throw an error about an unknown namespace.

[BUGFIX] Make sure PreProcessors come before internal namespace extraction

---

src/Core/Parser/SyntaxTree/ViewHelperNode.php
src/Core/Parser/TemplateParser.php
src/Core/ViewHelper/AbstractViewHelper.php
src/Core/ViewHelper/ViewHelperInterface.php
src/View/AbstractTemplateView.php
src/View/TemplatePaths.php
src/ViewHelpers/ForViewHelper.php
tests/Unit/Core/Parser/SyntaxTree/ViewHelperNodeTest.php
tests/Unit/Core/Parser/TemplateParserTest.php
tests/Unit/Core/ViewHelper/AbstractTagBasedViewHelperTest.php
tests/Unit/Core/ViewHelper/AbstractViewHelperTest.php

This change:
* Improves handling of errors with template examples
* Moves such template code errors to TemplateParser entirely
* Implements validation of required arguments (by presence alone) in ViewHelperNode constructor, causing it to fail on bad syntax
* Introduces a secondary validateAdditionalArguments method that allows validating the presences of additional, unregistered arguments at parse time
* Cleans up the way ViewHelperNode is handled in TemplateParser
* Makes sure the TemplatePaths checks for global (not controller specific) templates after controller specific ones

[TASK] Improve TemplateParser logic

---

src/ViewHelpers/Format/HtmlspecialcharsViewHelper.php
tests/Unit/ViewHelpers/Format/HtmlspecialcharsViewHelperTest.php

Ensures escaping of single quotes. See: https://forge.typo3.org/issues/59540

[TASK] Use ENT_QUOTES rather than ENT_COMPAT

---

src/Core/Compiler/NodeConverter.php
tests/Unit/Core/Compiler/NodeConverterTest.php

This wraps array access with an isset if to prevent warnings because of non existing keys in compiled templates

[BUGFIX] Prevent warning with empty arrays

---

src/ViewHelpers/DebugViewHelper.php
tests/Unit/ViewHelpers/DebugViewHelperTest.php

Rather than depending on output buffering, var_export with "return" parameter can be used safely on all supported PHP versions. Prevents issues with debug instructions being output when var_dump is used on PHP7 with debug enabled.

[TASK] Use var_export for basic DebugViewHelper

---

examples/Resources/Private/Singles/Namespaces.html
src/Core/Parser/Patterns.php
src/Core/Parser/TemplateParser.php
src/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php
tests/Functional/ExamplesTest.php
tests/Unit/Core/Parser/TemplateParserPatternTest.php
tests/Unit/Core/Parser/TemplateParserTest.php

his commit adds an NamespaceDetectionTemplateProcessor
that takes care of 3 things:
- replace cdata sections with empty lines (including nested cdata)
- register/ignore namespaces through xmlns and shorthand syntax
- report any unregistered/unignored namespaces through exception

[TASK] Add NamespaceDetectionTemplateProcessor

---

src/Core/ViewHelper/ViewHelperResolver.php
tests/Unit/Core/ViewHelper/ViewHelperResolverTest.php

Allows:
```php
// given class My\Package\ViewHelpers\RenderViewHelper exists and REPLACES f:render
$view->getViewHelperResolver()->extendNamespace('f', 'My\\Package\\ViewHelpers');
$class = $view->getViewHelperResolver()->resolveViewHelperClassName('f', 'render');
// "My\\Package\\ViewHelpers\\RenderViewHelper"
// given class My\Package\OtherViewHelper exists, gets ADDED to "f:" namespace
$class = $view->getViewHelperResolver()->resolveViewHelperClassName('f', 'other');
// "My\\Package\\ViewHelpers\\OtherViewHelper"
```
And in templates allows all ViewHelpers from "My\Package\ViewHelpers" to be used as part of "f:".
The feature is achieved through allowing each registered PHP namespace string to become an array and the resolve class method to support both strings and arrays, walking the …

[FEATURE] Allow namespaces to be extended

---

src/Core/Compiler/NodeConverter.php
src/Core/Parser/SyntaxTree/EscapingNode.php

Rather than use the f:format.htmlspecialchars ViewHelper via a ViewHelperNode, involving resolving and everything else implied by rendering a ViewHelper, a new node type - EscapingNode - is implemented. The node is added in the same way as the old escaping would do, but evaluates as and compiles to a single `htmlspecialchars` function call.

[FEATURE] Replace escaping by f:format.htmlspecialchars with EscapingNode

---

src/Core/Variables/ChainedVariableProvider.php
tests/Unit/Core/Variables/ChainedVariableProviderTest.php

Allows any number of VariableProviders to be chained in another VariableProvider, making the container consult each chained VariableProvider until a value is found. Different types of VariableProviders can be combined, e.g. a standard array-based instance combined with a VariableProvider that reads a JSON file.

[FEATURE] Chained VariableProvider

---

src/Core/Compiler/TemplateCompiler.php
src/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php
src/Core/ViewHelper/ViewHelperResolver.php
tests/Unit/Core/ViewHelper/ViewHelperResolverTest.php

This change affects ViewHelperResolver and:
* Renames `registerNamespace` to `addNamespace` since it now truly does add, also when namespace exists.
* Removes the thrown exception "Namespace is already registered and should not be re-registered".
* Changes behavior to extend namespace when called multiple times with different PHP namespaces.
* Documents many public methods that were previously low on docs.
* Adds a shorthand addNamespaces method on ViewHelperResolver so that compiled templates can add all extracted namespaces with a single method call and avoid compiling a loop.

[TASK] Streamline names and behaviors in namespace registration

---

examples/Resources/Private/Singles/Namespaces.html
src/Core/Parser/TemplateParser.php
src/Core/ViewHelper/ViewHelperResolver.php
tests/Unit/Core/ViewHelper/ViewHelperResolverTest.php

Before this change, ignoring a namespace with `{namespace ignoredname}` was not respected due to casting NULL to an array. And support restored for namespaces added as PHP namespace in xmlns notation, including without the "ViewHelpers" suffix which will now get appended automatically.
This change also removes a redundant argument on ViewHelperResolver and adds a specific method to check if namespace is ignored.

[BUGFIX] Fixes for namespace resolving

---

src/View/TemplatePaths.php
tests/Unit/View/TemplatePathsTest.php

This change fixes an issue where if one of multiple template root paths contained a no-action template (named by controllername sitting directly in template root path) would take priority over an action template, if the no-action template sat in a template file which had priority over the other but the priority path did not contain an action template.
Example:
Path A contains MyController.html
Path B contains MyController/MyAction.html
If Path A was checked before Path B then MyController.html would be returned where the expected return is MyController/MyAction.html.
Also fixes a side issue exposed by the bug fix, where stream wrappers would not be rewound before being read, causing empty template source on subsequent reads.

[BUGFIX] No-action template must not have priority over action template

---

src/Core/Compiler/TemplateCompiler.php

This change makes sure that when caching is disabled, the template compiler will flush the cache for any existing entries (allowing for example dynamically flushing cache by custom TTL from a ViewHelper's compile method). Until this change, a previously cached template could never be excluded from compiling, which resulted in bad behavior when combined with the fact that the template caching could possibly already have begun at the time when a ViewHelper disables the compiler.

[BUGFIX] Correct handling of disabled compiler in relation to cache

---

src/Core/Compiler/NodeConverter.php
src/Core/Parser/SyntaxTree/Expression/AbstractExpressionNode.php
src/Core/Parser/SyntaxTree/Expression/ExpressionNodeInterface.php

This allows each node to compile itself differently as optimised PHP calls. A default implementation is provided which utilises the existing `evaluateExpression()` method to evaluate the node. The change is not breaking.

[TASK] Refactor ExpressionNode and interface to move compiling to each node

---

src/Core/Parser/SyntaxTree/BooleanNode.php

Allows the context gathering to function in compiled templates where parts may have already been evaluated before being passed to the node.

[BUGFIX] Consider text parts when BooleanNode gathers context

---

src/Core/ViewHelper/ViewHelperResolver.php
tests/Unit/Core/ViewHelper/ViewHelperResolverTest.php

If a user was careless and added a ViewHelper namespace ending in a backslash, ViewHelper classes would fail to resolve but on some systems the class file would still load, causing a seemingly unrelated "Cannot redeclare class" error.
Trimming the namespace suffix before the lookup avoids this situation.

[TASK] Convenience trimming backslash suffix from namespace

---

src/Core/Compiler/StopCompilingException.php
src/Core/Compiler/TemplateCompiler.php
src/Core/Parser/SyntaxTree/ViewHelperNode.php
src/Core/Parser/TemplateParser.php
src/Core/ViewHelper/ViewHelperInvoker.php
tests/Unit/Core/Compiler/TemplateCompilerTest.php
tests/Unit/Core/Parser/SyntaxTree/ViewHelperNodeTest.php
tests/Unit/Core/ViewHelper/ViewHelperInvokerTest.php
tests/Unit/ViewHelpers/SwitchViewHelperTest.php

This change:
* Implements a StopCompilingException to allow earlier return during compiling when disabling compiler from a ViewHelper. Sets compilable state to FALSE in ParsingState.
* Implements L1 caching of ParsedTemplate (ParsingState) in TemplateParser; preventing re-parsing of uncompilable templates and storing already instantiated compiled templates.
* Refactors some argument validation to ViewHelperNode in order to prevent multiple executions (will execute once per node and not execute once compiled).
The change improves performance in two key areas:
* During template parsing and compiling performance is improved when rendering templates that use loops or multiple calls to render the same partial/section.
* During rendering of compiled templates performance is improved due to …

[TASK] Improve performance of rendering logic

---

src/View/TemplatePaths.php
tests/Unit/View/TemplatePathsTest.php

When passing template resource as source code string to TemplatePaths the resulting template identifier would be non-unique and would falsely report TRUE for cached status and retrieve an unexpected parsed template.
Giving the template a unique identifier also when operated in source code mode solves this issue.

[BUGFIX] Caching identifier colission when using template source

---

bin/fluid

If typo3fluid/fluid is installed as dependency the bin/fluid script fails with an error:
> PHP Fatal error:  Class 'TYPO3Fluid\Fluid\Core\Variables\StandardVariableProvider' not found in
> /var/www/vendor/typo3fluid/fluid/examples/include/class_customvariableprovider.php on line 19
Fix this by also looking for autoload.php in the vendor-dir this package is currently
installed to.

[BUGFIX] Support bin/fluid execution as dependency

---

src/Core/ViewHelper/AbstractConditionViewHelper.php

When rendering a template with a piece of template code like:
```xml
{f:if(condition: variable, then: 'yes', else: 'no')}
<f:if condition="{variable}" then="yes" else="no" />
```
Would never execute the "else" statement once the ViewHelper was compiled regardless of input arguments. Used with child nodes the compiled result works perfectly.
Problem is in renderStatic which does not consider "else" passed directly in arguments. The condition is extended to also consider this way of passing the argument.

[BUGFIX] Compiled condition never reaches "else" if passed as argument

---

src/ViewHelpers/SpacelessViewHelper.php

This change avoids using a possibly NULL value that should contain a rendering closure. Building the closure before using it avoids this problem.

[BUGFIX] Spaceless ViewHelper builds render children closure

---

src/Core/ViewHelper/ViewHelperResolver.php

In preparation for extending the ways in which ViewHelper resolving
can be performed, we implement an internal cache which can skip
the more expensive resolving steps and improve performance also
when rendering other templates/partials in the same View lifecycle.

[TASK] Implement internal cache of resolved ViewHelper classes

---

src/ViewHelpers/Format/PrintfViewHelper.php

To enable the rendering of the children the default value of the argument "value" must be NULL instead of FALSE.

[BUGFIX] Set default value for argument "value" to NULL

---

tests/Functional/ExamplesTest.php
tests/Unit/Core/Parser/Fixtures/TemplateParserTestFixture06-split.php
tests/Unit/Core/ViewHelper/AbstractConditionViewHelperTest.php

This patch ensures correct line endings for Unit Test when running on Windows systems (and checked out as Unix files).

[BUGFIX] Ensure correct line endings in Unit Tests on Windows systems

---

src/ViewHelpers/ForViewHelper.php
tests/Unit/ViewHelpers/ForViewHelperTest.php

By argument definition the default value for "key" in the ForViewHelper ist NULL instead of an empty string. The validation and the tests should care about that default value. Currently the key is set without any name in the $templateVariableContainer

[BUGFIX] Ensure initial value for key in ForViewHelper is used

---

src/Core/Variables/VariableExtractor.php
tests/Unit/Core/Variables/VariableExtractorTest.php

Accessing an object is bound to the existence of a method called
"exists()" which leads to an invalid array access on objects actually
implementing that method without the intention to be accessed as array.
Using the ArrayAccess interface using the method "offsetExists()"
offers a more specific approach on using an array accessor however.

[BUGFIX] Invalid array object access

---

src/Core/Compiler/TemplateCompiler.php
src/View/AbstractTemplateView.php
src/ViewHelpers/SectionViewHelper.php
tests/Unit/Core/Compiler/TemplateCompilerTest.php
tests/Unit/ViewHelpers/SectionViewHelperTest.php

To prevent errors with "reserved" variable names, use a timestamp prefix for sections.
Related: https://review.typo3.org/#/c/46447/2

[BUGFIX] Avoid reserved "sections" variable name

---

src/View/TemplatePaths.php
tests/Unit/View/TemplatePathsTest.php

When passing a template source (not file reference) the resulting compiled class name was potentially invalid due to using sha1() as prefix. Adding a `source_` prefix avoids the problem.

[BUGFIX] Avoid creating invalid class names for compiled template sources

---

src/View/TemplatePaths.php
tests/Unit/View/TemplatePathsTest.php

This patch ensures sanitized paths when using realpath(). Some
improvements for the tests are added as well.

[BUGFIX] Ensure sanitized paths on Windows

---

src/Core/Parser/SyntaxTree/ViewHelperNode.php
src/Core/ViewHelper/AbstractViewHelper.php
tests/Functional/BaseFunctionalTestCase.php
tests/Functional/Cases/Rendering/RecursiveSectionRenderingTest.php
tests/Functional/Fixtures/Templates/RecursiveSectionRendering.html

Fixes an issue where recursively calling a ViewHelper caused the RenderingContext reference to become incorrect after ViewHelper renders a nested instance of itself. Expressed for example by recursively rendering a section with a loop - after exiting the loop and returning to the parent section variables would have unexpected values because the RenderingContext was replaced.
Cloning (shallow copying) the ViewHelper instance before creating the render children closure solves this issue.

[BUGFIX] Shallow copy RenderingContext before each ViewHelper

---

src/ViewHelpers/CaseViewHelper.php
src/ViewHelpers/DefaultCaseViewHelper.php
src/ViewHelpers/SwitchViewHelper.php
tests/Functional/BaseFunctionalTestCase.php
tests/Functional/Cases/SwitchTest.php
tests/Unit/ViewHelpers/SwitchViewHelperTest.php

This change introduces a custom compile() method for SwitchViewHelper which creates a native PHP switch() statement using various closures for evaluating the case matching and rendering the matched case.

[TASK] Compiling of switch statement

---

src/Core/Parser/BooleanParser.php

Removes the string trimming method (TemplateParser->unquoteString is used) and what appears to be a method intended to be used from within the string trimming method. Neither had any existing usages either in Fluid itself or as API.

[TASK] Remove never-used methods on BooleanParser

---

src/Core/Parser/SyntaxTree/ViewHelperNode.php

Some third party ViewHelpers may depend on the presence of a rendering context while parsing - although it technically is an incorrect expectation to have the context available at this point, making it available allows third parties to access various secondary aspects of the rendering context.
Specifically, the lack of this parse-time rendering context setting affects Widgets used in TYPO3 CMS when the template is uncompilable.
Followup for https://github.com/TYPO3Fluid/Fluid/pull/77 which removed this line as it was evidently redundant. Line restored now along with a comment linking to this pull request.

[BUGFIX] Assign RenderingContext during parsing

---

src/Core/ViewHelper/AbstractConditionViewHelper.php
tests/Unit/Core/ViewHelper/AbstractConditionViewHelperTest.php

Removed code deals with static rendering but was called during non-static rendering. The code would never be reached - and the same evaluation is already being done correctly in the static rendering method.

[TASK] Remove never-reached code from AbstractConditionViewHelper

---

src/Core/Parser/SyntaxTree/EscapingNode.php
tests/Unit/Core/Parser/SyntaxTree/EscapingNodeTest.php

If view helpers are chained, already encoded HTML entities will
be encoded again and again. To circumvent that, the handing in
the escaping interceptor is adjusted to avoid double encoding.
Related: https://forge.typo3.org/issues/75133
Releases: master

[BUGFIX] Avoid double HTML encoding on chained view helpers

---

src/Core/Parser/SyntaxTree/EscapingNode.php
tests/Unit/Core/Parser/SyntaxTree/EscapingNodeTest.php

This reverts commit d2e36f5ff2a9d3101130c66302695f207e5d3a50.
With the previous change it is not possible anymore to enforce double
encoding. Thus, the behavior has to be changed using the class member
variables escapeChildren and escapeOutput instead (which has been
done for the view helpers of the core already).
Related: https://forge.typo3.org/issues/75133

Revert "[BUGFIX] Avoid double HTML encoding on chained view helpers"

---

src/Core/ViewHelper/AbstractViewHelper.php

We now disable children escaping in case output escaping is already on.
This is a saner default so that view helper creators very seldomly need to
think about setting any of the escaping behavior properties.

[TASK] Simplifiy encoding behavior

---

src/Core/Parser/TemplateParser.php

The node, which has been wrapped by the interceptor,
needs to be added back to the stack.

[BUGFIX] Fix interceptor call for self-closing view helpers

---

examples/Resources/Private/Layouts/Dynamic.html
examples/Resources/Private/Singles/DynamicLayout.html
examples/example_dynamiclayout.php
src/Core/Compiler/TemplateCompiler.php
src/Core/Parser/ParsingState.php
tests/Functional/ExamplesTest.php
tests/Unit/View/TemplatePathsTest.php

This enables use of any dynamic expressions, ViewHelpers
or variable references as part of or only value of the
"name" attribute of `f:layout` - see included example
`example_dynamiclayout.php`.
Marked as BUGFIX since this support was advertised
and intended to be included right from the start.
See also: https://forge.typo3.org/issues/70285
See also: https://forge.typo3.org/issues/76314

[BUGFIX] Support dynamic nodes in Layout name attribute

---

src/Core/Compiler/TemplateCompiler.php
src/ViewHelpers/SwitchViewHelper.php
tests/Functional/BaseFunctionalTestCase.php
tests/Functional/ExamplesTest.php
tests/Unit/ViewHelpers/SwitchViewHelperTest.php

In compiled templates using static layout names the layout name would not be resolved correctly, causing the template to fail. In addition, an assigned variable $self was lacking in getLayoutName - this variable would be required by closures potentially generated by compiling RootNodes as per https://github.com/TYPO3Fluid/Fluid/commit/1cc3600097b74420c3fc857977b0af6bfbeafed1.
In addition, Switch ViewHelper's compile method has been very slightly changed to use `call_user_func_array` in order to correctly pass arguments to the lambda function that gets called.

[BUGFIX] Fix layout resolving when name is static and cache is enabled

---

src/View/TemplatePaths.php

In getLayoutIdentifier we implemented an internal cache for resolved files - but the getLayoutIdentifier method would only ever be called once, making the cache redundant.

[TASK] Drop an internal cache in API method with single use

---

src/View/TemplatePaths.php

This change adds an internal ability to clean resolved filenames and identifiers by type of cache and uses this to flush only the necessary type from each of the set***Paths methods.
Also cleans up how flushing happens: now done for all types when fresh instances are created and done for specific types when individual template type paths are set.
Implements constants for the cache type names.

[TASK] Clean up resolved file caching

---

src/Core/Parser/SyntaxTree/ObjectAccessorNode.php

The method is refactored to clearly declare as class property the list of reserved variable names and their values. The switch is (although nicely performant) replaced by two if-clauses, which avoid calling ->getVariableProvider on RenderingContext if retrieving default constants.
See also: https://github.com/TYPO3Fluid/Fluid/issues/127

[TASK] Micro-optimisation in ObjectAccessorNode->evaluate

---

src/ViewHelpers/DebugViewHelper.php
tests/Unit/ViewHelpers/DebugViewHelperTest.php

This change adds the following capabilities to `f:debug`:
* Option to produce HTML output (off by default)
* Option to limit recursion levels (5 by default)
* Ability to render ArrayObject, Iterator as key/value pairs
* Ability to render recursively
* Ability to render stream metadata

[FEATURE] Improve the Debug ViewHelper's capabilities

---

examples/Resources/Private/Singles/Variables.html
examples/example_variables.php
src/Core/Parser/Patterns.php
tests/Functional/ExamplesTest.php

This change fixes an issue where a template variable named for example "123variable" would render correctly when referenced as `{123variable}` but if used in an array part like for example `<f:alias map="{newVar: 123variable}">` the variable would not be resolved. Instead, a numeric value of `123` would be cast by the parser. Loosening up the expression which required array part variable references to start with a letter solves the issue.
See also: https://forge.typo3.org/issues/76276

[BUGFIX] Detect/allow number-prefixed variables in array parts

---

src/View/TemplatePaths.php

Explicitly check for null when testing for the end of the paths
array when searching for file candidates. This fixes an issue with empty
strings as root path, which would immediately stop the iteration and
trigger an exception.
Resolves: #135

[BUGFIX] Explicitly check for end of array (#135)

---

src/View/TemplatePaths.php

Explicitly check for null when testing for the end of the paths
array when searching for file candidates. This fixes an issue with empty
strings as root path, which would immediately stop the iteration and
trigger an exception.
Resolves: #135

[BUGFIX] Prevent loop exit when reaching empty template path (#136)

---

src/ViewHelpers/OrViewHelper.php

When the OrViewHelper gets cached, the $argumentsX variable
gets filled with NULL and the ViewHelperInvoker tests this
with isset(). If this isset() returns false, the Invoker then
fills the argument with its default value. In this case an empty
string is filled and not NULL, like expected.
You can replicate this by using the OrViewHelper once without cache
and then with cache. The cached version will return an empty string
instead of the provided alternative.

[BUGFIX] Support cached OrViewHelper

---

src/Core/Parser/BooleanParser.php
src/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php
src/Core/Variables/VariableExtractor.php
src/Core/ViewHelper/ViewHelperResolver.php

`stristr` creates a copy of the string which is not required if we
just want to check if a string contains a string.
The case insensitive check is also not requird if we check for characters
that do not have an uppercase representation.

[TASK] Use strpos instead of stristr

---

src/Core/Parser/Patterns.php
tests/Functional/Cases/Parsing/WhitespaceToleranceTest.php

See included functional test for cases which before this
patch would cause the tag attribute(s) to not be caught
by the parser. Adjusting the regular expressions used to
detect ViewHelper tags, split on dynamic tags and split
ViewHelper argument names/values solves the issue.
Note: additional whitespace in the places documented
by the functional test is valid XML and thus valid Fluid.

[BUGFIX] Tolerate whitespace in tag attribute parsing

---

src/Core/Parser/Patterns.php

In earlier versions it was allowed to use lower and upper case letters for namespace identifier. Further upper case letters are still valid via your Pattern: $SCAN_PATTERN_TEMPLATE_VIEWHELPERTAG
So would be cool to see allowed upper case letters in namespace identifiers again in your code.
Stefan

Allow upper camel case letters as namespace identifier

---

src/View/TemplatePaths.php

This change adds public visibility to the method
getPartialPathAndFilename on TemplatePaths. The
method is useful to call in custom implementations
dealing with rendering of partial templates.
Ref: https://review.typo3.org/#/c/47678/13

[FEATURE] Make getPartialPathAndFilename public

---

doc/FLUID_CREATING_VIEWHELPERS.md
src/ViewHelpers/CountViewHelper.php
src/ViewHelpers/ForViewHelper.php
src/ViewHelpers/Format/CdataViewHelper.php
src/ViewHelpers/Format/HtmlspecialcharsViewHelper.php
src/ViewHelpers/Format/PrintfViewHelper.php
src/ViewHelpers/Format/RawViewHelper.php
src/ViewHelpers/OrViewHelper.php
src/ViewHelpers/RenderViewHelper.php
tests/Functional/Fixtures/ViewHelpers/AbstractEscapingViewHelper.php
tests/Unit/ViewHelpers/ElseViewHelperTest.php
tests/Unit/ViewHelpers/OrViewHelperTest.php
tests/Unit/ViewHelpers/RenderViewHelperTest.php

This change removes all arguments passed to
registerArgument when those passed values are
the same as the default values (FALSE for required,
NULL for default value).

[TASK] Remove superfluous default values in registerArgument

---

src/Core/Compiler/ViewHelperCompiler.php
src/Core/ViewHelper/AbstractViewHelper.php
src/Core/ViewHelper/Traits/CompileWithContentArgumentAndRenderStatic.php
src/Core/ViewHelper/Traits/CompileWithRenderStatic.php
src/ViewHelpers/AliasViewHelper.php
src/ViewHelpers/CommentViewHelper.php
src/ViewHelpers/CountViewHelper.php
src/ViewHelpers/DebugViewHelper.php
src/ViewHelpers/ForViewHelper.php
src/ViewHelpers/Format/CdataViewHelper.php
src/ViewHelpers/Format/PrintfViewHelper.php
src/ViewHelpers/Format/RawViewHelper.php
src/ViewHelpers/GroupedForViewHelper.php
src/ViewHelpers/OrViewHelper.php
src/ViewHelpers/SpacelessViewHelper.php
tests/Unit/Core/ViewHelper/ViewHelperInvokerTest.php
tests/Unit/ViewHelpers/CountViewHelperTest.php
tests/Unit/ViewHelpers/DebugViewHelperTest.php
tests/Unit/ViewHelpers/Format/CdataViewHelperTest.php
tests/Unit/ViewHelpers/Format/RawViewHelperTest.php
tests/Unit/ViewHelpers/OrViewHelperTest.php

This change adds a dedicated ViewHelperCompiler to cover frequent use cases in ViewHelpers:
* Compiling directly with static function call (to renderStatic - or other methods on other classes)
* Compiling with static function call and using one of the provided arguments as "content" or calling renderChildren if that argument is not passed.
Both use cases support calling a static method on *any* class - not just ViewHelpers, or on another ViewHelper - if that method conforms to the signature of the renderStatic method defined in ViewHelperInterface.
Both use cases are then implemented in ViewHelpers of Fluid where possible, which improves performance of the following ViewHelpers:
* f:format.cdata
* f:format.printf
* f:alias
* f:comment
* f:count
* f:for
* f:groupedFor
* f:or
* f:spaceless …

[FEATURE] Provide dedicated ViewHelperCompiler and Traits

---

src/Core/ViewHelper/AbstractViewHelper.php

Do not allow reset() nor current() to be called on
ArrayAccess (which does not support these
methods). Should not break, since:
* This only relates to newly added “type[]” notation
* ArrayAccess is mostly implemented by Iterators in
our main use cases (TYPO3 CMS, Flow)
Furthermore removes a redundant call to current(),
the value of which is already returned from reset().

[BUGFIX] Avoid reset() on possibly ArrayAccess

---

src/Core/Compiler/NodeConverter.php

Allows PHP to more efficiently convert the result
to a hash map which performs slightly better than
the large elseif block. No behaviour change.

[TASK] Convert a big elseif to a switch

---

src/Core/Variables/JSONVariableProvider.php

The JSONVariableProvider would continuously hammer
and produce warnings about JSON source being NULL.
Avoiding loading if source is NULL prevents this.

[BUGFIX] Prevent JSONVariableProvider from reading NULL

---

src/View/TemplatePaths.php
tests/Unit/View/TemplatePathsTest.php

Support was unintentionally removed by added call
to sanitizePath() - restored and added a unit test to
prevent future breaking in this way.

[BUGFIX] Restore support for php://stdin template reference

---

src/View/TemplatePaths.php

Prevents internally passing around a resolved layout
name containing a dot and file extension. The format
would eventually be converted to one using underscore
separated names but explicitly doing it early on will
prevent confusion when debugging the code.

[TASK] Prevent internal dotted layout name

---

src/Core/Parser/SyntaxTree/Expression/CastingExpressionNode.php
src/Core/Parser/SyntaxTree/Expression/ExpressionException.php
tests/Unit/Core/Parser/SyntaxTree/Expression/CastingExpressionNodeTest.php

New Exception type to throw from within ExpressionNode
implementations. Allows catching and handling this type
of error individually (for things like improved error
feedback from template rendering).
Implements new Exception type in CastingExpressionNode.

[FEATURE] Introduce expression specific Exception type

---

src/Core/Parser/TemplateParser.php

Makes $error->getPrevious() return the original error
when handling a Parser-specific error (which rewrites
the exception message to include template excerpts).

[TASK] Include original Exception in rewritten Parser Exception

---

src/Core/Compiler/AbstractCompiledTemplate.php
src/Core/Parser/ParsedTemplateInterface.php
src/Core/Parser/ParsingState.php
src/Core/Parser/TemplateParser.php
tests/Unit/Core/Compiler/AbstractCompiledTemplateTest.php
tests/Unit/Core/Parser/ParsingStateTest.php

This change introduces a new property on parsed
and compiled template objects which allow those
parsed/compiled templates to store their own
identifier (the name used for the compiled class).
Prerequisite of up-coming features improving cache
management in Fluid.

[FEATURE] Store identifier via ParsedTemplateInterface

---

src/View/TemplatePaths.php

This change allows resolveAvailableTemplateFiles on
TemplatePaths to be called with a controller name of
NULL, which causes Fluid to look for the action’s
template file in the templateRootPaths directly, no
controller sub-directory being checked.

[FEATURE] Allow controller-less resolving in templateRootPaths

---

src/View/AbstractTemplateView.php

This change allows the View class to return a fallback
rendering context, parsed template and rendering
type integer without a pre-parsed rendering stack.
The result is that it becomes possible to render in
sub-views based on an existing ParsedTemplate
including those coming from compiled templates.

[TASK] Allow rendering without stack through View

---

src/Core/Compiler/FailedCompilingState.php
tests/Unit/Core/Compiler/FailedCompilingStateTest.php

This change introduces a new type of ParsingState
(ParsedTemplateInterface implementation) which is to
be used when compiling fails.
Currently this new type is not implemented anywhere
but is planned for the coming cache warmup feature as
a way to provide better feedback about failed compiles.
The class includes properties to carry both a failure
description and suggestions to mitigate the problem;
the intention being that such solutions shall be possible
to suggest when throwing Exceptions from ViewHelpers.
In the long run it is the intention to use this parsing state
whenever compiling fails, thus allowing things like debug
inspections to report problems and potential solutions,
while preserving the original ParsingState as a production
alternative that doesn’t catch and report …

[FEATURE] Introduce FailedCompilingState

---

src/Core/Compiler/NodeConverter.php
src/Core/Compiler/StopCompilingChildrenException.php

This change adds a new type of Exception and handling
thereof. The new Exception can be thrown from within
ViewHelpers’ `compile()` method and causes the compiler
to skip compiling:
* Further child nodes down the stack from current node
* Argument values and closures
* Render children closures
Instead, the compiler replaces the entire compiled state
of the ViewHelper that threw the Exception, turning it into
a static string provided in the Exception.
Planned usage is the coming cache improvements which
include a new ViewHelper which uses this to create a
completely static value for the compiled template.

[FEATURE] Introduce StopCompilingChildrenException

---

bin/fluid
tests/Functional/CommandTest.php

Correct invalid references to class names and refactor
the main command entry method to correct class construction.

[BUGFIX] Fix CLI usage of class names

---

src/Core/Variables/VariableExtractor.php
tests/Unit/Core/Variables/VariableExtractorTest.php

Due to the precedence for ArrayAccess accessors a property only
accessible via getter method in an ArrayAccess object cannot be
retrieved via Fluid currently.
This change adjusts the precedence so that for objects the
ArrayAccess is used as fallback after checking getter methods
for the given propertyName.

[BUGFIX] Makes object properties accessible in ArrayAccess (#184)

---

examples/Resources/Private/Singles/Variables.html
src/Core/Compiler/ViewHelperCompiler.php
src/Core/ViewHelper/Traits/CompileWithContentArgumentAndRenderStatic.php
tests/Functional/ExamplesTest.php

This change fixes an issue where the mentioned compiling
method would produce invalid PHP syntax if the content
argument could not be resolved.
Furthermore, uses the protected property for content
argument name on the Trait for storing the resolved name.
Also adds examples and test cases that validate this
compiling method.
NB: Do not back-port to 1.0 branch!

[BUGFIX] Fix compiling for renderStatic with content argument

---

src/View/AbstractTemplateView.php

This reverts commit 81dbc0e5d72700a7797dfffface001a77d0d880b.
Close: #201

Revert "[TASK] Allow rendering without stack through View (#174)"

---

src/View/AbstractTemplateView.php

Identifiers are already cache in TemplatePaths which
is consulted directly from the View. One function call
replaces one condition - and decreases total LOC.

[TASK] Remove unnecessary View-level partial identifier cache

---

src/Core/Parser/Patterns.php
tests/Unit/Core/Parser/TemplateParserPatternTest.php

This fixes the accessing of variables with names (or keys) ending in
digits used in array expressions.
Specifically an expression like this: `foo: bar2` was previously wrongly
parsed to `foo: bar` and resulted in wrong variables being accessed.
This has been fixed while at the same time retaining existing behavior
for parsing raw numeric values.
Tests are added to prove the corrected behavior.
Fixes #190

[BUGFIX] Variable access ending in digits in array expressions (#190)

---

src/Core/Parser/Patterns.php

This changes only commentary to clarify the elements of the
`SPLIT_PATTERN_SHORTHANDSYNTAX_ARRAY_PARTS` regular expression.

[TASK] Update commentary for array parts regular expression

---

examples/Resources/Private/Singles/Variables.html
examples/example_variables.php
tests/Functional/ExamplesTest.php

Adds an example of the Fluid-equivalent of PHP $$variable to output
the other variable identified by the value of the given, named variable.
Close: #213

[DOC] Add variable access example of {{dynamicVariableName}}

---

examples/Resources/Private/Singles/Variables.html
src/ViewHelpers/Format/RawViewHelper.php
tests/Functional/ExamplesTest.php

Since https://github.com/TYPO3/Fluid/pull/113, `f:format.raw` needs
a corresponding ternary condition in compiled template code because
it overrides the `compile()` method inherited by the Trait.
Close: #209

[BUGFIX] Fix f:format.raw used with "value" argument

---

src/Core/ViewHelper/Traits/CompileWithContentArgumentAndRenderStatic.php
src/Core/ViewHelper/Traits/CompileWithRenderStatic.php

Fixes usage of `self::` in Traits for ViewHelpers. Allows
the renderStatic method to be inherited from parents.

[BUGFIX] Allow late static binding for renderStatic

---

src/Core/ViewHelper/Traits/CompileWithRenderStatic.php

Adds a contract to force the presence and signature of
the buildRenderChildrenClosure method on implementers
of CompileWithRenderStatic trait. And cleans up a
usage of call_user_func_array to call this method.

[TASK] Force renderChildrenClosure for CompileWithRenderStatic

---

src/Core/ViewHelper/Traits/CompileWithContentArgumentAndRenderStatic.php

To let the content argument trait work in compiled templates, yet
another fix is required which prepends the compiled initialisation
code with a custom closure that is either built on-the-fly or
reuses the existing render children closure if the content argument
was not set (=NULL) in the arguments array.

[BUGFIX] Make CompileWithContentArgumentAndRenderStatic compile closure

---

src/ViewHelpers/CycleViewHelper.php

The CycleViewHelper relied on it's own instance to iterate
through all possible cycle values, which didn't work
when the template was compiled because the calls were made
to separate instances of the ViewHelper.
This fix adjusts the CycleViewHelper to work with the
`ViewHelperVariableContainer` and a proper static rendering.

[BUGFIX] CycleViewHelper correctly cycles even compiled (#141)

---

src/ViewHelpers/CycleViewHelper.php

Saves a duplicated `render()` method - low priority.

[TASK] Implement CompileWithRenderChildren on CycleViewHelper

---

bin/fluid

The support added by this patch is fully described at
https://forge.typo3.org/issues/78665, but a short
summary would be that a new "bootstrap" argument is
added to the Fluid CLI command which when used,
includes that bootstrap file (and does nothing else).
Pending the linked changed in TYPO3 this allows Fluid
to operate on command line using every context and
setting configured in the site it is installed in.

[FEATURE] Allow command-line Fluid to include third-party bootstrap

---

examples/Resources/Private/Singles/Passthrough.html
examples/example_passthrough.php
src/Core/Parser/PassthroughSourceException.php
src/Core/Parser/TemplateProcessor/PassthroughSourceModifierTemplateProcessor.php
src/Core/Rendering/RenderingContext.php
src/View/AbstractTemplateView.php
tests/Functional/ExamplesTest.php

This adds a new pre-processor which handles a new type of
modifer in templates:
`{passthrough on}`
Which when enabled causes the template to be output instead
of parsed. This can then be used in partials, templates or layouts
to completely avoid parsing the template.
Useful if you have a piece of template code that collides with
Fluid's syntax - putting this code in a partial, enabling passthrough
and rendering that partial then outputs the source (and removes
the modifier itself).
Close: #219

[FEATURE] Template source passthrough pre-processor

---

examples/example_namespaceresolving.php

One example file contains code which has been moved
to the view_init.php file in examples include folder. The
code should be removed from the example file.

[TASK] Remove redundant example code

---

src/ViewHelpers/DebugViewHelper.php

Removes a line that would never be reached; previous
condition includes the same check and would trigger
instead of the removed code.

[TASK] Remove never-reached line in DebugViewHelper

---

bin/fluid

Must be rebased after https://github.com/TYPO3/Fluid/pull/240 is merged.

[FEATURE] Allow ClassName::methodName as bootstrap on CLI

---

src/Core/ViewHelper/AbstractViewHelper.php
tests/Unit/Core/ViewHelper/AbstractViewHelperTest.php

This prevents calling count() on argument to check validity
of first item. Cases where first value is "null" now means
that the value itself is valid (e.g. container is empty).

[BUGFIX] Avoid count() when checking types with "[]" notation

---

src/ViewHelpers/ForViewHelper.php
tests/Unit/ViewHelpers/Fixtures/CountableIterator.php
tests/Unit/ViewHelpers/ForViewHelperTest.php

Skip counting and other operations for iteration data when
the "iteration" argument is not set. Counting for example
QueryResult can be rather expensive so avoiding it whenever
possible makes good sense.
Also switches some `!== null` checks in favor of `isset()`,
which is done for consistency and to avoid potential e_notice.
Close: #243

[BUGFIX] Avoid iteration data in f:for without "iteration" argument

---

src/Core/Parser/SyntaxTree/Expression/MathExpressionNode.php

Adjust the regular expression to allow camel case variable names.

[BUGFIX] MathExpression not working with camel case variables

---

src/ViewHelpers/VariableViewHelper.php
tests/Unit/ViewHelpers/VariableViewHelperTest.php

New ViewHelper `f:variable` with arguments "name"
and "value", assigns a variable in the VariableProvider
using the `add()` method and does not remove the
variable again afterwards.
Usages:
{f:variable(name: 'myvariable', value: 'some value')}
<f:variable name="myvariable">some value</f:variable>
{oldvariable -> f:format.htmlspecialchars() -> f:variable(name: 'newvariable')}
<f:variable name="myvariable"><f:format.htmlspecialchars>{oldvariable}</f:format.htmlspecialchars></f:variable>

[FEATURE] Add variable assigning ViewHelper

---

src/Core/Compiler/TemplateCompiler.php
tests/Unit/Core/Compiler/TemplateCompilerTest.php

A previous refactoring changed isDisabled() on
TemplateCompiler, causing the condition which
would normally flush the cache to remove the
current template, if the template is uncompilable
(read: was compiled, then became uncompilable)

[BUGFIX] Cache did not flush when compiler disabled

---

src/Core/Compiler/TemplateCompiler.php
src/View/AbstractTemplateView.php

Refactors AbstractTemplateView slightly so that
the parsed template reading code can be called
from both render() and renderSection(), causing
the template to be loaded correctly.
Without this patch it is not possible to call
renderSection() via the View's API without getting
an error that no parsed template exists.
Also adds a public method on TemplateCompiler
to reset the current processing state.

[BUGFIX] Allow renderSection() to be called directly

---

src/Core/Parser/SyntaxTree/ViewHelperNode.php
tests/Unit/Core/Parser/SyntaxTree/ViewHelperNodeTest.php

Currently only the argument type „boolean“ got converted into the proper BooleanNode, causing arguments defined as „bool“ to be passed as TextNodes instead of BooleanNode.
closes #253

[BUGFIX] Convert bool arguments into BooleanNodes

---

src/Core/Parser/TemplateParser.php

Although this means a minor performance hit in compiled
templates in particular, we drop the variable extraction method
detection temporarily.
The extractor detection will be restored in another and much
larger pull request which will also merge the variable extraction
detection and the extraction logic into VariableProvider rather
than forcing use of Fluid's VariableExtractor.
Close: #255

[BUGFIX] Disable variable extractors

---

src/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php

This patch removes all {namespace} declarations after
they have been detected, thus preventing them from
being output when rendering the template which does
not use sections but contains {namespace} declarations.

[BUGFIX] Remove detected {namespace} declarations

---

src/View/TemplatePaths.php

Since the method does not explicitly require nor check for
a string being passed, a check is added to detect arrays
and call `array_map` to (recursively) sanitize each path.

[BUGFIX] Handle potential array input in sanitizePath method

---

src/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php

Due to slight differences in how Fluid detects xmlns declarations
in templates, TYPO3 CMS has had to deliver not one, but two
separate methods of detecting and registering namespaces.
This patch synchronises the behavior and removes the need for
TYPO3 CMS to process the template for namespaces.
There is one main difference introduced by this patch:
All xmlns declarations are now stripped from the tag; and the tag
itself is stripped away if `data-namespace-typo3-fluid="true"`
is set on the tag.

[FEATURE] Synchronise xmlns extraction with TYPO3 CMS

---

src/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php

Since the method now modifies the template source string,
the source should also be returned from the method.

[BUGFIX] Return modified source from namespace detection

---

examples/Resources/Private/Partials/EscapingModifierPartial.html
examples/Resources/Private/Singles/EscapingModifier.html
examples/example_escapingmodifier.php
src/Core/Parser/TemplateParser.php
src/Core/Parser/TemplateProcessor/EscapingModifierTemplateProcessor.php
src/Core/Rendering/RenderingContext.php
tests/Functional/ExamplesTest.php
tests/Unit/Core/Parser/TemplateParserTest.php
tests/Unit/Core/Parser/TemplateProcessor/EscapingModifierTemplateProcessorTest.php

This patch adds support for disabling escaping throughout
an entire template file. This is done by using:
```
{escaping off}
```
In a template, layout or partial. When toggled off it
causes the template parser to skip escaping of all
outputs from ViewHelpers, variable outputs etc.
For legacy reasons the feature is added with backwards
compatibility for the original escaping modifier which
was introduced in Flow. Therefore, the following values
are all equally possible and mean the same:
```
{escaping off}
{escapingEnabled off}
{escaping false}
{escaping=false}
{escaping=off}
{escaping = off}
{escapingEnabled = off}
{escapingEnabled = false}
{escapingEnabled off}
{escapingEnabled false}
```
While it is possible to set a `true` value for the modifier,
this simply gets ignored (because …

[FEATURE] Add escaping modifier pre-processor

---

src/View/AbstractTemplateView.php
tests/Unit/View/AbstractTemplateViewTest.php

Prevents issues where calling renderSection multiple
times caused incorrect results because TemplateCompiler
holds on to the first parsed template.
By resetting the compiler in stopRendering() we ensure
that we have a fresh scope when a user calls render,
renderPartial or renderSection multiple times on the
same View instance.

[BUGFIX] Reset compiler after each render operation

---

src/Core/ViewHelper/ViewHelperResolver.php

Check if the namespace identifier exists and is not null before calling
in_array to avoid php warnings.
This is necessary to successfully work with construct like
```xml
{namespace content}
....
<content:encoded>
...
</content:encoded>
```
This is used in templates for rss feeds.

[BUGFIX] PHP warning with "empty" namespaces

---

src/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php
tests/Unit/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessorTest.php

See included test case; last set in data provider fails without patch
and does not detect any namespace and does not remove the
container tag. With the patch the NS is detected and tag is removed.

[BUGFIX] Correctly detect xmlns namespaces with uppercase chars

---

src/Core/ViewHelper/AbstractConditionViewHelper.php
tests/Unit/Core/ViewHelper/AbstractConditionViewHelperTest.php

This simple example should render an empty string because the `condition` argument of the `f:if` tag evaluates to `false` and the `if` argument of the `f:else` tag evaluates to `false` too.
```html
<f:if condition="0">
<f:then>Not true</f:then>
<f:else if="0">Not true either!</f:else>
</f:if>
```
But the last else-child in a conditional view helper was rendered regardless of the outcome of its "if" condition in a non-compiled (i.e. the first) run. The compiled code seems to work fine, though.
Fixes #284

[BUGFIX] Don't render else-child if its "if" condition evaluates to "false"

---

.travis.yml

This fixes the Travis build for HHVM. HHVM is available on Trusty but not Precise anymore.

[BUGFIX] use the Trusty build environment

---

src/Core/Parser/SyntaxTree/BooleanNode.php
tests/Unit/Core/Parser/SyntaxTree/BooleanNodeTest.php

This fixes https://github.com/TYPO3/Fluid/issues/301
Even the docs are not right:
https://docs.typo3.org/typo3cms/ExtbaseFluidBook/8-Fluid/7-using-boolean-conditions.html
> A number for example is evaluated as true if it is greater than 0.
See http://php.net/manual/en/language.types.boolean.php
> Warning
-1 is considered TRUE, like any other non-zero (whether negative or positive) number!
https://softwareengineering.stackexchange.com/a/300792/41772
Negative numbers in PHP are true. Currently it is not consistent with the negative number handling in PHP. This PR fixes it.

[BUGFIX] Evaluate negative numbers as boolean like PHP does

---

src/View/TemplatePaths.php
tests/Unit/View/TemplatePathsTest.php

Class TemplatePaths will now correctly return the class variable layoutPathAndFilename if it was set before
Resolve: #309

[BUGFIX] Fixes layoutPathAndFilename behavior in TemplatePaths (#309)

---

src/Core/Compiler/TemplateCompiler.php
tests/Unit/Core/Compiler/TemplateCompilerTest.php

Instances are stored with the sanitzied identifier into a runtime cache.
The `TemplateCompiler::has()` must also use the sanitzed version of the
identifier to check if the instance exists in the runtime cache.

[BUGFIX] Use sanitized identifier in TemplateCompiler::has()

---

src/Core/Cache/SimpleFileCache.php
tests/Unit/Core/Parser/TemplateParserTest.php

`require` and `include` are statements, not functions. Therefore the parentheses are not needed.

[TASK] require and include are statements

---

src/Core/Compiler/TemplateCompiler.php

This patch prevents a problem where it is made up to the individual cache implementation whether or not to re-load a class file when a class is already defined. Instead, making the compiler only fetch the class from cache if it is not already loaded (by checking class_exists without allowing autoloading!) prevents re-loading classes with “class already declared” errors to follow.

[BUGFIX] Prevent re-loading cached classes that already exist

---

src/Core/Parser/BooleanParser.php
tests/Functional/Cases/Conditions/BasicConditionsTest.php
tests/Unit/Core/Parser/BooleanParserTest.php

With this commit the user can choose to use „and“ instead of „&&“ and „or“ instead of „||“ in boolean conditions
closes #319

[FEATURE] add and/or alternative for ||/&& syntax

---

src/Core/Compiler/TemplateCompiler.php
src/Core/Compiler/UncompilableTemplateInterface.php
src/Core/Parser/TemplateParser.php
tests/Unit/Core/Compiler/TemplateCompilerTest.php
tests/Unit/Core/Parser/TemplateParserTest.php

Problem briefly described:
Uncompilable templates are both parsed and attempted compiled
on each initial rendering (once per request/context). Because no
result is stored if a template is not compilable, the compiler does
not know that it should not attempt to compile the template.
This patch introduces a few measures to create a compiled stub
class which informs the template parser and compiler that the
template was attempted compiled but determined uncompilable,
so the compiler should not attempt to compile it by converting
the syntax tree to PHP code.
The stub template is achieved by allowing the template compiler
to also "compile" ParsedTemplateInterface implementations which
have the "compilable" flag set to false. When this is the case, the
compiler creates a stub class which skips …

[TASK] Improve performance of uncompilable templates

---

src/Core/Parser/TemplateParser.php

Problem briefly described: numbers passed in tag attributes vs. numbers passed in inline syntax (which internally uses the array
syntax parsing) handles numeric values in two different ways:
* In tags, a NumericNode is created if is_numeric is true
* In arrays, numbers are cast with (float) and matched by regexp
NumericNode also casts the value but does so by using an add-
zero trick which makes PHP do the casting based on string value,
and the input is always a string in the parser. This means that the
two different ways of passing a number will produce two different
types of variables given natural numbers as input. Passing floats
still causes the same type.
The solution is to apply the same method of casting in both cases.

[BUGFIX] Make casting of numbers the same in arguments and arrays

---

src/Core/ViewHelper/ViewHelperResolver.php

Using a static class property for the cache could have bad
side effects for setups which have multiple contexts for
Fluid and may change the namespaces between contexts.
Converting the cache to a non-static property cleans it
properly when a new ViewHelperResolver is created.

[BUGFIX] Make ViewHelperResolver internal cache non-static

---

src/View/TemplatePaths.php
tests/Unit/View/Fixtures/LegacyTemplatePathsFixture.php
tests/Unit/View/LegacyTemplatePathsTest.php
tests/Unit/View/TemplatePathsTest.php

This patch addresses the following issues, all in TemplatePaths.
**Format-related issues**
* Method signatures contain default format which means the
configured format (setFormat($format)) would not be respected
and had to be passed every time. Changed to null and call to
getFormat() when value is null.
* When extracting path arrays, default format would always be
"html" instead of what was configured in TemplatePaths.
* Layout name prefix did not contain format when generating
an identifier, which could cause colissions between two Layouts
with the same name but different formats.
**General issues/improvements**
* Exception message improved to explicitly report "no paths set".
* Removed `array_values` when extracting template paths, thus
preserving the paths' original indexes.
In …

[BUGFIX] File resolving related fixes

---

src/Core/ViewHelper/ViewHelperVariableContainer.php
tests/Unit/Core/ViewHelper/ViewHelperVariableContainerTest.php

A method `getAll` is added to ViewHelperVariableContainer
which allows getting all variables for a ViewHelper as array.
A new method `addAll` is added as well, allowing a complete
set of variables to be added/overridden at the same time.
The resulting two methods allows a ViewHelper to use many
options with defaults as needed, and just one method call to
retrieve all of them and another call to update all of them.

[FEATURE] Add getAll / addAll to ViewHelperVariableContainer

---

src/Core/Rendering/AbstractRenderable.php
src/Core/Rendering/RenderableClosure.php
src/Core/Rendering/RenderableInterface.php
src/Core/Rendering/StandardRenderable.php
src/ViewHelpers/RenderViewHelper.php
tests/Unit/ViewHelpers/RenderViewHelperTest.php

This patch adds a new interface for "renderable" objects,
which allows any object to adopt the interface and when
assigned to the template, render itself based on the current
RenderingContext. A new argument "renderable" is added
to `f:render` to render such objects. Two implementations
are added: a StandardRenderable which renders a Node,
and a ClosureRenderable which renders arbitrary closures.
The feature is also the basis for a larger refactoring which
finally stop storing sections in the VariableProvider while
parsing, by providing a proper API for getting sections
from a parsed template object.

[FEATURE] Introduce concept of Renderables

---

src/Core/ViewHelper/AbstractViewHelper.php
src/Core/ViewHelper/ViewHelperInterface.php
tests/Unit/Core/ViewHelper/AbstractViewHelperTest.php
tests/Unit/Core/ViewHelper/Fixtures/RenderMethodFreeDefaultRenderStaticViewHelper.php
tests/Unit/Core/ViewHelper/Fixtures/RenderMethodFreeViewHelper.php

ViewHelpers are no longer required to, nor suggested to, implement a render() method.
If the method does not exist, `callRenderMethod` instead calls `renderStatic` if it is implemented on the class (i.e. not inherited from the base class). If the VH class does not implement render() and inherits renderStatic() an exception is thrown, informing the developer to implement one or the other (with preference for renderStatic that is declared on the interface).

[FEATURE] Make render method optional

---

src/Core/Parser/ParsingState.php
src/Core/Parser/SyntaxTree/AbstractNode.php

Allows class overrides to only override getRootNode
on ParsingState in order to change which node gets
returned, instead of also having to override the
render() method. Does not affect behavior.

[TASK] Call getter instead of accessing property

---

examples/Resources/Private/Singles/ErrorHandling.html
src/View/AbstractTemplateView.php

Somewhere, respect for $ignoreUnknown was lost. This patch
adds a check and only throws the exception if it is false.

[BUGFIX] Respect $ignoreUnknown when rendering section/partial

---

composer.json

Updates the composer manifest license value to the
current way of saying LGPL 3 or later.

[TASK] Update deprecated license for Packagist

---

src/ViewHelpers/DebugViewHelper.php
tests/Unit/ViewHelpers/DebugViewHelperTest.php

The debug viewhelper use now DateTime::ATOM instead of DateTime::ISO8601.
This format is not compatible with ISO-8601, but is left this way for backward compatibility reasons. Use DateTime::ATOM or DATE_ATOM for compatibility with ISO-8601 instead.
Resolves: #374

[BUGFIX] Switch incompatible use of DateTime format

---

examples/Resources/Private/Singles/Conditions.html
examples/example_conditions.php
src/Core/Parser/SyntaxTree/Expression/TernaryExpressionNode.php
src/Core/Parser/TemplateParser.php
tests/Functional/ExamplesTest.php

This patch corrects the following problems for
ternary conditions:
* Dotted paths were not detected correctly.
* The “then” part was mandatory
* Negating the condition did not work correctly
All three described cases are working now.
Fixes: #148

[BUGFIX] Fix ternary condition behaviors

---

src/Core/ViewHelper/AbstractConditionViewHelper.php
src/ViewHelpers/IfViewHelper.php
tests/Unit/ViewHelpers/IfViewHelperTest.php

The AbstractConditionViewHelper method evaluateCondition
was less than ideal, in that it:
* Only received arguments and thus could not support context
related conditions.
* Was protected which prevents a future refactoring to call the
method to evaluate directly from the compiled code.
* Was not strictly requiring an array of arguments which meant
technically unsafe code (static analysis would demand guard)
Instead of breaking the API, the old method is deprecated in
favor of a new method which strictly requires arguments as an
array and the current instance of the rendering context.
The new method is made public though it is still not being
called as such - this is in preparation for a future improvement
of the compiled code to clean up the current closure-based
solution for evaluating …

[FEATURE] Deprecate evaluateCondition() in favor of verdict()

---

src/Core/Cache/StandardCacheWarmer.php
tests/Unit/Core/Cache/StandardCacheWarmerTest.php

A bug in the warmup code meant that all templates,
partials and layouts which were in sub-folders in
the root paths, would cause file not resolved errors
due to using basename() on the absolute file path.
To remedy this, each path has to be traversed by
itself and the relative file path has to be determined
by trimming off the root path. The result is that any
level of sub-folders can be supported in warmup.

[BUGFIX] Process paths individually in warmup

---

examples/Resources/Private/Singles/Structures.html
src/Core/Parser/Patterns.php
tests/Functional/ExamplesTest.php

This patch improves the inline syntax of Fluid in the
following ways:
* The “pipe” character can be used instead of “->” to
pass tag contents, e.g. {variable | f:format.raw()}. This
is done to approach shell syntax and for easier picking
up of Fluid syntax if you come from Twig.
* Arguments for inline VH calls can now be specified with
tag attribute syntax. Commas were already optional which
allowed syntax like “{v:h(foo: bar baz: 123)}”. This is now
homogenised completely so you can use expressions like
“{v:h(foo=“{bar}” baz=“123”)}” - which means that you
can now migrate a tag-based usage to inline syntax
without having to touch the arguments you provided as
tag attributes.
All is achieved by adding two characters to the list that is
detected as inline syntax - “|” and “=“ - and by …

[FEATURE] Improve inline syntax for arguments and passing

---

src/ViewHelpers/InlineViewHelper.php
tests/Unit/ViewHelpers/InlineViewHelperTest.php

Allows rendering a variable containing Fluid code as
if the code contained in the variable were part of the
template invoking the ViewHelper.
$view->assign('variable', 'value of my variable');
$view->assign('code', 'My variable: {variable}');
And in the template:
{code -> f:inline()}
Which outputs:
My variable: value of my variable
You can use this to pass smaller and dynamic pieces of Fluid code
to templates, as an alternative to creating new partial templates.

[FEATURE] Inline fluid ViewHelper

---

src/Core/ViewHelper/AbstractTagBasedViewHelper.php

We have found an issue where consecutive viewhelpers take over properties from the previous one. 
This is the TYPO3 bug report: https://forge.typo3.org/issues/86890

[BUGFIX] Prevent property spill-over to next call

---

tests/Unit/View/TemplatePathsTest.php

Fixes a sometimes failing, sometimes succeeding unit
test which compares arrays of resolved files.
Sorts both arrays before comparison because at this
point in tests we don’t care about the order, which is
tested by other methods.
Unblocks #421

[TASK] Canonicalize arrays before comparison

---

src/Core/Compiler/TemplateCompiler.php
tests/Unit/Core/Compiler/TemplateCompilerTest.php
tests/Unit/ViewHelpers/SwitchViewHelperTest.php

When compiled templates are retrieved from the cache and contain binary characters, arbitrary behavior may occur, usually a huge pile of Chinese-like characters is outputted and the template class cannot be loaded. Avoid this by delegating the generation of the compiled node state to the node converter.

[BUGFIX] Prevent binary characters in compiled templates

---

src/Core/Variables/VariableExtractor.php
tests/Unit/Core/Fixtures/ClassWithMagicGetter.php
tests/Unit/Core/Fixtures/ClassWithProtectedGetter.php
tests/Unit/Core/Variables/VariableExtractorTest.php

Value extraction will now support delegation of getter calls
via PHP‘s __call() magic method. Additionally, extracting a property
that results in a protected getter call will stop raising an error.
Solves #437

[BUGFIX] Support overloaded methods when extracting variables

---

src/Core/ViewHelper/Traits/CompileWithContentArgumentAndRenderStatic.php
src/Core/ViewHelper/Traits/CompileWithRenderStatic.php

A view helper might render the result into an array
and still use CompileWithRenderStatic to be compilable,
the return type annotations should reflect that.

[TASK] Allow mixed renderStatic() return types in compile traits

---

src/ViewHelpers/IfViewHelper.php

Comparing strings directly without using array comparison workaround is now possible.
Related: #442

Update IfViewHelper to reflect changes in string comparison

---

doc/FLUID_IMPLEMENTATION.md
doc/FLUID_STRUCTURE.md

Maybe the good way would be to have not any reserved variable names. But in the meantime, this one should be documented.

[TASK] Add a note about the special variable layoutName

---

examples/Resources/Private/Singles/Variables.html
src/Core/Parser/Interceptor/Escape.php
src/Core/Parser/InterceptorInterface.php
src/Core/Parser/TemplateParser.php
tests/Functional/ExamplesTest.php

Prevents a potential security issue when expression
nodes are used to output variables, in which case,
they would not be properly escaped.
The fix implements escaping interception for these
expression nodes.
https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?vector=AV:N/AC:H/PR:N/UI:R/S:C/C:L/I:L/A:N/E:F/RL:O/RC:C

[BUGFIX] Ensure escaping of escapable ExpressionNode

---

composer.json

Renames the composer package and sets the “replace”
composer option so it only replaces Fluid 3.0 or above.

[FEATURE] Rename Fluid 3.0+ to typo3/fluid-engine

---

src/Core/Variables/StandardVariableProvider.php
tests/Unit/Core/Variables/StandardVariableProviderTest.php

The bugfix/feature which was introduced in #438 where the function `is_callable` was used, is also necessary in StandardVariableProvider.

[BUGFIX] Support overloaded methods in StandardVariableProvider

---

src/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php

The annotation of the property `NamespaceDetectionTemplateProcessor::$localNamespaces` is changed to being `@var array` to fix issues with the recent version of `phpdocumentor/reflection-docblock`.

[BUGFIX] Fix broken annotation of property (#476)

---

src/Core/ViewHelper/ViewHelperResolver.php
tests/Functional/Cases/Parsing/NamespaceRegistrationTest.php

Restores incorrect revert https://github.com/TYPO3/Fluid/commit/2b5ffd5ef66a557b4bf01fd74d65c2df6fec1587
which was unintentionally reverted as part of #489.
Fixes a regression in namespace resolving behavior,
wherein a conflicting ignored namespace (e.g. "f*")
incorrectly caused the registered namespace to be
ignored (e.g. "f:" would be ignored).
References: #451, #475, #489
References: https://github.com/neos/flow-development-collection/issues/1761

[BUGFIX] Handle conflict with registered/ignored namespaces (#475)

---

.travis.yml
bin/fluid
src/Core/Parser/SyntaxTree/Expression/TernaryExpressionNode.php
src/Core/Parser/TemplateParser.php
src/Core/Variables/JSONVariableProvider.php
src/View/AbstractTemplateView.php
src/View/TemplatePaths.php

Which is mainly not using curly braces to get characters
of a string and checking for valid arrays before accessing
them.
See https://wiki.php.net/rfc/notice-for-non-valid-array-container
for a further explanation.
To stay compatible with PHP 5 `isset` is used instead of a null
coalesce operator:
`isset($foo['bar']) ? $foo['bar'] : null;`
vs.
`$foo['bar'] ?? null;`

[FEATURE] Make fluid PHP 7.4 compatible

---

src/View/TemplatePaths.php

Guard TemplatePaths->createIdentifierForFile against
attempts to use filemtime() on a file which does not
exist. Return a zero timestamp in this case.

[BUGFIX] Guard against filemtime on missing file

---

src/Component/ComponentInterface.php

Functionless stub for ComponentInterface to allow
ViewHelpers to implement API from Fluid 3.x and
still be technically valid in terms of static analysis.

[TASK] Add stub for ComponentInterface

---

doc/FLUID_CREATING_VIEWHELPERS.md
doc/FLUID_VIEWHELPERS.md

Avoids use of pseudo-ViewHelper "f:fluid" in favor
of traditional way using "html" tag.
Close: #448

[DOC] Remove wrong namespace registration examples

---

tests/Unit/Core/Variables/StandardVariableProviderTest.php
tests/Unit/Core/Variables/VariableExtractorTest.php

This patch adds two missing test cases for VariableExtractor
and StandardVariableProvider. The absence of these tests
has caused two pull requests to be rejected even though the
patches' tests ran successfully.
To prevent future pitfalls, the test case that would fail if a
developer attempts to make multiple same-level sub-variable
references work, are added in the appropriate places.
References: #509, #472

[TASK] Add two missing test cases

---

src/Component/Argument/ArgumentCollection.php

Creates a stub for the new ArgumentCollection class which
is added in Fluid 3.0. Allows Fluid 2.x implementations to
be technically valid when performing static analysis on
classes which implement API for both Fluid 2.x and 3.x.

[TASK] Stub ArgumentCollection from Fluid 3.0 API

---

src/Core/Compiler/NodeConverter.php

fixes: https://github.com/TYPO3/Fluid/issues/517

Escape single quotes in cache static viewhelper

---

src/Core/ViewHelper/AbstractTagBasedViewHelper.php
tests/Functional/Cases/TagBasedTest.php
tests/Unit/Core/ViewHelper/AbstractTagBasedViewHelperTest.php

Due to a regression in https://github.com/TYPO3/Fluid/pull/419,
a TagBasedViewHelper which was called with one or more
data- prefixed arguments would discard the prefixed arguments
and the output would not contain the attribute.
This patch fixes that regression by moving the handling of
unregistered arguments to the initialize() function in order
to make sure the additional attributes are handled *after*
the reset() method has been called on TagBuilder.
References: #419

[BUGFIX] Restore support for data- prefixed arguments

---

src/Core/ViewHelper/AbstractTagBasedViewHelper.php
src/Core/ViewHelper/TagBuilder.php
tests/Functional/Cases/TagBasedTest.php
tests/Unit/Core/ViewHelper/AbstractTagBasedViewHelperTest.php

To support developers in building accessible applications,
the AbstractTagBasedViewHelper now provides a new
argument aria. It therefore can be used to add additional
aria attributes to the HTML element.

[FEATURE] Introduce aria argument in AbstractTagBasedViewHelper

---

src/View/ViewInterface.php

Fix the namespace to the actual position of the exception.

[BUGFIX] Correct throws annotation in ViewInterface

---

src/Core/Rendering/RenderingContext.php
src/View/AbstractTemplateView.php
tests/Unit/Core/Parser/SyntaxTree/Expression/CastingExpressionNodeTest.php
tests/Unit/Core/Parser/SyntaxTree/Expression/MathExpressionNodeTest.php
tests/Unit/Core/Parser/SyntaxTree/Expression/TernaryExpressionNodeTest.php
tests/Unit/Core/Parser/SyntaxTree/RootNodeTest.php
tests/Unit/Core/Rendering/RenderingContextTest.php
tests/Unit/Core/ViewHelper/AbstractViewHelperTest.php
tests/Unit/Core/ViewHelper/ViewHelperInvokerTest.php
tests/Unit/ViewHelpers/SwitchViewHelperTest.php

The constructor of AbstractTemplateView instantiates RenderingContext,
handing itself over as constructor argument.
However, there is no point the RenderingContext knows it's view, and
$this->view is actually completly unused. There is also no getter or
anything accessing the property.
The patch resolves this circular dependency by dropping
the required constructor argument in RenderingContext.

[BUGFIX] Circular dependency RenderingContext<->AbstractTemplateView

---

src/Core/ViewHelper/ViewHelperVariableContainer.php
src/ViewHelpers/RenderViewHelper.php
tests/Unit/ViewHelpers/RenderViewHelperTest.php

This change corrects the signature of
ViewHelperVariableContainer->getView to reflect
that the return is possibly-null, and throws a
very specific exception in f:render if encountering
that case (indicating that a RenderingContext
override was incomplete or incorrect).

[BUGFIX] Handle possibly-null view instance

---

src/Core/ViewHelper/TagBuilder.php

Public TagBuilder->addAttribute() accepts null as
$attributeValue. htmlspecialchars(null) in non strict types
context raises a E_DEPRECATED level error since PHP 8.1.
The patch sanitizes the call using a string cast.

[BUGFIX] Sanitize htmlspecialchars(null) in TagBuilder

---

src/View/TemplatePaths.php

Helper method resolveTemplateFileForControllerAndActionAndFormat()
can return null for invalid controller / action combinations.
Calling file_exists(null) in non strict types context raises a
E_DEPRECATED level error since PHP 8.1.
Sanitize according calls in TemplatePaths.

[BUGFIX] Sanitize file_exists(null) in TemplatePaths

---

src/ViewHelpers/SpacelessViewHelper.php

Invoking $childClosure() may return null. Feeding null as third
argument to preg_replace raises a E_DEPRECATED level error in
PHP 8.1 in non strict types context.
Sanitize that call.

[BUGFIX] Avoid preg_replace('', '', null) in SpacelessViewHelper

---

tests/Functional/Cases/Conditions/BasicConditionsTest.php
tests/Unit/Core/Parser/BooleanParserTest.php
tests/Unit/Core/Parser/SyntaxTree/BooleanNodeTest.php

Some tests has been expecting results on how php <8.0
behaves. These expectations were hard coded. These tests
had further tested raw php execution as a second match.
This patch sets the hardcoded expected values to values
based on the current php version used to run the
testsuite.
Testes with php8.0 enabled build, which demonstrates that
tests working with it. Still have issue with clover file
as current phpunit version do not support it.
See: https://github.com/sbuerk/Fluid/runs/3979490519?check_suite_focus=true
Fixes: #566

[TASK] Change expected values to match used php version behaviour

---

.github/workflows/build.yml
composer.json
phpunit.xml.dist
src/Core/Compiler/TemplateCompiler.php
tests/Unit/Core/Compiler/TemplateCompilerTest.php
tests/Unit/ViewHelpers/Fixtures/CountableIterator.php

This pull-request contains multiple commits, which works to the point that github workflow testing is green with PHP 7.2, 7.3, 7.4, 8.0 and 8.1 with E_ALL error_reporting and display_errors = 1, or to say shortly tested as hard as possible.
To get there, some fixes have to be added, mainly fix inpropper testsetup (mock) or an
incompatible test fixture. 
Furthermore two packages will be raised for the minumum version as these are the needed
versions absolutly needed for PHP8.1 execution.
Note: There is one drawback, uploading coverage get disabled for PHP8.0 and PHP8.1 as
phpunit 8.5.x do not support creating corresponding file when run with PHP8.0 or 8.1.
As phpunit 9.x needs at least PHP7.3, I choosed to disable the uploading for now.
This has to be investigated further to find a …

[TASK] Move testing forward until PHP8.1 testing with display_errors=1 and E_ALL testing

---

src/View/TemplatePaths.php
tests/Unit/View/Fixtures/ARandomController/TestTemplate.html
tests/Unit/View/TemplatePathsTest.php

The current templatePaths functionality is highly limited,
in order to run Fluid with an "ADR" approach where each
Action represents a single PHP class (single responsibility),
Fluid always expected a Controller in order to build the path.
This change addresses the issue when a TemplatePaths object
is built with an empty controller (""), to resolve the paths
correctly when trying to locate the proper file path.

[BUGFIX] Allow action-only templates to work

---

src/Core/ViewHelper/Traits/CompileWithContentArgumentAndRenderStatic.php
tests/Functional/Cases/CompileWithContentArgumentAndRenderStaticTest.php
tests/Functional/Fixtures/ViewHelpers/CompileWithContentArgumentAndRenderStaticExplicitSetArgumentNameForContentInConstructorViewHelper.php
tests/Functional/Fixtures/ViewHelpers/CompileWithContentArgumentAndRenderStaticExplicitSetArgumentNameForContentOverriddenResolveContentArgumentNameMethodViewHelper.php
tests/Functional/Fixtures/ViewHelpers/CompileWithContentArgumentAndRenderStaticExplicitSetArgumentNameForContentViewHelper.php
tests/Functional/Fixtures/ViewHelpers/CompileWithContentArgumentAndRenderStaticFirstRegisteredOptionalArgumentAfterRequiredArgumentAsRenderChildrenViewHelper.php
tests/Functional/Fixtures/ViewHelpers/CompileWithContentArgumentAndRenderStaticUseFirstRegisteredOptionalArgumentAsRenderChildrenViewHelper.php

This pull-request contains two commits:
- Adding tests to cover this trait and show that implementation is broken
- Provide the change to document how to set this property correctly
As this is needed for changes in the Typo3 core, it would be nice if
a new patchlevel release could be done after approving and merging this,
so a pending core change can be reviewed and processed:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/73014
Fixes: #582

[TASK] Change property docblock of $contentArgumentName how to set it

---

src/View/AbstractTemplateView.php
src/View/TemplateAwareViewInterface.php

Method render() of AbstractTemplateView has an
optional argument to provide a template name.
This is not reflected in ViewInterface since
ViewInterface does not know about templates.
The patch adds an optional TemplateAwareViewInterface
to reflect this argument in 'template aware'
views like TemplateView.

[TASK] Add TemplateAwareViewInterface

---

src/Core/ViewHelper/TagBuilder.php

The method can obviously return null.

[BUGFIX] Fix type annotation on TagBuilder->getAttribute()

---

README.md

scrutinizer is stalled / misconfigured for a long time
already. Remove it from the README.md badge list.

[TASK] Remove stalled scrutinizer badge from README.md

---

.github/workflows/build.yml

There is little point in current codebase to manage
test coverage for multiple PHP versions. The patch
restricts 'coveralls' analysis to one PHP version
only, to reduce complexity and to deal with main
branch correctly.

[TASK] Update php coveralls for only one PHP version

---

composer.json

Current main-branch is de-facto PHP >=7.2 already since
we're not testing any lower PHP version for quite a while.
This patch requires a 2.8.0 as next release since we're
now forcing a higher minimum PHP version.
Resolves #405

[!!!][TASK] Require PHP >=7.2

---

LICENSE.txt
README.md

For whatever reasons, the LICENSE file has
been reformatted and rephrased in the past.
The patch switches to the original phrasing
from LGPL 3.0 [1], which should make services
like github recognize the project to be release
under a common open source license.
[1] https://www.gnu.org/licenses/lgpl-3.0.txt

[TASK] Use original LGPL 3.0 license

---

.github/workflows/build.yml
README.md
composer.json

Coverage is a lie. With current configuration, it
does not really reflect actual test statistics and
"97%" is simply misleading since it ignores files
that are not loaded at all durnig tests.
As such, this statistic does not actively help us
in current development and should be dropped.
Naturally, patches that have parser impact need
proper test coverage and won't be accepted without.
A misleading coverage generator does not help
us here.

[TASK] Remove coveralls code coverage stats

---

tests/Functional/BaseConditionalFunctionalTestCase.php
tests/Functional/BaseFunctionalTestCase.php
tests/Functional/Cases/CompileWithContentArgumentAndRenderStaticTest.php
tests/Functional/Cases/Rendering/DataAccessorTest.php
tests/Functional/Cases/TagBasedTest.php
tests/Functional/CommandTest.php
tests/Functional/ExamplesTest.php

First patch to improve test class inheritance: Functional
tests no longer extend (empty) UnitTestCase, but BaseTestCase
instead.

[TASK] Functional tests extend BaseTestCase

---

tests/Functional/Core/Cache/SimpleFileCacheTest.php

Make that unit test a functional test and let it
write to php tmp-dir to perform tests. This avoids
vfsStream magic and uses casual functional setup.

[TASK] Make SimpleFilecache a functional test

---

.gitattributes

The class is an abstract for unit testing VH's. Exporting
it does not make sense since it has a direct dependency to
RenderingContextFixture is setup(), which is not exported.
The patch excludes the file from packaging again, which
also allows Fluid to refactor internally without being
breaking.
Resolves #562

[TASK] Stop exporting ViewHelperBaseTestcase

---

tests/Functional/Core/Cache/SimpleFileCacheTest.php
tests/Unit/Core/Compiler/TemplateCompilerTest.php
tests/Unit/Core/Parser/TemplateParserTest.php
tests/Unit/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessorTest.php
tests/Unit/Core/ViewHelper/AbstractConditionViewHelperTest.php
tests/Unit/Core/ViewHelper/AbstractTagBasedViewHelperTest.php
tests/Unit/Core/ViewHelper/AbstractViewHelperTest.php
tests/Unit/View/AbstractTemplateViewTest.php
tests/Unit/ViewHelpers/AliasViewHelperTest.php
tests/Unit/ViewHelpers/DebugViewHelperTest.php
tests/Unit/ViewHelpers/ElseViewHelperTest.php
tests/Unit/ViewHelpers/InlineViewHelperTest.php
tests/Unit/ViewHelpers/LayoutViewHelperTest.php
tests/Unit/ViewHelpers/OrViewHelperTest.php
tests/Unit/ViewHelpers/RenderViewHelperTest.php

To prepare towards phpnunit 9, we avaid a couple
of deprecated things.

[TASK] Avoid at() and assertFileNotExists()

---

tests/Functional/ExamplesTest.php

Preparing phpunit 9, the closure output assertion
needs to be streamlined a bit to continue to work.

[TASK] Simplify ExamplesTest output assertion

---

composer.json

phpunit 8 needs to be kept for PHP 7.2.
composer req --dev phpunit/phpunit:"^8.5.26 || ^9.5"

[TASK] Allow phpunit 9

---

src/Core/Parser/SyntaxTree/Expression/TernaryExpressionNode.php
tests/Functional/Cases/Conditions/TernaryConditionsTest.php

Ternary expressions are broken with cached templates.
Even with simple things like this:
$view->assign('myVariable', false);
{myVariable ? 'yes' : 'no'}
This evaluates correctly to 'no' on first call with cold
caches, but to 'yes' when a cached template is used
on subsequent calls.
This came up when the functional tests have recently been
fixed to correctly test cached behavior.
The fix is to evaluate() the "left" / "check" side just
like the non-cached variant does.

[BUGFIX] Correct cached ternary expressions

---

phpstan-baseline.neon
src/Core/Compiler/NodeConverter.php
src/Core/ViewHelper/Traits/ParserRuntimeOnly.php
tests/Functional/Cases/Rendering/NestedFluidTemplatesWithLayoutTest.php
tests/Functional/ViewHelpers/SectionViewHelperTest.php
tests/Unit/Core/ViewHelper/Traits/ParserRuntimeOnlyTest.php

ViewHelperInterface->compile() is annotated to return
string. ParserRuntimeOnly violates this and returns
null instead. This leads to different behavior in
consuming ViewHelpers between non-compiled and compiled
versions.
The change adapts ParserRuntimeOnly->compile() to
return an empty string and changes NodeConverter to
deal with it. A string cast is added to stay compatible
in case some other compile() method returns null as well.

[BUGFIX] ParserRuntimeOnly trait compile() returns string

---

src/ViewHelpers/SwitchViewHelper.php
tests/Functional/ViewHelpers/SwitchCaseDefaultCaseViewHelperTest.php

The SwitchViewHelper tends to return a mix of empty
string and null, which can be different when used
in non-compiled and compiled context and the existance
of a 'default' fallback.
The patch changes the VH slightly to return empty
string instead of null more often.

[BUGFIX] Inconsistent return types in SwitchViewHelper

---

phpstan-baseline.neon
src/ViewHelpers/Cache/DisableViewHelper.php

compile() should return a string. Cache/DisableViewHelper
violates this. Let it return an empty string instead
of null.

[TASK] Cache/DisableViewHelper->compile() returns string

---

phpstan-baseline.neon
src/Core/Parser/ParsedTemplateInterface.php
src/Core/Parser/ParsingState.php
tests/Functional/Fixtures/Various/ParsedTemplateImplementationFixture.php

ParsedTemplateInterface->getLayoutName() may return
string|null, but only string is reflected in the method
annotation. Adapt this.

[TASK] Correct annotation on ParsedTemplateInterface

---

Documentation/Development/CreatingViewHelpers.rst
Documentation/Development/Decisions.rst
Documentation/Development/Expressions.rst
Documentation/Development/Implementation.rst
Documentation/Development/Index.rst
Documentation/Index.rst
Documentation/Installation/Index.rst
Documentation/Usage/Index.rst
Documentation/Usage/RunningExamples.rst
Documentation/Usage/Structure.rst
Documentation/Usage/Syntax.rst
Documentation/Usage/ViewHelpers.rst

This way, the topic can be linked from other manuals without referencing
a concrete page.
Additionally, a wrong link to Fluid Styled Content manual was fixed.

[DOCS] Add anchors to chapters

---

.github/workflows/build.yml
composer.json

With phpunit dropping prophecy dependency, we can avoid a CI PHP 8.2 related hack.
> composer req --dev "phpunit/phpunit":"^8.5.29 || ^9.5.24"

[TASK] Raise phpunit min-versions to avoid prophecy

---

src/Core/Parser/SyntaxTree/Expression/MathExpressionNode.php
tests/Unit/Core/Parser/SyntaxTree/Expression/MathExpressionNodeTest.php

Fixes #673
Allows multiple spaces as well as newline, tab etc. in between operator and operand.
This can be the case when formatting projects with, e.g. `prettier`:
Formatteres break maths expressions onto multiple lines, if they contain long variable names, such as:
```
<f:variable name="proportionalWidth"
><f:format.number decimals="2" thousandsSeparator=""
>{data.tx_someextensionlongname_and_even_some_more_field_name /
100}</f:format.number
></f:variable
>
```
This example fails before this PR, and succeeds after this PR.
---
Side note - rather independent of this PR:
It actualy fails quite miserably, with 
- the math expression node printing itself as `{data.tx_someextensionlongname_and_even_some_more_field_name / 100}`, 
- and the number formatting view helper printing an unexpected …

fix: Match mathematical expressions containing multiple whitespace chars

---

tests/Functional/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessorTest.php
tests/Unit/Core/Compiler/TemplateCompilerTest.php
tests/Unit/Core/Parser/TemplateParserTest.php
tests/Unit/Core/ViewHelper/AbstractTagBasedViewHelperTest.php
tests/Unit/Core/ViewHelper/AbstractViewHelperTest.php
tests/Unit/View/AbstractTemplateViewTest.php

We switched from withConsecutive() to
willReturnOnConsecutiveCalls() when adding
phpunit 10 support. This was partially broken
since various tests were designed to test the
input, which withConsecutive() does, but
willReturnOnConsecutiveCalls() does not.
Switch to a callback in some places, remove
a couple of heavily mocking tests altogether
and change some tests to functional tests.
In general, we should continue to avoid various
heavy mocking tests and various whitebox tests,
and substitute them with good functional tests.

[TASK] Fix tests using willReturnOnConsecutiveCalls()

---

src/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php

NamespaceDetectionTemplateProcessor->localNamespaces is protected and unused and can be removed without further impact.

[TASK] Remove unused protected variable

---

tests/Functional/ViewHelpers/GroupedForViewHelperTest.php

This test has probably been fixed with
cf46c129017481c61fc1b35fe0d74f0fceb0561b
and can be enabled.

[TASK] Enable a commented test

---

src/ViewHelpers/GroupedForViewHelper.php

We can switch to StandardVariableProvider
relatively easily. This VH has decent test
coverage, it looks as if this is fine.

[TASK] Avoid VariableExtractor in GroupedFor VH

---

src/ViewHelpers/DebugViewHelper.php

We can switch to StandardVariableProvider
relatively easily.

[TASK] Avoid VariableExtractor in Debug VH

---

src/Core/Variables/ChainedVariableProvider.php

VariableExtractor is deprecated for a long time,
use the methods from StandardVariableProvider
instead.

[TASK] Avoid VariableExtractor in ChainedVariableProvider

---

src/ViewHelpers/DebugViewHelper.php
src/ViewHelpers/GroupedForViewHelper.php

The recent changes avoiding VaribleExtractor can
be simplified a bit to not use nested array magic.

[TASK] Simplify usages of StandardVariableProvider

---

src/Core/Variables/VariableProviderInterface.php

The constructor declared in VariableProviderInterface is broken with the current usage. Add an @todo to clarify this needs to be changed.

[TASK] Comment broken VariableProviderInterface constructor

---

phpstan-baseline.neon
src/Core/Parser/Interceptor/Escape.php
tests/Unit/Core/Parser/Interceptor/EscapeTest.php

Resolves: #715
This change simply introduces the performance improvements already done by Claus Due in v3 to v2.x.
See https://github.com/TYPO3/Fluid/commit/6053dcb6987857bd8eeda765aef36fa9aad126a2

[TASK] Improve performance of Escape interceptor

---

src/Core/Variables/StandardVariableProvider.php
tests/Unit/Core/Variables/StandardVariableProviderTest.php

This method has been copied over from
deprecated VariableExtractor when this
class has been prepared for deprecation.
It is unused an can be removed without
further impact.

[TASK] Remove StandardVariableProvider->getAccessorsForPath()

---

src/Core/Variables/ChainedVariableProvider.php

ChainedVariableProvider adds an instance of
StandardVariableProvider by default. This is
odd, it should add it explicitly if needed.
This change is not considered breaking since
it affects an internal use case, mostly
related to cache warming.

[TASK] Simplify ChainedVariableProvider

---

tests/Unit/Core/Parser/TemplateParserTest.php

The second constructor argument of ObjectAccessorNode defaults to an empty array. There is no point in
handing this over explicitly in TemplateParserTest.

[TASK] Avoid creating ObjectAccessorNode with default argument

---

src/Core/Compiler/NodeConverter.php
src/Core/Parser/SyntaxTree/ObjectAccessorNode.php
tests/Unit/Core/Compiler/NodeConverterTest.php

In an attempt to improve compiled template performance, 82911b85 and 735f3362 established a second constructor argument on ObjectAccessorNode, handing over "accessors". This was later reverted in 48e43466 to fix #255.
As a result, ObjectAccessorNode is never called with a second constructor argument in business code, so $this->accessors is always an empty array.
The patch removes the second constructor argument
again and simplifies the generated template code
in NodeConverter accordingly.
Related: #255

[TASK] Remove variable accessors from ObjectAccessorNode

---

phpstan-baseline.neon
src/Core/Variables/VariableProviderInterface.php

The second argument $accessors can be removed
from VariableProviderInterface since it fits
no purpose anymore with a1645c53 being merged.
The patch removes the argument from the interface
only, keeping consumers as is for now, to verify
this change is not breaking.

[TASK] Simplify VariableProviderInterface->getByPath()

---

examples/src/CustomVariableProvider.php
phpstan-baseline.neon
src/Core/Variables/ChainedVariableProvider.php
src/Core/Variables/StandardVariableProvider.php
src/Core/Variables/VariableExtractor.php
tests/Unit/Core/Parser/SyntaxTree/ObjectAccessorNodeTest.php
tests/Unit/Core/Variables/StandardVariableProviderTest.php

Simplify especially StandardVariableProvider
getByPath() by avoiding the second argument
in the implementation. That argument has been removed from the VariableProviderInterface with c4f24ecd.

[TASK] Avoid second argument on getByPath()

---

src/Core/Compiler/NodeConverter.php

This minor modification makes the compiled source
code slightly better readable.

[TASK] Use "[]" instead of "array()" in compiled templates

---

src/Core/Variables/StandardVariableProvider.php
tests/Unit/Core/Variables/StandardVariableProviderTest.php

The getByPath() call in resolveSubVariableReferences() may return null if the variable can not be resolved. This leads to a PHP 8.1 deprecation when null is
given to str_replace().
Fix this and cover with tests.
Resolves: #584

[BUGFIX] Avoid null to str_replace() in StandardVariableProvider

---

src/Core/Variables/StandardVariableProvider.php
tests/Unit/Core/Variables/StandardVariableProviderTest.php

Allow {foo}bar{baz} and similar.
Resolves: #353

[BUGFIX] Support multiple references in variable names

---

composer.json

PHP mbstring is used by boolean parser in
a couple of places. TYPO3 core v12 has it
as hard requirement as well, it shouldn't
hurt much to finally require this in Fluid
as well.
> composer req ext-mbstring:*
Resolves: #622

[TASK] Require php mbstring

---

tests/Unit/Core/Variables/Fixtures/StandardVariableProviderModelFixture.php
tests/Unit/Core/Variables/StandardVariableProviderTest.php

Move this fixture file to a more appropriate place.

[TASK] Move StandardVariableProviderModelFixture to unit namespace

---

tests/Unit/Core/ViewHelper/Traits/Fixtures/ParserRuntimeOnlyFixture.php
tests/Unit/Core/ViewHelper/Traits/ParserRuntimeOnlyTest.php

phpunit 10.1 soft deprecated getMockForTrait().
We can avoid usages by adding a fixture class
that uses the trait.

[TASK] Avoid TestCase::getMockForTrait()

---

src/Core/ViewHelper/Traits/ParserRuntimeOnly.php
src/ViewHelpers/CommentViewHelper.php
src/ViewHelpers/LayoutViewHelper.php
src/ViewHelpers/SectionViewHelper.php
tests/Unit/Core/ViewHelper/Traits/Fixtures/ParserRuntimeOnlyFixture.php
tests/Unit/Core/ViewHelper/Traits/ParserRuntimeOnlyTest.php

This trait has been added with 127d8e70 for
no apparent reason: It was used three times
with one consumer overriding the render()
method again. There is no point to have a
trait for methods that only return null
or empty strings.
To simplify the construct a bit, the trait
is avoided and marked as @deprecated. Neither
Flow nor TYPO3 use the trait in own VH's,
impact should be quite small.

[TASK] Avoid and deprecate ParserRuntimeOnly trait

---

src/Core/Compiler/ViewHelperCompiler.php
src/Core/ViewHelper/Traits/CompileWithContentArgumentAndRenderStatic.php
src/Core/ViewHelper/Traits/CompileWithRenderStatic.php

The ViewHelperCompiler helper class has been
introduced a while ago and shrinked over
time again. It consists of one method with
an sprintf() and two constants nowadays.
It is used in the two traits
CompileWithRenderStatic and
CompileWithContentArgumentAndRenderStatic.
To simplify the code a bit, the code of
ViewHelperCompiler is now inlined to the
two traits, which makes them easier to
read and understand. ViewHelperCompiler
is marked @deprecated, neither Flow nor
TYPO3 use that class, so impact should be
rather low.

[TASK] Avoid and deprecate ViewHelperCompiler

---

tests/BaseTestCase.php
tests/Unit/Core/Parser/ParsingStateTest.php

BaseTestCase (which is currently API unfortunately) contains method getAccessibleMockForAbstractClass() which is used once for no good reason.
The patch refactors the consuming test case a bit
and marks the method @deprecated. This avoids a
call to getMockForAbstractClass(), which has been
marked as deprecated in phpunit 10.1.

[TASK] Deprecate getAccessibleMockForAbstractClass()

---

src/Core/Cache/SimpleFileCache.php

We're not measuring code coverage.
@codeCoverageIgnore can be removed.

[TASK] Avoid @codeCoverageIgnore

---

tests/BaseTestCase.php
tests/Functional/Core/Cache/SimpleFileCacheTest.php
tests/Unit/Core/Cache/StandardCacheWarmerTest.php
tests/Unit/Core/Compiler/NodeConverterTest.php
tests/Unit/Core/Compiler/TemplateCompilerTest.php
tests/Unit/Core/Parser/Interceptor/EscapeTest.php
tests/Unit/Core/Parser/SyntaxTree/AbstractNodeTest.php
tests/Unit/Core/Parser/SyntaxTree/BooleanNodeTest.php
tests/Unit/Core/Parser/SyntaxTree/Expression/CastingExpressionNodeTest.php
tests/Unit/Core/Parser/SyntaxTree/ObjectAccessorNodeTest.php
tests/Unit/Core/Parser/SyntaxTree/RootNodeTest.php
tests/Unit/Core/Parser/SyntaxTree/ViewHelperNodeTest.php
tests/Unit/Core/Parser/TemplateParserTest.php
tests/Unit/Core/Rendering/RenderingContextTest.php
tests/Unit/Core/ViewHelper/AbstractTagBasedViewHelperTest.php
tests/Unit/Core/ViewHelper/AbstractViewHelperTest.php
tests/Unit/Core/ViewHelper/ViewHelperResolverTest.php
tests/Unit/View/AbstractTemplateViewTest.php
tests/Unit/View/TemplatePathsTest.php

With latest phpunit versions BaseTestCase::getMock() becomes more and more unfortunate. The patch avoids all usages and deprecated the test helper method.
Strategies:
* Use phpunit native createMock() if possible
* Use phpunit native createMock() with interfaces if possible
* Use getMockBuilder() with onlyMethods() for more complex things
* Avoid mocking the test subject altogether if possible

[TASK] Avoid and deprecate getMock()

---

tests/BaseTestCase.php

The test related assert methods of BaseTestCase
should be deprecated. The patch inlines a
private helper method, declares the methods
protected, and removes unused trailing
arguments.

[TASK] Clean up special BaseTestCase asserters

---

tests/BaseTestCase.php
tests/Unit/Core/ViewHelper/AbstractTagBasedViewHelperTest.php

This assertion tests for an internal state
in it's single usage. There is little reason
for whitebox tests, stuff like that should
be covered by functional tests instead.
The patch removes a single usage and
deprecates the test helper assertion method.

[TASK] Deprecate BaseTestCase::assertAttributeInstanceOf()

---

tests/BaseTestCase.php
tests/Unit/Core/Cache/StandardCacheWarmerTest.php

BaseTestCase::assertAttributeNotEmpty() can be
avoided by refactoring a single test.

[TASK] Avoid and deprecate assertAttributeNotEmpty()

---

tests/Unit/Core/Cache/StandardCacheWarmerTest.php

StandardCacheWarmerTest:testWarm() test mocks
so much that it's totally unclear what it
actualy tests. It does not add value and is
removed.

[TASK] Remove a heavy mocking test

---

tests/BaseTestCase.php
tests/Unit/Core/ViewHelper/ViewHelperResolverTest.php

This whitebox test related methods can be
avoided by using casual getter methods on
test subject instead.

[TASK] Avoid and deprecated assertAttributeContains()

---

tests/BaseTestCase.php
tests/Unit/Core/Compiler/NodeConverterTest.php
tests/Unit/Core/Parser/SyntaxTree/ViewHelperNodeTest.php
tests/Unit/Core/Variables/StandardVariableProviderTest.php
tests/Unit/Core/ViewHelper/ViewHelperResolverTest.php
tests/Unit/View/AbstractViewTest.php
tests/Unit/View/Fixtures/AbstractViewTestFixture.php
tests/Unit/View/TemplatePathsTest.php

This asserter is used for whitebox tests.
The patch refactors usages to avoid whitebox
tests and deprecates the method.

[TASK] Avoid and deprecate assertAttributeEquals()

---

tests/Unit/Core/Cache/StandardCacheWarmerTest.php
tests/Unit/Core/Parser/SyntaxTree/AbstractNodeTest.php
tests/Unit/Core/Parser/TemplateParserTest.php
tests/Unit/View/TemplatePathsTest.php

Calling invoke() instead of invokeArgs()
on reflected methods is more easy to read.

[TASK] Prefer invoke() over invokeArgs() in tests

---

tests/Unit/Core/Compiler/AbstractCompiledTemplateTest.php
tests/Unit/Core/Compiler/Fixtures/AbstractCompiledTemplateTestFixture.php
tests/Unit/Core/Compiler/NodeConverterTest.php
tests/Unit/Core/Parser/TemplateParserTest.php
tests/Unit/Core/ViewHelper/Traits/Fixtures/ParserRuntimeOnlyFixture.php
tests/Unit/Core/ViewHelper/ViewHelperVariableContainerTest.php
tests/Unit/View/AbstractTemplateViewTest.php
tests/Unit/View/Fixtures/AbstractTemplateViewTestFixture.php
tests/Unit/View/Fixtures/AbstractViewTestFixture.php

phpunit 10.1 deprecated getMockForAbstractClass(). We rewrite a couple of tests to avoid it.

[TASK] Avoid getMockForAbstractClass()

---

src/Core/Parser/TemplateParser.php

$argumentDefinition is not used within the method
and can be removed. It's unclear if the call to
prepareArguments() is needed (no test fail when
removed), we'll keep it for now and add a @todo.

[TASK] Avoid unused variable in TemplateParser

---

src/Core/Compiler/NodeConverter.php

NodeConverter->convertArrayNode() is changed to
render more dense and easier readable PHP code
for arrays.
Also, NodeConverter is marked @internal since
it is pretty much directly bound to the node
based syntax tree created by TemplateParser,
and deep wired to TemplateCompiler.
Changing NodeConverter for anything important
would mean changing TemplateParser, TemplateCompiler and probably nodes as well. The most important
consumers Flow and TYPO3 don't do that.

[TASK] Simplify array representation in compiled templates

---

src/Core/Compiler/NodeConverter.php
tests/Unit/Core/Compiler/NodeConverterTest.php

Another small change for compiled templates
makes the compiled PHP code of BooleanNode
more easy to read.

[TASK] Improve readability of compiled BooleanNode

---

tests/Functional/ViewHelpers/IfThenElseViewHelperTest.php

See what happens when both an then argument
and an then child VH are given. Fine.
See what happens when both an else argument
and an else child VH are given, which leads
to different behavior in cached/non-cached
templates.

[TASK] More if VH test cases

---

phpstan-baseline.neon
src/Core/ViewHelper/AbstractConditionViewHelper.php

Inline private evaluateElseClosures() to renderStatic() to make it more easy to understand what is going on with all the else and elseif closure stuff.

[TASK] Inline private method in AbstractConditionViewHelper

---

tests/Functional/ViewHelpers/IfThenElseViewHelperTest.php

Add various test sets to IfThenElseViewHelperTest
to see which edge cases are broken. Streamline
the test set naming towards consistent naming.

[TASK] Test more if/then/else combinations

---

src/Core/ViewHelper/AbstractConditionViewHelper.php
tests/Functional/ViewHelpers/IfThenElseViewHelperTest.php

This fixes a bunch of f:if ViewHelper edge cases.
Most test cases have been established with previous patches already, inactive ones with issues on compiled templates are activated now.
Especially else and else if code edge cases are in line with non-compiled execution now.
The patch essentially rewrites the generated compiled PHP code, as well as its execution flow within
AbstractConditionViewHelper. The internal changes
to "__" prefixed arguments are not considered
breaking, TYPO3, Flow and other consumers should in general not suffer from this.
The patch adds just one further commented test set, but this is related to not-compiled templates and
will be sorted out with another patch.
Resolves: #769

[BUGFIX] Correct compiled f:if VH edge cases

---

src/Core/Parser/SyntaxTree/ArrayNode.php

The internal getter can be removed and
the property can be defined using
constructor property promotion.

[TASK] Clean up ArrayNode

---

phpstan-baseline.neon
src/Core/Parser/SyntaxTree/ViewHelperNode.php
src/Core/Parser/TemplateParser.php
tests/Unit/Core/Parser/SyntaxTree/ViewHelperNodeTest.php
tests/Unit/Core/ViewHelper/AbstractViewHelperTest.php

ViewHelperNode has an unused constructor argument
$parsingState. This is also not used in casual consumer and can be removed without further headaches. This seems to be an left over from early v2 development.

[TASK] Avoid dependency to ParsingState in ViewHelperNode

---

src/Core/Parser/SyntaxTree/BooleanNode.php

The protected property `BooleanNode::$node`
is never written or read and can be removed.
Type declaration for property `$stack` and
return type for `getStack()` can be be set
in non-breaking manner. Do it.
Other type declarations are added if safe
to do so.

[TASK] Cleanup BooleanNode

---

phpstan-baseline.neon
src/Core/Parser/SyntaxTree/EscapingNode.php

Since minimum php version raise we can now use native
typed properties. `EscapingNode` property  `$node` can
be safely set to `NodeInterface`.
This is ensured by the two possible ways to set this
property, the constructor and `addChildNode()`.
Used command(s):
```shell
vendor/bin/phpstan analyze --no-progress \
--generate-baseline=phpstan-baseline.neon
```

[TASK] Set native `$node` property type `NodeInterface` in EscapingNode

---

composer.json

Add all used checks and scripts from the
current GitHub Action workflow as defined
composer scripts. This helps during local
development.

[TASK] Add all CI scripts as composer scripts

---

src/Core/Parser/SyntaxTree/TextNode.php
tests/Unit/Core/Parser/SyntaxTree/TextNodeTest.php

Add all native type declarations to `TextNode`,
which are safe to be added.

[TASK] Cleanup `TextNode`

---

src/Core/Parser/SyntaxTree/ArrayNode.php
src/Core/Parser/SyntaxTree/BooleanNode.php
src/Core/Parser/SyntaxTree/EscapingNode.php
src/Core/Parser/SyntaxTree/Expression/CastingExpressionNode.php
src/Core/Parser/SyntaxTree/Expression/MathExpressionNode.php
src/Core/Parser/SyntaxTree/Expression/TernaryExpressionNode.php
src/Core/Parser/SyntaxTree/NumericNode.php
src/Core/Parser/SyntaxTree/ObjectAccessorNode.php
src/Core/Parser/SyntaxTree/RootNode.php
src/Core/Parser/SyntaxTree/TextNode.php
src/Core/Parser/SyntaxTree/ViewHelperNode.php

Concrete SyntaxTree node implementations can
be considered internal. Therefore, mark them
as such and add todo's to make them final.

[TASK] Mark SyntaxTree nodes as internal

---

phpstan-baseline.neon
src/Core/Parser/SyntaxTree/NodeInterface.php
src/Core/Parser/SyntaxTree/ViewHelperNode.php
src/Core/ViewHelper/AbstractViewHelper.php
src/Core/ViewHelper/ViewHelperInterface.php

This aims to solve a class structure issue that
makes various things more complicated than they
should be, and prevents fixing various issues
with compiled templates.
When a template is parsed, view helpers are
represented by the ViewHelperNode in the
syntax tree.
At compile time, ViewHelperNode creates the PHP
representation of a view helper in convert().
convert() now creates the "outer" stuff - it
takes care of VH argument representation and
of embedding compiled children. For the "inner"
stuff, the specific ViewHelper compile()
method is called.
Various ViewHelpers thus override compile():
For instance, f:comment returns an empty string,
since it does not want anything to be rendered.
ViewHelperNode convert() however still compiles
children and adds them to the output, even though …

[TASK] Move convert code from ViewHelperNode to VH

---

src/Core/Compiler/StopCompilingChildrenException.php
src/Core/ViewHelper/AbstractViewHelper.php
src/ViewHelpers/Cache/StaticViewHelper.php
src/ViewHelpers/Cache/WarmupViewHelper.php
tests/Unit/Core/Compiler/StopCompilingChildrenExceptionTest.php

As established with 1f1dc5ac, we can stubstitute
this exception with a more simple solution.

[TASK] Deprecate StopCompilingChildrenException

---

src/Core/Parser/SyntaxTree/BooleanNode.php
src/Core/ViewHelper/AbstractConditionViewHelper.php
src/ViewHelpers/IfViewHelper.php

The AbstractConditionViewHelper based VH's take
care of children on their own. There is no need
to have them within compiled PHP code a second
time.
The patch adds a custom convert() method to
AbstractConditionViewHelper that optimizes
the generated PHP code accordingly.
This has a huge impact especially on f:if with
large bodies in practice, generated compiled
template code can shrink by half in size.
Resolves: #771

[TASK] Optimize compiled code of condition VHs

---

src/ViewHelpers/CommentViewHelper.php
src/ViewHelpers/LayoutViewHelper.php
src/ViewHelpers/RenderViewHelper.php
src/ViewHelpers/SectionViewHelper.php
tests/Functional/ViewHelpers/CommentViewHelperTest.php

There are a couple of view helpers that never
render the body closure as such. Those still
create unused code within compiled templates.
We can shortcut compilation in these VH's a
bit to create smaller compiled templates.
The patch has a huge positive effect on
compiled templates sizes especially due
to the f:section change, which until now
contained the entire body of each section
within the files twice.
f:comment - Obviously, comments are never rendered. f:layout - Layouts are resolved at a different
level and the VH has no support for
different children.
f:section - Sections are resolved at a different
level and called via f:render. It's
compiled variant does not need to
take care of bodies itself.

[TASK] Optimize compiled code of some VHs

---

phpstan-baseline.neon
src/Core/Parser/SyntaxTree/ViewHelperNode.php
src/Core/Parser/TemplateParser.php

This method seems to be an artifact
of 15b94a1e: It has never been used
for anything.
We can remove it without further impact.

[TASK] Remove unused setPointerTemplateCode()

---

src/Core/Compiler/TemplateCompiler.php
src/Core/Parser/SyntaxTree/Expression/TernaryExpressionNode.php

The patch changes string representation in
TemplateCompiler and TernaryExpressionNode
to make both the code and the generated
template code better readable.

[TASK] Better readable TemplateCompiler

---

src/ViewHelpers/LayoutViewHelper.php

The method is obsolete since convert()
is overridden, which does not call
compile() anymore.

[TASK] Remove f:layout compile() method

---

phpstan-baseline.neon
src/Core/Parser/Interceptor/Escape.php
tests/Unit/Core/Parser/Interceptor/EscapeTest.php

This reverts commit a1d2da5d871d865db7a61cf0e48b1ca1446e6948.
The patch has side effects when the node being escaped is changed to an instance of EscapingNode, so especially the check
if (end($this->viewHelperNodesWhichDisableTheInterceptor) === $node) {
needs to be kept.
Reverts #715

Revert "[TASK] Improve performance of Escape interceptor (#716)"

---

src/Core/Parser/SyntaxTree/Expression/MathExpressionNode.php
tests/Unit/Core/Parser/SyntaxTree/Expression/MathExpressionNodeTest.php

[BUGFIX] Cast string values to float or int

---

src/Core/Parser/SyntaxTree/Expression/MathExpressionNode.php

This change requires https://github.com/TYPO3/Fluid/pull/773 to be merged first.
Fixes #777

[TASK] Improve type annotations for MathExpressionNode

---

phpstan-baseline.neon
src/Core/ViewHelper/AbstractConditionViewHelper.php
tests/Functional/ViewHelpers/IfThenElseViewHelperTest.php

Good: {f:if(condition:'{myVariable}',then: '1', else:'0')}
Bad:  {f:if(condition:'{myVariable}',then: 1, else:0)}
This is a regression of 2.9.0. The patch adds coverage and fixes the case.

[BUGFIX] Fix f:if inline syntax case

---

tests/Functional/Cases/Parsing/CommaToleranceTest.php

While this is probably covered by lower-level test, it can’t hurt to list all variants in one location, similar to the whitespace test case.
(see also Core issue: https://forge.typo3.org/issues/93933)

[TASK] Add test to cover commas in vh and arrays

---

phpstan-baseline.neon
src/Core/Parser/SyntaxTree/ViewHelperNode.php
tests/Functional/ViewHelpers/StaticCacheable/Fixtures/ExpectedOutput.html
tests/Functional/ViewHelpers/StaticCacheable/Fixtures/Partials/Result/Pagination.html
tests/Functional/ViewHelpers/StaticCacheable/Fixtures/Templates/Results.html
tests/Functional/ViewHelpers/StaticCacheable/Fixtures/ViewHelpers/CompilableViewHelper.php
tests/Functional/ViewHelpers/StaticCacheable/NotSharedStaticCompilableViewHelperTest.php
tests/Functional/ViewHelpers/StaticCacheable/SharedStaticCompilableViewHelperTest.php

Fluid have been designed without DependencyInjection
and therefore shared classes, for example ViewHelper,
in mind.
Using systems can implement custom ViewHelperResolvers
to determine how ViewHelper are resolved and created,
using custom configuration. For example, the TYPO3 CMS
implements such a custom ViewHelperResolver providing
the ability to instanciate them throug Symfony DI.
This allows shared ViewHelper instances now and may
become more likely, especial for custom ViewHelper
using the `CompileWithRenderStatic` trait.
ViewHelper and ViewHelperNodes are connected through
cycling references. This has not been a problem until
the execution code for `convert()` have been moved
from ViewHelperNode to the AbstractViewHelper (#787)
to avoid creating unnessesary children codes, which may …

[BUGFIX] Ensure correct `ViewHelperNode` in `ViewHelper`

---

.github/workflows/build.yml
composer.json

PHPUnit removed the `-v` cli argument
with 10.2.4 as a followup. That flag
was the short form for the --verbose
removed with 10.0 and did not had any
effect.
Due to the fact that no composer.lock
file is used, the newer version is
installed leading to failing tests.
This change raises the version of
PHPUnit and aligns the test calls
to avoid the removed cli argument.
Used command(s):
```shell
composer require --dev --no-update \
"phpunit/phpunit":"^10.2.6"
```

[TASK] Raise phpunit and align changes

---

src/Core/Compiler/AbstractCompiledTemplate.php
src/Core/Compiler/StopCompilingException.php
src/Core/Compiler/UncompilableTemplateInterface.php
src/Core/ErrorHandler/StandardErrorHandler.php
src/Core/Exception.php
src/Core/Parser/Exception.php
src/Core/Parser/ParsingState.php
src/Core/Parser/SyntaxTree/ArrayNode.php
src/Core/Parser/SyntaxTree/Expression/ExpressionException.php
src/Core/Parser/SyntaxTree/Expression/ParseTimeEvaluatedExpressionNodeInterface.php
src/Core/Parser/SyntaxTree/TextNode.php
src/Core/Parser/UnknownNamespaceException.php
src/Core/ViewHelper/AbstractViewHelper.php
src/Core/ViewHelper/Exception.php
src/Exception.php
src/View/Exception.php
src/View/Exception/InvalidSectionException.php
src/View/Exception/InvalidTemplateResourceException.php
src/View/TemplateView.php
tests/Functional/Fixtures/ViewHelpers/CompileWithContentArgumentAndRenderStaticExplicitSetArgumentNameForContentOverriddenResolveContentArgumentNameMethodViewHelper.php
tests/Unit/Core/Compiler/Fixtures/AbstractCompiledTemplateTestFixture.php
tests/Unit/Core/Fixtures/TestViewHelper2.php
tests/Unit/Core/Variables/Fixtures/StandardVariableProviderModelFixture.php
tests/Unit/Core/ViewHelper/Fixtures/RenderMethodFreeDefaultRenderStaticViewHelper.php
tests/Unit/View/Fixtures/AbstractTemplateViewTestFixture.php
tests/UnitTestCase.php

PER Coding Style 2.0, which fluid respects with its php-cs-fixer configuration, added a CGL rule to define empty classes, interfaces and functions in one line rather than each brace on its separate line. php-cs-fixer already enforces this, so this commit adjusts the existing code base.
Executed command:
composer cgl:fix

[TASK] Apply single_line_empty_body from PER-CS2.0

---

src/Core/Variables/StandardVariableProvider.php

StandardVariableProvider does not throw exceptions, contrary to the methods’ comments.

[TASK] Correct comments in StandardVariableProvider

---

src/Core/Variables/JSONVariableProvider.php
tests/Unit/Core/Variables/JSONVariableProviderTest.php

Currently, JSONVariableProvider doesn’t load the JSON file if getByPath() is used, in contrast to get(), getAll(), or getAllIdentifiers().

[BUGFIX] Load variables from file with getByPath

---

Documentation/Usage/Syntax.rst
src/Core/Variables/ScopedVariableProvider.php
src/Core/Variables/VariableProviderInterface.php
src/ViewHelpers/AliasViewHelper.php
tests/Functional/ViewHelpers/AliasViewHelperTest.php
tests/Unit/Core/Variables/ScopedVariableProviderTest.php

In its current implementation, the `f:alias` ViewHelper has side effects: It adds variables to the global variable container, which are not restored properly after the ViewHelper call. If a variable name is used as alias which already exists, that variable is unset after the ViewHelper call.
To resolve this, a new `ScopedVariableProvider` is introduced to handle local variables
inside ViewHelper calls properly. After the local scope, global variables are restored to their original value in case they existed. At the same time, other modifications to the variable provider inside the `f:alias` call, such as a call to `f:variable`, should still be persistent after the ViewHelper call. This ensures that the change is non-breaking for the vast majority of usages. The only situation where this …

[FEATURE] Proper support of local variables in ViewHelpers

---

src/Core/Parser/SyntaxTree/AbstractNode.php
tests/Unit/Core/Parser/SyntaxTree/AbstractNodeTest.php

`AbstractNode->castToString()` already checked for objects which could not
converted to a string representation due to missing `__toString()` method.
It's possible that the value could be an array, which per nature is not
really convertable to a string anyway. Older php versions simply converted
it to an `Array` string along with a notices, which has been raised to a
warning in newer PHP versions.
There is no way to properly convert an array, therefore the PHP warning
should always lead to an parser exception like for object not convertable.
This change now checks explicitly for an array and throws a corresponding
`TYPO3Fluid\Fluid\Core\Parser\Exception` with a meaningfull message.
Test is extended to cover this case.
Resolves: #826

[BUGFIX] Throw array conversion exception in `AbstractNode->castToString()`

---

src/ViewHelpers/ForViewHelper.php
tests/Functional/ViewHelpers/ForViewHelperTest.php

The previous implementation overwrote template variables with the same name as the specified ViewHelper parameters "as", "key", or "iteration". With the new implementation, the variable state before the ViewHelper call gets restored once the ViewHelper call is completed.

[BUGFIX] Eliminate side-effects from ForViewHelper

---

src/Core/Rendering/RenderingContext.php
src/Core/Rendering/RenderingContextInterface.php
tests/Unit/Core/Rendering/RenderingContextTest.php

This adds the ability to attach arbitrary attributes to the rendering context. All popular usages of Fluid out there extend the rendering context implementation of Fluid and don't actually implement the whole interface, so we should be able to change the interface as well.
As a result of this, TYPO3 CMS will be able to drop its own rendering context implementation, which will make the integration more straightforward.

[FEATURE] Attributes for RenderingContext

---

src/Core/Variables/ScopedVariableProvider.php
tests/Unit/Core/Variables/ScopedVariableProviderTest.php

The previous implementation of getScopedCopy() in the new ScopedVariableProvider copied both local and global variables. This is not necessary because all variables (except for settings) are provided explicitly and thus existing data in the data structure is irrelevant.
The new implementation reduces that unnecessary overhead by returning a StandardVariableProvider instead.

[BUGFIX] Fix memory overhead of getScopedCopy()

---

src/ViewHelpers/Format/JsonViewHelper.php
tests/Functional/ViewHelpers/Format/JsonViewHelperTest.php

JsonViewHelper doesn't have any dependencies to TYPO3, so it can be moved to Fluid Standalone.

[FEATURE] JsonViewHelper for StandaloneFluid

---

src/ViewHelpers/Format/Nl2brViewHelper.php
tests/Functional/ViewHelpers/Format/Nl2brViewHelperTest.php

Nl2brViewHelper doesn't have any dependencies to TYPO3, so it can be moved to Fluid Standalone.

[FEATURE] Nl2brViewHelper for StandaloneFluid

---

src/ViewHelpers/Format/UrlencodeViewHelper.php
tests/Functional/ViewHelpers/Format/UrlencodeViewHelperTest.php

UrlencodeViewHelper doesn't have any dependencies to TYPO3, so it can be moved to Fluid Standalone.

[FEATURE] UrlencodeViewHelper for StandaloneFluid

---

src/ViewHelpers/Format/NumberViewHelper.php
tests/Functional/ViewHelpers/Format/NumberViewHelperTest.php

NumberViewHelper doesn't have any dependencies to TYPO3, so it can be moved to Fluid Standalone.

[FEATURE] NumberViewHelper for StandaloneFluid

---

src/ViewHelpers/Format/StripTagsViewHelper.php
tests/Functional/ViewHelpers/Format/StripTagsViewHelperTest.php

StripTagsViewHelper doesn't have any dependencies to TYPO3, so it can be moved to Fluid Standalone.

[FEATURE] StripTagsViewHelper for StandaloneFluid

---

Documentation/Usage/Syntax.rst
src/Core/Variables/ScopedVariableProvider.php
tests/Functional/ViewHelpers/ForViewHelperTest.php
tests/Unit/Core/Variables/ScopedVariableProviderTest.php

The default behavior of the newly introduced local and global variable scopes has been that existing local variables are preferred over global variables if both exist. While this makes sense in general, if a local variable gets overwritten by a VariableViewHelper, this value couldn't be used in the local context because the local variable still had its old value.
This change makes sure that both the local and the global variable get the new value. This eliminates the described inconsistencies when using a name of a local variable for a global variable.
Resolves #846

[BUGFIX] Explicitly set variables should override local variables

---

src/Core/Variables/ScopedVariableProvider.php
tests/Unit/Core/Variables/ScopedVariableProviderTest.php

With the previous implementation of ScopedVariableProvider, variables that contained arrays or object structures could behave incorrectly in a scoped context. When accessing a object path in a fluid template (e. g. myVar.subKey), the value of that "sub variable" was considered for the decision which variable (global or local) should be used.
This behavior is incorrect, only the "primary" variable name should determine if a local variable is set or not (and should fall back to a global variable). This would mean that a non-existing sub value in a local variable would trigger a fallback to the global variable.
This change restores the correct behavior: Only the "primary" variable name is checked initially. If the variable exists in the local variables, those will be used, even if the …

[BUGFIX] Choose global/local variable based on primary identifier

---

src/ViewHelpers/IfViewHelper.php

We can't easily link to https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ApiOverview/Fluid/Syntax.html due to versioning, so the auto-generated code is updated to reflect some more implementation details.
Also some rephrasing to make things easier to read (hopefully ;)).

[DOCS] Clarify IfViewHelper usage

---

src/Core/ViewHelper/TagBuilder.php
tests/Unit/Core/ViewHelper/TagBuilderTest.php

TagBuilder::addAttribute() allows both strings and array/traversables as attribute value. However, in the implementation only "data" and "aria" are properly handled as arrays. For other attribute names, this leads to a type conversion warning.
With this patch, that edge case is properly handled with an exception. Also, test coverage is added both for data/aria and the exception.
Resolves: #857

[BUGFIX] Prevent php warning when passing array as tag attribute

---

src/ViewHelpers/SplitViewHelper.php
tests/Functional/ViewHelpers/SplitViewHelperTest.php

This patch adds a new <f:format.split> ViewHelper to Fluid Standalone. It is named "split" instead of "explode" to be consistent with the naming of JavaScript.
The ViewHelper aims to support everything that TYPO3's utility functions "GeneralUtility::intExplode()" and
"GeneralUtility::trimExplode()" provide.
* items in the resulting array can be trimmed of whitespace
* items in the resulting array can be converted to integers
* empty items in the resulting array can be removed
* the "limit" option behaves similar to PHP's explode() behavior
In a following patch, its counterpart "join" will be added.

[FEATURE] SplitViewHelper

---

src/ViewHelpers/ReplaceViewHelper.php
tests/Functional/Fixtures/Various/ArrayAccessExample.php
tests/Functional/Fixtures/Various/IterableExample.php
tests/Functional/ViewHelpers/ReplaceViewHelperTest.php

The ReplaceViewHelper replaces one or multiple strings with other strings. This ViewHelper mimicks PHP's :php:`str_replace()` function. However, it's also possible to provide replace pairs as associative array via the "replace" argument.
Replace a single string:
```xml
<f:replace value="Hello World" search="World" replace="Fluid" /> 
```
Replace multiple strings:
```xml
<f:replace value="Hello World" search="{0: 'World', 1: 'Hello'}" replace="{0: 'Fluid', 1: 'Hi'}" /> 
```
Replace multiple strings using associative array:
```xml
<f:replace value="Hello World" replace="{'World': 'Fluid', 'Hello': 'Hi'}" /> 
```

[FEATURE] ReplaceViewHelper

---

src/ViewHelpers/JoinViewHelper.php
tests/Functional/ViewHelpers/JoinViewHelperTest.php
tests/Functional/ViewHelpers/ReplaceViewHelperTest.php

The JoinViewHelper combines elements from an array into a single string. You can specify both a general separator and a special one for the last element that is rendered between the elements.
```html
<f:join value="{0: '1', 1: '2', 2: '3'}" />   
```
Results in the output:
```html
123
```
```html
<f:join value="{0: '1', 1: '2', 2: '3'}" separator=", " />
```
Results in the output:
```html
1, 2, 3
```
```html
<f:join value="{0: '1', 1: '2', 2: '3'}" separator=", " separatorLast=" and " />
```
Results in the output:
```html
1, 2 and 3
```

[FEATURE] JoinViewHelper

---

src/ViewHelpers/FirstViewHelper.php
src/ViewHelpers/LastViewHelper.php
tests/Functional/ViewHelpers/FirstViewHelperTest.php
tests/Functional/ViewHelpers/LastViewHelperTest.php

The FirstViewHelper and LastViewHelper return the first or last item of a specified array, respectively.
```xml
<f:first value="{0: 'first', 1: 'second', 2: 'third'}" /> 
<f:last value="{0: 'first', 1: 'second', 2: 'third'}" /> 
```

[FEATURE] ViewHelpers to return first/last item of an array

---

examples/src/CustomVariableProvider.php
src/Core/Compiler/TemplateCompiler.php
src/View/AbstractTemplateView.php
src/View/TemplatePaths.php
tests/Functional/AbstractFunctionalTestCase.php
tests/Unit/View/TemplatePathsTest.php

64bit xxh3 hash is significantly quicker. This is a micro optimization especially when creating hashes from template contents for caching.

[TASK] Use xxh3 instead of sha1

---

src/Core/ViewHelper/AbstractTagBasedViewHelper.php
src/Core/ViewHelper/AbstractViewHelper.php
tests/Functional/Cases/TagBasedTest.php
tests/Functional/Fixtures/ViewHelpers/TagBasedTestViewHelper.php

A previous optimation broke the ability to use arbitrary
ViewHelper attributes in TagBasedViewHelpers that start with
aria-* and data-*. This patch re-implements this functionality.
A following patch will allow all arbitrary attributes for
TagBasedViewHelpers. This is a pre-patch to fix the existing
regression in Fluid.

[BUGFIX] Re-enable arbitrary aria- and data- arguments

---

src/Core/ViewHelper/AbstractTagBasedViewHelper.php
tests/Functional/Cases/Escaping/ViewHelperEscapingTest.php
tests/Functional/Cases/TagBasedTest.php
tests/Functional/Fixtures/ViewHelpers/TagBasedTestViewHelper.php
tests/Unit/Core/ViewHelper/AbstractTagBasedViewHelperTest.php

Tag based ViewHelpers can now receive arbitrary arguments which
will be added to the resulting HTML tag automatically. This offers
a much more readable option compared to the "additionalAttributes"
argument, which is still available for tag based ViewHelpers. Also,
both "data" and "aria" arguments are still available to supply multiple
data or aria attributes as an array.
As a result of this change, the following methods of
AbstractTagBasedViewHelper are deprecated and will be removed
with the next major version of Fluid:
* registerUniversalTagAttributes(): The method is now a no-op since
all previously registered universal attributes can now be used without
registration.
* registerTagAttribute(): The method still has the same functionality
since it also supports the required flag as well …

[FEATURE] Allow arbitrary arguments for TagBasedViewHelper

---

bin/fluid
src/Tools/ConsoleRunner.php

The fluid binary currently only supports one command: The execution of fluid code, supplied by various sources, like a file, interactively or via socket. To be able to add more features in the future, a command parameter has been introduced to differentiate various sub-commands.
The existing functionality is now available as a sub-command by executing "bin/fluid run". However, the "run" command is defined as default command in this first step, which means that the previous syntax still works and that this change should be non-breaking.
Since ConsoleRunner has been defined as @internal, it has been marked as final, also the visibility of methods, variables and constants has been set to private to reduce/clarify the API of the class.

[TASK] Prepare fluid binary to support multiple commands

---

src/Core/ViewHelper/AbstractTagBasedViewHelper.php
tests/Functional/Cases/TagBasedTest.php
tests/Functional/Fixtures/ViewHelpers/OverrideUniversalAttributeTestViewHelper.php

With the introduction of arbitrary attributes for TagBasedViewHelpers, the predefined universal tag attributes have been removed, since they will be added to the resulting HTML tag without any additional configuration. However, there are cases (vhs does this) where those global attributes are overridden by a concrete ViewHelper implementation. To make the change non-breaking, we restore those pre-defined attributes for now and remove them with the next major version of Fluid.

[BUGFIX] Allow override of universal attributes

---

src/ViewHelpers/ConstantViewHelper.php
tests/Functional/Fixtures/Various/BackedEnumExample.php
tests/Functional/Fixtures/Various/ClassConstantsExample.php
tests/Functional/Fixtures/Various/EnumExample.php
tests/Functional/ViewHelpers/ConstantViewHelperTest.php

This commit adds the `f:constant` ViewHelper allowing to use native PHP constants and enums in Fluid context.
Fixes: #873

[FEATURE] Add f:constant ViewHelper

---

composer.json

Fluid standalone devs should rely on the calls
performed by GH workflows. It is a burden to
keep composer scripts in sync.

[TASK] Avoid composer 'scripts' and 'scripts-descriptions'

---

tests/Functional/Cases/Conditions/BasicConditionsTest.php
tests/Unit/Core/Parser/BooleanParserTest.php
tests/Unit/Core/Parser/SyntaxTree/BooleanNodeTest.php

[TASK] Avoid pre PHP 8.0 code switches

---

src/ViewHelpers/ConstantViewHelper.php

The attribute in `ConstantViewHelper` is called `name`, but the documentation references it as `value`. This PR fixes the examples in the documentation.

[BUGFIX] Correct attribute name in ConstantViewHelper example

---

.php-cs-fixer.dist.php
src/Core/Parser/TemplateParser.php
src/Core/ViewHelper/ViewHelperInvoker.php
src/View/AbstractTemplateView.php
tests/Unit/Core/Variables/ChainedVariableProviderTest.php
tests/Unit/Core/ViewHelper/AbstractViewHelperTest.php

Implicit nullable method parameters are deprecated with PHP 8.4. The patch prepares affected method
signatures and activates an according php-cs-fixer rule.

[TASK] Avoid implicitly nullable method parameter

---

src/Core/ViewHelper/AbstractTagBasedViewHelper.php
src/ViewHelpers/FirstViewHelper.php
src/ViewHelpers/ForViewHelper.php
src/ViewHelpers/Format/CaseViewHelper.php
src/ViewHelpers/Format/TrimViewHelper.php
src/ViewHelpers/JoinViewHelper.php
src/ViewHelpers/LastViewHelper.php
src/ViewHelpers/ReplaceViewHelper.php
tests/Functional/ViewHelpers/StaticCacheable/Fixtures/ViewHelpers/CompilableViewHelper.php

$required defaults to 'false' and does not need
to be set explicitly when there are no further
non-default arguments.

[TASK] Avoid registerArgument() with required=false

---

src/Core/Parser/Patterns.php
src/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php
tests/Functional/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessorTest.php

One way to make custom ViewHelpers available in Fluid templates is to define them as xml namespaces. Fluid parses `<html>` tags in templates, extracts all XML namespaces relevant to Fluid and removes them from the resulting HTML output.
XML namespaces by convention are usually named as URIs. However, they are actually not "callable" URLs but rather unique identifiers. Thus, there is only one valid way to reference Fluid namespaces as xml namespaces: By using the following schema:
```
http://typo3.org/ns/$Vendor/$Package/ViewHelpers/
```
Using https instead of http is invalid. Previously, Fluid namespaces defined with https instead of http were ignored and kept in the resulting output. Now, we catch this bug in templates and throw an exception instead to make tempate authors aware that …

[!!!][TASK] Throw exception for https namespaces

---

Documentation/Changelog/2.x.rst
src/Core/ViewHelper/AbstractViewHelper.php
tests/Unit/Core/ViewHelper/AbstractViewHelperTest.php

Previously, `overrideArgument()` needed to be used to override an existing ViewHelper argument. With this change, `registerArgument()` no longer throws an exception if an argument with the same name already exists. This simplifies the ViewHelper API.
Since it is no longer necessary with this change, `overrideArgument()` is now deprecated.

[TASK] Allow registerArgument() to override arguments

---

Documentation/Changelog/4.x.rst
examples/src/CustomViewHelperResolver.php
phpstan-baseline.neon
src/Core/ViewHelper/AbstractViewHelper.php
src/Core/ViewHelper/ArgumentDefinition.php
src/Core/ViewHelper/TagBuilder.php
src/Core/ViewHelper/ViewHelperInvoker.php
src/Core/ViewHelper/ViewHelperResolver.php
src/Core/ViewHelper/ViewHelperVariableContainer.php
tests/Functional/Fixtures/Various/TestViewHelperResolver.php
tests/Functional/ViewHelpers/StaticCacheable/SharedStaticCompilableViewHelperTest.php
tests/Unit/Core/ViewHelper/AbstractViewHelperTest.php
tests/Unit/Core/ViewHelper/ViewHelperVariableContainerTest.php

With v4 of Fluid, the goal is to not break any custom ViewHelpers out there. Thus, we only apply type hints to ViewHelper-related API for cases where we can be reasonably sure that it won't break ViewHelpers.
AbstractViewHelper is extended directly by custom ViewHelpers, so we can only type hint private properties.
ViewHelperInvoker and ViewHelperResolver are APIs that are implemented by frameworks that use Fluid for templating, so stricter types don't affect ViewHelper implementations. Still, there are some cases in which we won't enforce types because it is unclear if there are edge cases out there where the supplied types actually match existing PHPDOC annotations. For example, we can't really be sure if templates or ViewHelpers always return strings, so we stay away from those type …

[TASK] Introduce type hints to ViewHelper-related API

---

Documentation/Changelog/2.x.rst
Documentation/Development/Implementation.rst
examples/example_cachestatic.php
examples/example_cachewarmup.php
examples/example_conditions.php
examples/example_customresolving.php
examples/example_dynamiclayout.php
examples/example_errorhandling.php
examples/example_escapingmodifier.php
examples/example_format.php
examples/example_layoutless.php
examples/example_math.php
examples/example_multiplepaths.php
examples/example_namespaceresolving.php
examples/example_namespaces.php
examples/example_passthrough.php
examples/example_single.php
examples/example_structures.php
examples/example_variableprovider.php
examples/example_variables.php
examples/src/Helper/ExampleHelper.php
phpstan-baseline.neon
src/Tools/ConsoleRunner.php
src/View/AbstractTemplateView.php
src/ViewHelpers/RenderViewHelper.php
tests/Functional/Cases/Escaping/ViewHelperEscapingTest.php
tests/Functional/Cases/Rendering/DataAccessorTest.php
tests/Functional/Cases/TagBasedTest.php
tests/Unit/View/AbstractTemplateViewTest.php

In order to simplify integrations of the Fluid template engine into frameworks (such as TYPO3), we deprecate four methods of AbstractTemplateView that are only shortcuts to the rendering context object.
These methods will be removed in Fluid v4 because the migration path is easy and it simplifies further work on TYPO3's Fluid integration.

[TASK] Deprecate shortcut methods in AbstractTemplateView

---

Documentation/Changelog/2.x.rst
Documentation/Development/Implementation.rst
examples/example_cachestatic.php
examples/example_cachewarmup.php
examples/example_conditions.php
examples/example_customresolving.php
examples/example_dynamiclayout.php
examples/example_errorhandling.php
examples/example_escapingmodifier.php
examples/example_format.php
examples/example_layoutless.php
examples/example_math.php
examples/example_multiplepaths.php
examples/example_namespaceresolving.php
examples/example_namespaces.php
examples/example_passthrough.php
examples/example_single.php
examples/example_structures.php
examples/example_variableprovider.php
examples/example_variables.php
examples/src/Helper/ExampleHelper.php
phpstan-baseline.neon
src/Tools/ConsoleRunner.php
src/View/AbstractTemplateView.php
src/ViewHelpers/RenderViewHelper.php
tests/Functional/Cases/Escaping/ViewHelperEscapingTest.php
tests/Functional/Cases/Rendering/DataAccessorTest.php
tests/Functional/Cases/TagBasedTest.php
tests/Unit/View/AbstractTemplateViewTest.php

In order to simplify integrations of the Fluid template engine into frameworks (such as TYPO3), we deprecate four methods of AbstractTemplateView that are only shortcuts to the rendering context object.
These methods will be removed in Fluid v4 because the migration path is easy and it simplifies further work on TYPO3's Fluid integration.

[TASK] Deprecate shortcut methods in AbstractTemplateView (#920)

---

src/Core/Rendering/RenderingContext.php
src/Core/Rendering/RenderingContextInterface.php
tests/Unit/Core/Rendering/RenderingContextTest.php

When we designed the RenderingContext functionality to add "arbitrary" objects to RenderingContext
(like a Request) in a recent minor release, we tried start making RenderingContext immutable and added
the implementation using a "with'er".
This is in general a good idea: RenderinContext
*should* be immutable.
It is however problematic to do this with this
single property: It leads to too many and
partially breaking changes when consumers try
to use this.
As such, the patch rolls back to a setAttribute()
approach. With the default implementation being
done in the Fluid delivered RenderingContext,
this change is currently not considered breaking
since no (known) consumer actually uses it.
To make RenderingContext immutable, we need a new
approach, maybe re-starting with a new class that …

[TASK] Use RenderingContext->setAttribute()

---

src/Core/Rendering/RenderingContext.php
src/Core/Rendering/RenderingContextInterface.php
tests/Unit/Core/Rendering/RenderingContextTest.php

When we designed the RenderingContext functionality to add "arbitrary" objects to RenderingContext
(like a Request) in a recent minor release, we tried start making RenderingContext immutable and added
the implementation using a "with'er".
This is in general a good idea: RenderinContext
*should* be immutable.
It is however problematic to do this with this
single property: It leads to too many and
partially breaking changes when consumers try
to use this.
As such, the patch rolls back to a setAttribute()
approach. With the default implementation being
done in the Fluid delivered RenderingContext,
this change is currently not considered breaking
since no (known) consumer actually uses it.
To make RenderingContext immutable, we need a new
approach, maybe re-starting with a new class that …

[TASK] Use RenderingContext->setAttribute() (#922)

---

Documentation/Changelog/4.x.rst
src/View/AbstractTemplateView.php
tests/Unit/View/AbstractTemplateViewTest.php

The following constants represent internal Fluid state and have been
set to `protected`. Thus, they can only be accessed by `AbstractTemplateView` and its child implementations:
:php:`TYPO3Fluid\Fluid\View\AbstractTemplateView::RENDERING_TEMPLATE`
:php:`TYPO3Fluid\Fluid\View\AbstractTemplateView::RENDERING_PARTIAL`
:php:`TYPO3Fluid\Fluid\View\AbstractTemplateView::RENDERING_LAYOUT`

[!!!][TASK] Mark internal constants as protected

---

Documentation/Changelog/4.x.rst
src/View/AbstractTemplateView.php

These methods have been marked as deprecated in Fluid 2.14 and are now removed.

[!!!][TASK] Remove deprecated methods in AbstractTemplateView

---

src/Core/Variables/JSONVariableProvider.php

This line has been changed several times, but was probably never correct: Either set the second parameter of json_decode() to true to get an associative array or set the flag JSON_OBJECT_AS_ARRAY as fourth parameter.
We opt for the second parameter to keep things simple

[BUGFIX] Supply correct parameter to json_decode

---

src/Core/Variables/JSONVariableProvider.php

This line has been changed several times, but was probably never correct: Either set the second parameter of json_decode() to true to get an associative array or set the flag JSON_OBJECT_AS_ARRAY as fourth parameter.
We opt for the second parameter to keep things simple

[BUGFIX] Supply correct parameter to json_decode (#928)

---

src/Core/ViewHelper/ViewHelperVariableContainer.php
src/ViewHelpers/FirstViewHelper.php
src/ViewHelpers/ForViewHelper.php
src/ViewHelpers/JoinViewHelper.php
src/ViewHelpers/LastViewHelper.php
src/ViewHelpers/ReplaceViewHelper.php

Since Fluid now requires at least PHP 8.2, we can simplify some calls to iterator_to_array(). Before PHP 8.2, the function could only handle iterator objects as argument, now also arrays are supported. We can remove some compatibility code which made sure that no arrays were passed to the function.

[TASK] Simplify calls to iterator_to_array()

---

examples/src/CustomVariableProvider.php
phpstan-baseline.neon
src/Core/Cache/FluidCacheInterface.php
src/Core/Cache/FluidCacheWarmerInterface.php
src/Core/Cache/FluidCacheWarmupResult.php
src/Core/Cache/SimpleFileCache.php
src/Core/Cache/StandardCacheWarmer.php
src/Core/ErrorHandler/ErrorHandlerInterface.php
src/Core/ErrorHandler/StandardErrorHandler.php
src/Core/ErrorHandler/TolerantErrorHandler.php
src/Core/Variables/ChainedVariableProvider.php
src/Core/Variables/JSONVariableProvider.php
src/Core/Variables/ScopedVariableProvider.php
src/Core/Variables/StandardVariableProvider.php
src/Core/Variables/VariableProviderInterface.php
src/Tools/ConsoleRunner.php

More type hints are applied in the following areas:
* ConsoleRunner
* Cache interface and implementations
* Cache warmup interface and implementations
* Variable providers
* Error handlers
While these changes are breaking, they shouldn't affect the vast majority of users,
since in most cases the Fluid implementations of the affected interfaces are used.

[!!!][TASK] Apply more type hints

---

src/View/ViewInterface.php

Add proper type hints to the two arguments
in ViewInterface->assign(). This is not
breaking since existing implementations can
still accept "more" by not setting these
arguments - method arguments of subtypes
are contravariant. This will be backported
to 2.14.

[TASK] Type hint arguments in ViewInterface

---

src/View/AbstractTemplateView.php
src/View/AbstractView.php
src/View/ViewInterface.php

Add proper type hints to the two arguments
in ViewInterface->assign(). This is not
breaking since existing implementations can
still accept "more" by not setting these
arguments - method arguments of subtypes
are contravariant. This will be backported
to 2.14.

[TASK] Type hint arguments in ViewInterface (#933)

---

examples/example_mvc.php

The word `used` was written twice in the explanatory comment section of `example_mvc.php`. This tiny PR removes it and reformats the lines accordingly.

[DOCS] Remove duplicate word

---

src/Core/ViewHelper/AbstractTagBasedViewHelper.php
tests/Functional/Cases/TagBasedTest.php

With Fluid 2.12, we introduced the ability to provide arbitrary
ViewHelper arguments to TagBasedViewHelpers. Consequently,
we deprecated the method registerTagAttribute(), which is no
longer necessary due to the mentioned change.
However, the implementations differed until now: The previous
implementation ignored empty strings for tag attributes, while
the new implementation added such input as empty attribute
to the resulting tag. We now check for empty strings and only
add attributes to the tag if it's not an empty string.
This will be backported to Fluid 2.14.

[BUGFIX] Restore previous empty tag attribute behavior

---

phpstan-baseline.neon
src/Core/Compiler/AbstractCompiledTemplate.php
src/Core/Compiler/TemplateCompiler.php
src/Core/Parser/ParsedTemplateInterface.php
src/Core/Parser/ParsingState.php
tests/Functional/Fixtures/Various/ParsedTemplateImplementationFixture.php
tests/Unit/Core/Cache/FluidCacheWarmupResultTest.php
tests/Unit/Core/Parser/TemplateParserTest.php

This patch adds type hints to the template compiler and associated classes, such as parsed/compiled templates and the parsing state. A few adjustments in test cases are necessary because of excessive mocking of internal functionality. In some cases, types were used in mock implementations that don't actually exist in real world use, these are now adjusted when necessary.
Note that these changes require all cached templates to be regenerated because type hints need to be added to the generated classes as well. Because of this, the patch has been marked as breaking.

[!!!][TASK] Add type hints to template compiler

---

src/Core/Parser/SyntaxTree/ObjectAccessorNode.php
src/Core/Variables/InvalidVariableIdentifierException.php
src/Core/Variables/StandardVariableProvider.php
tests/Unit/Core/Parser/SyntaxTree/ObjectAccessorNodeTest.php
tests/Unit/Core/Variables/StandardVariableProviderTest.php

This patch enhances Fluid's capabilities of dealing with booleans and null significantly. Previously, the actual booleans `false` and `true` could be only created from within inline syntax or if a ViewHelper argument was defined as boolean (in which case strings were parsed as boolean). `null` values couldn't really be created at all. Now, there exist standard variables for true, false, and null, which can be used in all contexts.
This patch is marked as breaking because it disallows the usage of the variable names `true`, `false` and `null` in variable providers.

[!!!][FEATURE] Boolean and Null literals

---

src/Core/Variables/StandardVariableProvider.php

These variable names are no longer available in Fluid v4 because boolean literals will become part of the language.

[TASK] Trigger deprecation if true/false/null variable is used

---

src/Core/ViewHelper/AbstractTagBasedViewHelper.php
src/Core/ViewHelper/TagBuilder.php
tests/Functional/Cases/TagBasedTest.php
tests/Functional/Fixtures/ViewHelpers/TagBasedTestViewHelper.php
tests/Unit/Core/ViewHelper/TagBuilderTest.php

TagBasedViewHelpers now have proper support for boolean attributes.
Before this change, it was very cumbersome to generate these with Fluid,
now it's implemented similar to popular JavaScript frameworks:
```
<my:viewhelper async="{true}" />
Result: <tag async="async" />
<my:viewhelper async="{false}" />
Result: <tag />
<my:viewhelper async="{null}" />
Result: <tag />
```
This can also be used in combination with variable casting:
```
<my:viewhelper async="{myString as boolean}" />
```
For compatibility reasons empty strings still lead to the attribute
being omitted from the tag. This might change in the future, however
we don't want to break templates now. ViewHelpers can define
an argument manually and implement the desired behavior in the
render method (this is how the ImageViewHelper …

[FEATURE] Support for boolean tag attributes

---

tests/Functional/ViewHelpers/IfThenElseViewHelperTest.php
tests/Unit/Core/Parser/BooleanParserTest.php

As this is a more complicated issue, we first provide test cases and disable them for now.
Related issue: #533

[TASK] Add non-working test cases for BooleanParser

---

phpstan-baseline.neon
src/View/AbstractTemplateView.php
src/View/AbstractView.php
src/View/ViewInterface.php

The previous type hint suggested that View objects only return strings. However, this is not the case. For example, if a View only contains a ViewHelper call without any other strings (like whitespace), the view might return any type the ViewHelper returns, such as an object or an array.

[TASK] Views return arbitrary types

---

phpstan-baseline.neon
src/ViewHelpers/Format/HtmlspecialcharsViewHelper.php

For now, we only correct the invalid type hint here because the class is also used internally by Fluid.

[TASK] Clarify return type of HtmlspecialcharsViewHelper

---

phpstan-baseline.neon
src/Core/Compiler/TemplateCompiler.php

TemplateCompiler::get() might also return an
UncompilableTemplateInterface.

[BUGFIX] Use correct return type for TemplateCompiler::get()

---

src/Core/Parser/SyntaxTree/Expression/MathExpressionNode.php
tests/Unit/Core/Parser/SyntaxTree/Expression/MathExpressionNodeTest.php

The parser of MathExpressionNode already allowed whitespace before
or after an expression. However, ExpressionNodes are only executed
if their `$detectionExpression` evaluates to true. This was not the case
for leading/trailing whitespace, which is why the regular expression is
extended to allow this.
Unfortunately, the test did only evaluate the parser but did not check
the regular expression beforehand. As there is no API for this (the
regular expression is the API and is executed directly in
`TemplateParser::textAndShorthandSyntaxHandler()`, we execute
the regex manually in the test as well. One existing test case is
removed because it never was actually supported.
In the future, we probably should implement a proper API for this.

[BUGFIX] Allow leading/trailing whitespace in math expression

---

src/ViewHelpers/CountViewHelper.php
src/ViewHelpers/Format/CdataViewHelper.php
src/ViewHelpers/Format/PrintfViewHelper.php
src/ViewHelpers/Format/RawViewHelper.php
src/ViewHelpers/InlineViewHelper.php
src/ViewHelpers/OrViewHelper.php
src/ViewHelpers/VariableViewHelper.php

`CompileWithContentArgumentAndRenderStatic` exists to simplify
a common use case of ViewHelpers: A ViewHelper should be
callable both with an argument and with its child content.
Example:
```
<f:variable name="myVar" value="my value" />
<f:variable name="myVar">my value</f:variable>
```
This can also be helpful with Fluid's inline syntax:
```
{f:format.json(value: myObject)}
{myObject -> f:format.json()}
```
While this feature is very useful, the trait also offers a more
confusing feature: If the "content argument name" isn't defined
explicitly, it will try to guess that name by going through all
defined ViewHelper arguments and pick the first optional
argument.
This is unnecessary magic behavior, which will be removed in
the future. As preparation for that, we define the content argument …

[TASK] Set content argument name explicitly in ViewHelpers

---

Documentation/Changelog/2.x.rst
Documentation/Changelog/4.x.rst
src/Core/ViewHelper/AbstractViewHelper.php
src/Core/ViewHelper/Traits/CompileWithContentArgumentAndRenderStatic.php
src/Core/ViewHelper/Traits/CompileWithRenderStatic.php
src/ViewHelpers/CountViewHelper.php
src/ViewHelpers/Format/CdataViewHelper.php
src/ViewHelpers/Format/JsonViewHelper.php
src/ViewHelpers/Format/Nl2brViewHelper.php
src/ViewHelpers/Format/PrintfViewHelper.php
src/ViewHelpers/Format/RawViewHelper.php
src/ViewHelpers/Format/StripTagsViewHelper.php
src/ViewHelpers/Format/UrlencodeViewHelper.php
src/ViewHelpers/InlineViewHelper.php
src/ViewHelpers/OrViewHelper.php
src/ViewHelpers/VariableViewHelper.php
tests/Functional/Core/ViewHelper/ContentArgumentNameTest.php
tests/Functional/Core/ViewHelper/Traits/CompileWithContentArgumentAndRenderStaticTest.php
tests/Functional/Fixtures/ViewHelpers/ContentArgumentNameViewHelper.php

Previously, `CompileWithContentArgumentAndRenderStatic` could
be used to create ViewHelpers that can get their default input both
from their child content and from a defined argument. This feature
has now been integrated into AbstractViewHelper. To use it, the
ViewHelper class needs to override the method
`resolveContentArgumentName()` and return the name of the
argument to be used.
Example:
```
public function initializeArguments(): void
{
$this->registerArgument('value', 'string', '');
}
public function resolveContentArgumentName(): string
{
return 'value';
}
```
`$this->renderChildren()` can then be used to get either the
defined argument or as fallback the ViewHelper's child content.
With this definition, the ViewHelper can be used in the following
ways:
```
<my:viewhelper …
```

[FEATURE] Provide contentArgument API to all ViewHelpers

---

src/Core/ViewHelper/TagBuilder.php
tests/Functional/Cases/Escaping/ViewHelperEscapingTest.php
tests/Unit/Core/ViewHelper/TagBuilderTest.php

The current approach to sanitize HTML tag attributes by
TagBuilder can be improved to only allow certain characters.
As TagBuilder is a low-level API to create arbitrary HTML tags,
the goal is not to prevent any JavaScript from being executed
because this might be a desired behavior in some use cases.
We would like to prevent the following:
```php
$unsafeInput = "onclick='alert(1)'";
$tagBuilder->addAttribute($unsafeInput, 'some value');
```
While still allowing the following:
```php
$tagBuilder->addAttribute('onclick', 'doSomething()');
```
Thus, this patch applies a strict allow-list to argument names
and throws an exception if any other characters are used.
The characters are limited to ASCII characters except for
select characters that are problematic in HTML attributes,
such as …

[BUGFIX] Improved argument validation in TagBuilder (#937)

---

tests/Functional/AbstractFunctionalTestCase.php
tests/Functional/ViewHelpers/ForViewHelperTest.php

The cache is now removed between each test case, not between
each test class. This also unveiled one interference between two
`ForViewHelper` test cases.
Further interference is still present due to Fluid's runtime cache.
This is now documented in #975 to be fixed later.

[BUGFIX] Prevent interference between functional tests

---

src/Core/ViewHelper/AbstractViewHelper.php

It has long been possible to render recursive templates with Fluid,
either by using partials or sections. In both cases, `<f:render />`
is used to initiate the recursive behavior.
For example, the following template creates a recursive main menu by
using sections:
```xml
<f:render section="menu" arguments="{items: mainMenu}" />
<f:section name="menu">
<ul>
<f:for each="{items}" as="item">
<li>
{item.title}
<f:if condition="{item.children}">
<f:render section="menu" arguments="{items: item.children}" />
</f:if>
</li>
</f:for>
</ul>
</f:section>
```
However, this was only working because `ForViewHelper` was
implemented as static ViewHelper by using Fluid's trait
`CompileWithRenderStatic`. The trait changed Fluid's handling
of ViewHelpers in a way that variables stay consistent even
during …

[BUGFIX] Properly restore renderingContext in renderChildren()

---

phpstan-baseline.neon
src/Core/Parser/SyntaxTree/ViewHelperNode.php
src/Core/ViewHelper/AbstractViewHelper.php
src/Core/ViewHelper/ViewHelperInterface.php

In the past, some ViewHelper API methods that were used by Fluid
internally were only part of `AbstractViewHelper`, which lead to
either `method_exists()` checks or phpstan warnings in the baseline.
With this change, the `ViewHelperInterface` becomes the internal
API definition for ViewHelpers, only to be used by Fluid internally.
Thus, missing API methods are added to the interface, while
user-facing API only used by `AbstractViewHelper` has been
removed.
In the future, we might consider adding a separate interface for the
used-facing API of ViewHelpers. For now we highly recommend
to keep using `AbstractViewHelper` as the basis for all custom
ViewHelper implementations.

[!!!][TASK] Extend ViewHelperInterface to cover current API

---

src/Core/ViewHelper/AbstractViewHelper.php

It has long been possible to render recursive templates with Fluid, either by using partials or sections. In both cases, `<f:render />` is used to initiate the recursive behavior.
For example, the following template creates a recursive main menu by using sections:
```xml
<f:render section="menu" arguments="{items: mainMenu}" />
<f:section name="menu">
<ul>
<f:for each="{items}" as="item">
<li>
{item.title}
<f:if condition="{item.children}">
<f:render section="menu" arguments="{items: item.children}" />
</f:if>
</li>
</f:for>
</ul>
</f:section>
```
However, this was only working because `ForViewHelper` was implemented as static ViewHelper by using Fluid's trait `CompileWithRenderStatic`. The trait changed Fluid's handling of ViewHelpers in a way that variables stay consistent even during …

[BUGFIX] Properly restore renderingContext in renderChildren() (#970)

---

src/View/AbstractTemplateView.php

Partials and sections can (of course) return anything, as can any template.

[TASK] Annotate correct type hints in AbstractTemplateView

---

src/View/AbstractTemplateView.php

Partials and sections can (of course) return anything, as can any template.

[TASK] Annotate correct type hints in AbstractTemplateView (#986)

---

Documentation/Changelog/2.x.rst
Documentation/Changelog/4.x.rst
src/Core/ViewHelper/AbstractViewHelper.php
src/Core/ViewHelper/Traits/CompileWithRenderStatic.php
src/Core/ViewHelper/ViewHelperInterface.php
tests/Functional/ViewHelpers/GroupedForViewHelperTest.php
tests/Functional/ViewHelpers/StaticCacheable/Fixtures/ViewHelpers/CompilableViewHelper.php
tests/Functional/ViewHelpers/StaticCacheable/SharedStaticCompilableViewHelperTest.php
tests/Unit/Core/ViewHelper/AbstractViewHelperTest.php

Until now it was best practice to differentiate between object-based
ViewHelpers, using the object method `render()` as their primary render
method, and static ViewHelpers, using the static method `renderStatic()`.
This distinction has been introduced to Fluid mainly for performance reasons:
With earlier PHP versions it was quite expensive performance-wise to create a
new ViewHelper object for each ViewHelper call. However, PHP's performance
characteristics for objects have changed quite a bit with newer versions,
which questions the usefulness of this performance optimization nowadays.
Our performance tests have shown that the performance gains are still existent
today if you compare `renderStatic()` to `render()` ViewHelpers, especially
if no further optimizations are applied to Fluid's …

[TASK] Use render() as primary ViewHelper method

---

Documentation/Changelog/2.x.rst
src/Core/ViewHelper/AbstractViewHelper.php
src/Core/ViewHelper/Traits/CompileWithContentArgumentAndRenderStatic.php
src/Core/ViewHelper/Traits/CompileWithRenderStatic.php

Both the trait `CompileWithRenderStatic` and ViewHelpers implementing
`renderStatic()` without using one of the deprecated traits will be deprecated
with Fluid v4 and will no longer work with v5.
ViewHelpers should use `render()` as their primary rendering method.
Related: #983

[TASK] Deprecate CompileWithRenderStatic and renderStatic()

---

Documentation/Usage/Syntax.rst

I've updated the section on inline syntax and added some more (real-life) examples.
And I've added the available casting types to the section on expression nodes.

[DOCS] Improve section about inline syntax

---

examples/example_multiplepaths.php
src/Tools/ConsoleRunner.php
src/View/TemplatePaths.php
tests/Unit/View/TemplatePathsTest.php

Ever since Fluid has been extracted from TYPO3, there has been some
TYPO3-specific code in TemplatePaths. This patch removes some of
these code paths and the remaining usages in Fluid itself.
Simultaneously, TemplatePaths in TYPO3 13 has been adjusted accordingly.
Soft-deprecations will be backported to Fluid v2 to let users know in
advance that these methods or constants will no longer be available in
the future.

[TASK] Deprecate TYPO3-specific code in TemplatePaths

---

tests/Functional/Core/Rendering/NamespaceInheritanceTest.php
tests/Functional/Fixtures/Layouts/NamespaceInheritanceLayout.html
tests/Functional/Fixtures/Partials/NamespaceInheritanceNestedPartial.html
tests/Functional/Fixtures/Partials/NamespaceInheritancePartial.html

This is an ugly workaround to prevent the interfering runtime
cache until #975 is resolved. Currently, subsequent test cases
are successful even if the rendering is modified to not inherit
ViewHelper namespaces to sub templates because they
re-use the "in-memory" template classes from previous tests.
As there is currently no way to configure this, we need to use
the ugly f:cache.disable ViewHelper in the affected template
to get robust testing results.

[TASK] Prevent template compilation in inheritance test

---

src/Schema/ViewHelperFinder.php

There are cases when errors occur on iterating through the installed view helpers. The generation of the XSDs then break hard with an exception. Currently, this occurs with the TYPO3 extension "schema".
Now, these errors are catched and collected. A calling script can get and display these errors. This way, the generation of XSDs is not cancelled, but proceed without the erroneous view helpers.
This is especially useful for the TYPO3 command "fluid:schema:generate".
Related: #1005

[TASK] Catch errors in schema generation and collect them

---

src/Schema/ViewHelperFinder.php

If a PHP namespace is defined in composer.json, but the
referenced directory doesn't exist, ViewHelperFinder
produced a PHP error. With this change, nonexistent
directories are skipped.

[BUGFIX] Skip nonexistent namespace paths

---

src/View/TemplateAwareViewInterface.php

Currently, the actual View instance in fact doesn't always
return a string for `render()`. We should change this in
the future, but for now the interface should represent the
actual implementation.

[TASK] Adjust interface type hint to match current implementation

---

tests/Functional/ViewHelpers/GroupedForViewHelperTest.php

The test case produced inconsistent results depending on the default timezone of the php setup.

[TASK] Stabilize test by specifying timezone

---

phpstan-baseline.neon
src/Core/ViewHelper/AbstractConditionViewHelper.php
src/Core/ViewHelper/AbstractViewHelper.php
tests/Functional/ViewHelpers/IfThenElseViewHelperTest.php

A f:if ViewHelper that contains else-if ViewHelpers and also sets the else attribute behaved differently for cached and uncached templates. With this change, uncached templates now behave just like cached templates.
This can be validated by temporarily commenting out the second test execution code in IfThenElseViewHelperTest::render(). This testing setup issue should also be fixed in the future, but this is out of scope for the specific issue.

[BUGFIX] Ensure consistent handling of else-if ViewHelpers

---

src/Core/ViewHelper/AbstractConditionViewHelper.php

If a f:if ViewHelper contains multiple f:else ViewHelpers, cached templates chose the first else node, while uncached templates chose the last one. This patch restores consistent behavior by adjusting the code for uncached templates.
This can be validated by temporarily commenting out the second test execution code in IfThenElseViewHelperTest::render(). This testing setup issue should also be fixed in the future, but this is out of scope for the specific issue. A follow-up patch will fix a similar issue.

[BUGFIX] Ensure consistent handling of multiple f:else

---

Documentation/Usage/ViewHelpers.rst
src/Core/ViewHelper/AbstractConditionViewHelper.php
tests/Functional/ViewHelpers/IfThenElseViewHelperTest.php

ViewHelpers that don't specify any then or else clause in any of the accepted syntax variants now directly return the result of the condition.
Previously, this syntax was not supported and a no-op resulting in an empty string. Thus, this is not considered a breaking change, but an enhancement of the existing behavior.

[FEATURE] ViewHelpers without then/else return verdict

---

Documentation/Index.rst
Documentation/Usage/ViewHelpers.rst
Documentation/guides.xml

Like other official manuals the Fluid Explained manual has an explicit shortcode, 'fluid' to be used during linking. 
Using the composer key does not work as this manual is not displayed as extension, so the paths are different.
Additionally use standard shortcodes where possible
Please backport if possible

[BUGFIX] Use correct interlink code for Fluid docs

---

src/Schema/SchemaGenerator.php
tests/Unit/Schema/SchemaGeneratorTest.php

The phpDoc annotation "@see" contains valuable information for the XSD schema generation for future reading.
Even though some IDEs like PHPStorm will not expose these links as being clickable, they can be copied+pasted from a tooltip in the IDE, and opened in the browser (instead of needing to find and open a PHP classfile to get to that link).
Some IDEs (eclipse?) seem to be able to parse a HTML subset for annotations, so maybe this will find future adoption (or markdown rendering might get available). Since also neither ReST nor Markdown is parsed in the XSD element `xsd:documentation` by PHPStorm either.... plaintext it is!

[TASK] Add SchemaGenerator evaluation for "@see"

---

src/Core/ViewHelper/AbstractConditionViewHelper.php
tests/Functional/ViewHelpers/IfThenElseViewHelperTest.php

This partially reverts 3084952: Now all condition-based ViewHelpers use
`null` as default return value instead of `''` because this is more
consistent when `then` or `else` returns `null`, for example if a
non-existent variable is used there:
```
{f:if(condition: true, then: nonExistingVariable)}
```
This should return `null`, but now returns `''`. Note that this change
is only a pre-patch, a follow-up will actually achieve the desired
behavior from that example.
For all other use-cases, this change shouldn't be a problem because
`null` will be converted to `''` anyways.

[BUGFIX] Use null instead of empty string as default for condition VHs

---

phpstan-baseline.neon
src/Core/Compiler/TemplateCompiler.php
src/Core/Parser/SyntaxTree/ViewHelperNode.php
src/Core/ViewHelper/AbstractConditionViewHelper.php
tests/Functional/ViewHelpers/IfThenElseViewHelperTest.php

With Fluid 4.1 (in 96099a6ba60bcb6a73187d289a781903a05882e3) it became possible to
use `f:if` and other condition-based ViewHelpers without `then` or `else`, which
would return the result of the condition as boolean. However, the current
implementation of this feature didn't consider the difference between a ViewHelper
without any `then` or `else` and one with `then` that returns `null`. These two
examples would both return the boolean:
```
{f:if(condition: myCondition, then: myUndefinedVariable)}
{f:if(condition: myCondition)}
```
With this change, the two examples are treated differently. Instead of checking
the arguments of the ViewHelper (which are already merged with the defined
default values), the ViewHelperNode is used to find out if the argument has
actually been specified. This …

[BUGFIX] Differentiate between null and unset then/else condition branches

---

src/Core/Parser/SyntaxTree/ViewHelperNode.php

This method hasn't been used since before the extraction of Fluid
from TYPO3 core. It is marked as internal and isn't used by any
extension in TYPO3 TER nor by any of the known Fluid extensions
or integrations.

[TASK] Remove obsolete method from ViewHelperNode

---

src/Core/Parser/TemplateParser.php

As suspected in the todo annotation, this call is obsolete: In the next line,
`$this->parseArguments()` is called, which calls
`ViewHelperResolver::getArgumentDefinitionsForViewHelper()` in its first
line, which then calls (and returns the result of `prepareArguments()`.

[TASK] Remove obsolete prepareArguments() call

---

tests/Functional/Core/ViewHelper/ViewHelperArgumentTypesTest.php

stdClass should in fact throw an exception if it's used as a scalar
argument value, so these test cases are obsolete.

[TASK] Remove commented-out test cases

---

Documentation/Changelog/4.x.rst
src/Core/Parser/Patterns.php
src/Core/ViewHelper/ViewHelperResolver.php
tests/Unit/Core/ViewHelper/ViewHelperResolverTest.php

Both `resolvePhpNamespaceFromFluidNamespace()` and
`isNamespaceValidOrIgnored()` are deprecated to be removed with
Fluid 5. Also, since this was the only usage of the constant
`Patterns::NAMESPACESUFFIX`, it is depreacted as well.

[TASK] Deprecate unused methods in ViewHelperResolver

---

Documentation/Changelog/4.x.rst
src/Core/ViewHelper/AbstractViewHelper.php
src/Core/ViewHelper/ArgumentProcessorInterface.php
src/Core/ViewHelper/LenientArgumentProcessor.php
src/Core/ViewHelper/ViewHelperInvoker.php
tests/Functional/Core/ViewHelper/ViewHelperArgumentTypesTest.php
tests/Unit/Core/ViewHelper/AbstractViewHelperTest.php
tests/Unit/Core/ViewHelper/LenientArgumentProcessorTest.php

Fluid allows ViewHelpers to specify their API by using
`AbstractViewHelper::registerArgument()`, which is usually called in
`initializeArguments()` of the ViewHelper. Internally, `ArgumentDefinition`
is used to represent the provided argument information and constraints.
Among those is the ability to specify the type of an argument as well
as if the argument should be a required argument.
While the required status is already validated at the parser level, the
argument types are validated by the ViewHelper implementation. However,
in most cases, Fluid's built-in validation method by `AbstractViewHelper`
is used. Unfortunately, this implementation has many flaws:
* it only covers a subset of possible types (e. g. it covers "boolean", but
not "bool")
* It doesn't ensure the correct argument …

[FEATURE] Introduce ArgumentProcessor API

---

Documentation/Changelog/4.x.rst
phpstan-baseline.neon
src/Core/Parser/TemplateParser.php
src/Core/ViewHelper/AbstractViewHelper.php
src/Core/ViewHelper/ViewHelperNodeInitializedEventInterface.php
src/ViewHelpers/LayoutViewHelper.php
src/ViewHelpers/SectionViewHelper.php
tests/Functional/Core/ViewHelper/ViewHelperEventsTest.php
tests/Functional/Fixtures/ViewHelpers/NodeInitializedEventViewHelper.php
tests/Functional/Fixtures/ViewHelpers/PostParseEventViewHelper.php

In the current implementation, there already exists a "postParseEvent"
method which allows ViewHelpers to hook into the rendering process.
This is currently used by the f:layout ViewHelper to set the template's
layout. It is also used by the f:section ViewHelper to collect all sections
within a template. Currently, both implementation use the variable
container to transport that information to the compiler and the renderer,
which will then interpret that data.
While it makes sense to provide a generic way to transport data to
allow third-parties to extend Fluid, both cases described above are part
of Fluid's core functionality. Thus, we should aim to append that data
directly to the `ParsingState` instead of using magic strings as variable
names. This patch creates a new event, which has …

[FEATURE] Introduce new nodeInitializedEvent for ViewHelpers

---

src/Core/ViewHelper/StrictArgumentProcessor.php
tests/Unit/Core/ViewHelper/StrictArgumentProcessorTest.php

The `StrictArgumentProcessor` is a stricter variant to the newly
introduced `LenientArgumentProcessor`. This patch only contributes
the implementation of the argument processor itself, without
actually using it in the code.
The plan is to use the new strict processor for upcoming new
features and to switch the existing ViewHelper implementation
to the stricter variant with Fluid v5. There probably will also be
an API to provide alternative implementations to Fluid in the
future once the `StrictArgumentProcessor` is used across
the whole code.

[FEATURE] StrictArgumentProcessor

---

src/Core/Compiler/FailedCompilingState.php
src/Core/Compiler/UncompilableTemplateInterface.php
src/Core/Parser/ParsedTemplateInterface.php
src/Core/Parser/ParsingState.php

The most relevant class `AbstractCompiledTemplate` is already
internal, so are both the `TemplateParser` and the `TemplateCompiler`,
so it makes sense to apply this to related classes/interfaces as well.

[TASK] Mark internal parser classes as internal

---

src/Core/ViewHelper/StrictArgumentProcessor.php
tests/Unit/Core/ViewHelper/StrictArgumentProcessorTest.php

The `StrictArgumentProcessor` now supports PHP's built-in
types `iterable`, `countable` and `callable`. This is already
helpful for template arguments, but will be even more relevant
once ViewHelpers switch to the `StrictArgumentProcessor`,
as it can simplify argument validation code in the `render()`
method.
Resolves: #1066

[FEATURE] Extend StrictArgumentProcessor with more types

---

tests/Functional/Core/Rendering/NamespaceInheritanceTest.php
tests/Functional/Fixtures/Layouts/NamespaceInheritance/CallPartial.html
tests/Functional/Fixtures/Layouts/NamespaceInheritance/CallSection.html
tests/Functional/Fixtures/Layouts/NamespaceInheritance/CallViewHelper.html
tests/Functional/Fixtures/Layouts/NamespaceInheritance/DefineNamespaceCallPartial.html
tests/Functional/Fixtures/Layouts/NamespaceInheritance/DefineNamespaceCallSection.html
tests/Functional/Fixtures/Layouts/NamespaceInheritanceLayout.html

This expands our test cases for the more obscure feature
of namespace inheritance, which is due to be deprecated
and removed. It allowed partials to access ViewHelpers
by "reusing" the import from their parent template.
The tests now cover more use cases and should also be
more reliable with cached templates.

[TASK] Make namespace inheritance tests more consistent

---

Documentation/Changelog/4.x.rst
src/Core/Compiler/TemplateCompiler.php
src/Core/Parser/TemplateParser.php
src/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php
src/Core/Rendering/RenderingContext.php
src/Core/ViewHelper/InheritedNamespaceException.php
src/Core/ViewHelper/ViewHelperResolver.php
src/View/AbstractTemplateView.php
tests/Functional/Core/Rendering/NamespaceInheritanceTest.php
tests/Functional/Core/ViewHelper/ViewHelperEscapingTest.php
tests/Functional/Fixtures/Layouts/NamespaceInheritance/CallPartialInlineSyntax.html
tests/Functional/Fixtures/Layouts/NamespaceInheritance/CallViewHelperInlineSyntax.html
tests/Functional/Fixtures/Partials/NamespaceInheritanceNestedPartial.html
tests/Functional/Fixtures/Partials/NamespaceInheritanceNestedPartialInlineSyntax.html
tests/Functional/Fixtures/Partials/NamespaceInheritancePartial.html
tests/Functional/Fixtures/Partials/NamespaceInheritancePartialInlineSyntax.html
tests/Unit/View/AbstractTemplateViewTest.php

Fluid v5 will no longer support inheritance of ViewHelper namespaces
from a template to its layout or partials. Namespace must either be
added globally (by using the public `ViewHelperResolver` API) or
by using the `{namespace x=…}` or `xmlns:x="…"` syntax in the
template file that uses the ViewHelper.
This patch prepares the removal of this feature by implementing
separate namespace collections for global, local and inherited
ViewHelper namespaces. Depending on the context, ViewHelpers
will be added to the appropriate collection. When a ViewHelper
is called, the different collections will be checked for a matching
namespace. Also, contexts get their own `ViewHelperResolver`
instances to isolate them properly.
If a namespace is only defined in a parent template, but not in
the template …

[TASK] Deprecate ViewHelper namespace inheritance

---

src/Core/ViewHelper/ViewHelperResolver.php

With the current API, it is possible to provide `null` as array item to the various ViewHelper APIs, which now is documented with the appropriate annotations.

[TASK] Clarify current namespace types

---

src/Core/ViewHelper/UnresolvableViewHelperException.php
src/Core/ViewHelper/ViewHelperCollection.php
src/Core/ViewHelper/ViewHelperResolver.php
src/Core/ViewHelper/ViewHelperResolverDelegateInterface.php
tests/Functional/Core/ViewHelper/ViewHelperResolverDelegateTest.php
tests/Functional/Fixtures/Various/TestViewHelperResolverDelegate.php
tests/Functional/Fixtures/ViewHelpers/TestViewHelperResolverDelegate/Render.php
tests/Functional/Fixtures/ViewHelpers/TestViewHelperResolverDelegate/Render_Sub.php
tests/Unit/Core/ViewHelper/ViewHelperResolverTest.php

It has always been possible to set a custom `ViewHelperResolver` for
Fluid in the rendering context. One major use case was (and still is)
to use a custom ViewHelper factory or dependency injection. However,
because there can only be one `ViewHelperResolver`, it becomes quite
hard to extend/adjust Fluid's ViewHelper resolving (= which class should
handle which ViewHelper call in a template) to special needs.
With the introduction of ViewHelperResolver delegates, the main
ViewHelperResolver can delegate the actual resolving within a
namespace to a custom implementation. This means that the logic
behind `<f:format.trim>` and `<my:custom>` can now be
different: Class names can have a different structure, and it's no longer
strictly necessary to have one ViewHelper class per ViewHelper. The …

[FEATURE] Introduce ViewHelperResolver delegates

---

Documentation/Changelog/4.x.rst
src/Core/Parser/SyntaxTree/ViewHelperNode.php
src/Core/ViewHelper/AbstractViewHelper.php
src/Core/ViewHelper/ViewHelperInterface.php

Currently, the raw parser nodes are provided twice to each
ViewHelper instance: Once with `setViewHelperNode()` and
once with `setChildNodes()`. The latter is now deprecated,
together with the property `$childNodes`, since it can easily
be subsituted like this within a ViewHelper:
before:
```php
$this->childNodes
```
after:
```php
$this->viewHelperNode->getChildNodes()
```

[TASK] Deprecate childNodes property for ViewHelpers

---

src/Core/Parser/SyntaxTree/ViewHelperNode.php

`ViewHelperNode` now has getters for the namespace and the name
of the ViewHelper tag. This allows for more flexibility in ViewHelper
compilation code and is necessary for the "reusable components"
feature.

[TASK] Add namespace/name getters to ViewHelperNode

---

phpstan-baseline.neon
src/Core/Parser/SyntaxTree/ViewHelperNode.php
src/Core/Parser/TemplateParser.php

The main responsibility of the Fluid parser is to create a tree of
`NodeInterface` instances from a template string. However, it
also performs another task: It pre-validates the supplied
arguments to ViewHelpers. If a certain argument is required,
but not supplied in the template, processing of that template
already fails in the parsing step. Also, if arguments are supplied
to a ViewHelper which have not been registered, the
`validateAdditionalArguments()` method of the ViewHelper is
called in the parsing step. It is also possible to modify the
escaping behavior for each ViewHelper, which is applied
by the parser as well.
In order to achieve that, the ViewHelper instance needs to be
created at parse time already to obtain its argument definitions.
However, this poses a problem in the …

[TASK] Improve ViewHelperNode creation in parser

---

src/Core/ViewHelper/StrictArgumentProcessor.php
tests/Unit/Core/ViewHelper/StrictArgumentProcessorTest.php

The recently introduced `StrictArgumentProcessor` didn't process
boolean arguments because it relied on the `BooleanParser` being
performed during template parsing. However, this is not the case
for templates being rendered directly from PHP:
```php
$myView->assign('booleanArgument', 1);
$myView->render('myTemplate');
```
This change assures that the `1` will be interpreted as valid boolean,
which is consistent with the other scalar types.

[BUGFIX] Attempt to cast boolean arguments

---

src/Core/Parser/TemplateParser.php
tests/Functional/Core/Parser/ViewHelperNamespacesTest.php

The current `TemplateParser` has separate code paths for the
inline and the tag-based ViewHelper syntax. While the actual
rendering is consistent in the end, the handling of parsing
errors is quite different. This patch performs two related
changes to the parsing algorithm of inline ViewHelpers:
1. Support Ignored ViewHelper Namespaces
The `ViewHelperResolver` has the option to ignore certain
ViewHelper namespaces, which leads to the parser ignoring
them completely and returning the uncompiled ViewHelper
code as-is. The original intent of this feature seems to be that
it should be possible to use XML namespaces within a Fluid
template, without the Fluid parser messing with the tags.
For inline ViewHelpers this never worked, which makes
kind of sense, since there is no overlapping syntax …

[TASK] Consistent parser error handling for inline ViewHelpers

---

composer.json
tests/Functional/Core/ViewHelper/ViewHelperResolverDelegateTest.php
tests/Unit/Core/Parser/TemplateProcessor/EscapingModifierTemplateProcessorTest.php

PHP 8.3 and 8.4 tests now use phpunit v12.
Fix two data providers the more strict
phpunit v12 found.
composer req --dev \
phpstan/phpstan:^2.1.17 \
phpunit/phpunit:"^11.5.22 || ^12.2.1" \
phpstan/phpstan-phpunit:^2.0.6

[TASK] Bump dev dependencies

---

.github/CONTRIBUTING.md

This commit adds an initial set of contribution guidelines to the Fluid project. These guidelines enable new contributors to see a quick summary of required steps to make a contribution and information on the local development setup and tooling that makes it possible to work on Fluid.
It has been chosen to add these guidelines as a Markdown file in `.github/CONTRIBUTING.md` to
support the GitHub feature that makes new contributors aware of existing Guidelines when creating a Pull Request.

[TASK] Add Contribution Guidelines

---

src/Core/Parser/Interceptor/Escape.php
src/Core/ViewHelper/AbstractViewHelper.php
src/ViewHelpers/Format/HtmlspecialcharsViewHelper.php

A code search both for "HtmlspecialcharsViewHelper" and "htmlspecialchars" confirmed that the ViewHelper is no longer used internally for escaping. Instead, the `EscapingNode` executes `htmlspecialchars()` directly on the string, both in uncached and cached context.
The `@todo` in `HtmlspecialcharsViewHelper` is removed without changing the return type though, because this would require a breaking change to the ViewHelper's internal behavior.

[TASK] Clarify code comments related to escaping

---

src/Core/Parser/Interceptor/Escape.php
src/Core/ViewHelper/AbstractViewHelper.php
src/ViewHelpers/Format/HtmlspecialcharsViewHelper.php

A code search both for "HtmlspecialcharsViewHelper" and "htmlspecialchars" confirmed that the ViewHelper is no longer used internally for escaping. Instead, the `EscapingNode` executes `htmlspecialchars()` directly on the string, both in uncached and cached context.
The `@todo` in `HtmlspecialcharsViewHelper` is removed without changing the return type though, because this would require a breaking change to the ViewHelper's internal behavior.

[TASK] Clarify code comments related to escaping (#1151)

---

src/Core/ViewHelper/StrictArgumentProcessor.php
tests/Unit/Core/ViewHelper/LenientArgumentProcessorTest.php
tests/Unit/Core/ViewHelper/StrictArgumentProcessorTest.php

Got this error:
> The argument "file" for template "Default_action_ContentElements_rte_only_templates_frontend_3a0ee286e27afc95" is registered with type "TYPO3\CMS\Core\Resource\FileInterface", but the provided value is of type "TYPO3\CMS\Core\Resource\File".
This fix makes it possible to use interfaces as typed arguments for components.

[BUGFIX] allow usage of interfaces in StrictArgumentProcessor

---

src/ViewHelpers/ArgumentViewHelper.php
tests/Functional/Fixtures/Layouts/LayoutWithArgumentDefinitions.html
tests/Functional/Fixtures/Partials/PartialWithArgumentDefinitions.html
tests/Functional/Fixtures/Templates/TemplateWithArgumentDefinitions.html
tests/Functional/ViewHelpers/ArgumentViewHelperTest.php

If `<f:argument>` is used with the `default` argument, it is now assumed that the argument is optional without specifying `optional="{true}"`.
Resolves: #1149

[TASK] Treat f:argument with default value as optional (#1150)

---

src/Core/ViewHelper/StrictArgumentProcessor.php
tests/Unit/Core/ViewHelper/LenientArgumentProcessorTest.php
tests/Unit/Core/ViewHelper/StrictArgumentProcessorTest.php

A typed array, e.g.: string[] doesn't allow an empty array [] as value until now.
reset() returns false instead of null, that results in the array being invalid.

[BUGFIX] empty array is now valid as typed array (#1139)

---

src/ViewHelpers/AliasViewHelper.php
src/ViewHelpers/Cache/DisableViewHelper.php
src/ViewHelpers/Cache/StaticViewHelper.php
src/ViewHelpers/Cache/WarmupViewHelper.php
src/ViewHelpers/CaseViewHelper.php
src/ViewHelpers/CommentViewHelper.php
src/ViewHelpers/CountViewHelper.php
src/ViewHelpers/CycleViewHelper.php
src/ViewHelpers/DebugViewHelper.php
src/ViewHelpers/DefaultCaseViewHelper.php
src/ViewHelpers/ElseViewHelper.php
src/ViewHelpers/ForViewHelper.php
src/ViewHelpers/Format/CdataViewHelper.php
src/ViewHelpers/Format/HtmlspecialcharsViewHelper.php
src/ViewHelpers/Format/JsonViewHelper.php
src/ViewHelpers/Format/PrintfViewHelper.php
src/ViewHelpers/Format/RawViewHelper.php
src/ViewHelpers/Format/TrimViewHelper.php
src/ViewHelpers/GroupedForViewHelper.php
src/ViewHelpers/IfViewHelper.php
src/ViewHelpers/InlineViewHelper.php
src/ViewHelpers/LayoutViewHelper.php
src/ViewHelpers/OrViewHelper.php
src/ViewHelpers/RenderViewHelper.php
src/ViewHelpers/SectionViewHelper.php
src/ViewHelpers/SpacelessViewHelper.php
src/ViewHelpers/SwitchViewHelper.php
src/ViewHelpers/ThenViewHelper.php
src/ViewHelpers/VariableViewHelper.php
tests/Functional/Fixtures/ViewHelpers/MutableTestViewHelper.php

In preparation for more type hints in `ViewHelperInterface` and
abstract classes, non-critical type hints are added to all existing
ViewHelper classes. These include:
* return types for `initializeArguments()` and `render()`
* parameter and return types for internal methods
Even though these changes most certainly aren't breaking, we
still apply them to v5 only, just to be sure. In follow-up patches,
the abstract classes will get more type hints (e. g. for properties),
which will require (!) changes to the ViewHelpers and thus will
be breaking changes.

[TASK] Add non-critical type hints to ViewHelper classes

---

tests/Functional/Core/Rendering/NamespaceInheritanceTest.php
tests/Functional/ViewHelpers/StaticCacheable/SharedStaticCompilableViewHelperTest.php

The underlying tests have already been changed in previous patches to not trigger deprecations.

[TASK] Remove obsolete IgnoreDeprecations attribute

---

Documentation/Changelog/4.x.rst
examples/Resources/Private/Singles/Namespaces.html
src/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php
tests/Functional/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessorTest.php

There are two main syntax variants to import a ViewHelper namespace
in a template:
```
{namespace my=Vendor\MyPackage\ViewHelpers}
<html xmlns:my="http://typo3.org/ns/Vendor/MyPackage/ViewHelpers" data-namespace-typo3-fluid="true">
```
The second variant is mainly used/preferred because it provides
autocompletion for ViewHelpers in supporting IDEs. However, a
third variant is implemented, which mixes the two variants:
```
<html xmlns:my="Vendor\MyPackage\ViewHelpers" data-namespace-typo3-fluid="true">
```
This doesn't make much sense because it neither provides
autocompletion nor is it valid XML syntax because it's
not a valid URL.
This patch deprecates that syntax variant, which will no longer
work in Fluid v5.
Resolves: #1019

[TASK] Deprecate unknown VH namespace syntax

---

Documentation/Changelog/5.x.rst
src/Core/ViewHelper/AbstractTagBasedViewHelper.php

`registerUniversalTagAttributes()` and `registerTagAttribute()`
have been deprecated with Fluid 2.12 and are now removed.

[!!!][TASK] Remove deprecated methods from tag-based VH

---

Documentation/Changelog/5.x.rst
src/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php
tests/Functional/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessorTest.php

Remove this namespace syntax variant:
```
<html xmlns:my="Vendor\MyPackage\ViewHelpers" data-namespace-typo3-fluid="true">
```
These are kept:
```
{namespace my=Vendor\MyPackage\ViewHelpers}
<html xmlns:my="http://typo3.org/ns/Vendor/MyPackage/ViewHelpers" data-namespace-typo3-fluid="true">
```
Related: #1079

[!!!][TASK] Remove wildly unknown VH namespace syntax

---

src/Core/ViewHelper/AbstractViewHelper.php

Currently, the ViewHelper validation API calls the internal ViewHelper API to obtain its argument definitions for validation. However, the proper way is to use the `ViewHelperResolver`, since it is possible to redefine certain argument definitions there.
This is demonstrated and tested by the `CustomViewHelperResolver` in the examples. However, this example only worked until now because of the lenient validation implementation of ViewHelpers.

[BUGFIX] Call proper API to obtain ViewHelper API

---

tests/Unit/Core/Fixtures/TestViewHelper.php

The ViewHelper is called with a `string`, but the argument is declared as `integer`.

[BUGFIX] Address bug in test ViewHelper

---

src/Core/ViewHelper/AbstractViewHelper.php

Currently, the ViewHelper validation API calls the internal ViewHelper API to obtain its argument definitions for validation. However, the proper way is to use the `ViewHelperResolver`, since it is possible to redefine certain argument definitions there.
This is demonstrated and tested by the `CustomViewHelperResolver` in the examples. However, this example only worked until now because of the lenient validation implementation of ViewHelpers.

[BUGFIX] Call proper API to obtain ViewHelper API (#1199)

---

src/Core/ViewHelper/StrictArgumentProcessor.php

If a component or ViewHelper argument is not required and is not
supplied in the ViewHelper call, Fluid takes care of filling in the
default value. But this also happens if the argument is supplied and
is set to `NULL`. This usually happens if an undefined variable is
provided to the ViewHelper. For ViewHelpers this is done by the
`ViewHelperInvoker`, for components in
`AbstractTemplateView::processAndValidateTemplateVariables()`.
The current implementation of `StrictArgumentProcessor` prevents the
fallback from happening if the argument is supplied, but with `NULL`
as value. This patch adjusts the `StrictArgumentProcessor` to also
pass `NULL` values through.

[BUGFIX] Allow NULL for optional arguments with default

---

src/Core/ViewHelper/AbstractViewHelper.php

The method is never called or referenced. Also, there don't
seem to be any usages of 3rd-party packages.

[TASK] Remove unused resetState() method

---

src/Core/Parser/TemplateParser.php
src/Core/Variables/StandardVariableProvider.php
src/Core/ViewHelper/ViewHelperVariableContainer.php
src/ViewHelpers/GroupedForViewHelper.php
tests/Unit/Core/Variables/StandardVariableProviderTest.php
tests/Unit/Core/ViewHelper/ViewHelperVariableContainerTest.php

This patch addresses various deprecations that were introduced in
recent dev versions of PHP 8.5. All changes should be non-breaking
and thus can be backported to Fluid v4.
* `TemplateParser` now uses empty strings instead of `null` as array
key for runtime cache. Public API will be adjusted in v5 only.
* `StandardVariableProvider` and `ViewHelperVariableContainer` use
`__serialize()` instead of `__sleep()` for serialization.
* GroupedForViewHelper ensures to use an empty string instead of
`null` for array key to avoid the deprecation and considered
non-breaking because php converted null-index to `""` index
anyway.

[TASK] Address deprecations introduced by PHP 8.5 (#1236)

---

Documentation/Changelog/5.x.rst
src/Core/Parser/TemplateParser.php

This is a follow-up from #1236. The internal changes are now reflected
in the public method signatures as well.

[!!!][TASK] Don't allow null as template identifier in parser

---

Documentation/Changelog/5.x.rst
src/Core/ViewHelper/AbstractViewHelper.php
src/Core/ViewHelper/ViewHelperInvoker.php
tests/Functional/Core/Component/ComponentRenderingTest.php

Because of deprecations and other prerequisites in v4, we are now
able to accumulate all ViewHelper-related validation code in
`ViewHelperInvoker`.

[!!!][TASK] Accumulate validation code in ViewHelperInvoker

---

examples/src/ViewHelper/CustomViewHelper.php
examples/src/ViewHelper/Nested/CustomViewHelper.php
phpstan-baseline.neon
src/Core/ViewHelper/AbstractConditionViewHelper.php
src/Core/ViewHelper/AbstractTagBasedViewHelper.php
src/Core/ViewHelper/AbstractViewHelper.php
src/Core/ViewHelper/ViewHelperInterface.php
tests/Functional/Fixtures/ViewHelpers/MutableTestViewHelper.php

Type declarations are added to all ViewHelper methods as well as
all properties that are considered internal and are most likely not
redefined directly by a ViewHelper implementation. Three properties
are left out intentionally, since they are currently part of the
ViewHelper API:
* `AbstractViewHelper::$escapeOutput`
* `AbstractViewHelper::$escapeChildren`
* `AbstractTagBasedViewHelper::$tagName`
Adding type declarations to those properties would make it impossible
to create ViewHelpers that are compatible with Fluid v4 and v5.

[!!!][TASK] Add type declarations to ViewHelper classes
